/*
 * This file was automatically generated by EvoSuite
 * Fri Jan 16 11:16:48 GMT 2026
 */

package test.modele;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertNull;
import static org.junit.Assert.assertTrue;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;

import modele.Assurance;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class Assurance_ESTest extends Assurance_ESTest_scaffolding {

	@Test(timeout = 4000)
	public void test00() throws Throwable {
		Assurance assurance0 = new Assurance((String) null, (String) null, 1, 0.0, "");
		String string0 = assurance0.getTypeContrat();
		assertEquals(1, assurance0.getAnneeCouverture());
		assertNull(string0);
		assertEquals(0.0, assurance0.getMontantPaye(), 0.01);
	}

	@Test(timeout = 4000)
	public void test01() throws Throwable {
		Assurance assurance0 = new Assurance("=m`(0|u|x&/$#q", "", 1, 1, ", ann\u00E9e_Couverture=");
		String string0 = assurance0.getTypeContrat();
		assertEquals("=m`(0|u|x&/$#q", assurance0.getNumPoliceAssurance());
		assertEquals("", string0);
		assertEquals(", ann\u00E9e_Couverture=", assurance0.getBat());
		assertEquals(1, assurance0.getAnneeCouverture());
		assertEquals(1.0, assurance0.getMontantPaye(), 0.01);
	}

	@Test(timeout = 4000)
	public void test02() throws Throwable {
		Assurance assurance0 = new Assurance((String) null, "", 0, 1.0, (String) null);
		String string0 = assurance0.getNumPoliceAssurance();
		assertEquals(1.0, assurance0.getMontantPaye(), 0.01);
		assertEquals(0, assurance0.getAnneeCouverture());
		assertNull(string0);
	}

	@Test(timeout = 4000)
	public void test03() throws Throwable {
		Assurance assurance0 = new Assurance("", "", 0, 0, "kTYvY");
		String string0 = assurance0.getNumPoliceAssurance();
		assertEquals("", assurance0.getTypeContrat());
		assertEquals("kTYvY", assurance0.getBat());
		assertEquals(0, assurance0.getAnneeCouverture());
		assertEquals(0.0, assurance0.getMontantPaye(), 0.01);
		assertEquals("", string0);
	}

	@Test(timeout = 4000)
	public void test04() throws Throwable {
		Assurance assurance0 = new Assurance("KOJ|3", "", 0, (-1635.465), "c.L\"(^E*_Bk");
		assurance0.setMontantPaye(0);
		double double0 = assurance0.getMontantPaye();
		assertEquals(0.0, double0, 0.01);
	}

	@Test(timeout = 4000)
	public void test05() throws Throwable {
		Assurance assurance0 = new Assurance("?hyjfs:P4\u0001n:#", (String) null, 0, (-653.31154), "ibUa}JKcThaY/p$d");
		double double0 = assurance0.getMontantPaye();
		assertEquals("?hyjfs:P4\u0001n:#", assurance0.getNumPoliceAssurance());
		assertEquals("ibUa}JKcThaY/p$d", assurance0.getBat());
		assertEquals((-653.31154), double0, 0.01);
		assertEquals(0, assurance0.getAnneeCouverture());
	}

	@Test(timeout = 4000)
	public void test06() throws Throwable {
		Assurance assurance0 = new Assurance("=m`(0|u|x&/$#q", "", 1, 1, ", ann\u00E9e_Couverture=");
		String string0 = assurance0.getBat();
		assertEquals(1, assurance0.getAnneeCouverture());
		assertEquals("", assurance0.getTypeContrat());
		assertEquals(1.0, assurance0.getMontantPaye(), 0.01);
		assertEquals("=m`(0|u|x&/$#q", assurance0.getNumPoliceAssurance());
		assertEquals(", ann\u00E9e_Couverture=", string0);
	}

	@Test(timeout = 4000)
	public void test07() throws Throwable {
		Assurance assurance0 = new Assurance((String) null, (String) null, (-1349), (-1349), (String) null);
		assurance0.setBat("");
		assurance0.getBat();
		assertEquals((-1349), assurance0.getAnneeCouverture());
		assertEquals((-1349.0), assurance0.getMontantPaye(), 0.01);
	}

	@Test(timeout = 4000)
	public void test08() throws Throwable {
		Assurance assurance0 = new Assurance("KOJ|3", "", 0, (-1635.465), "c.L\"(^E*_Bk");
		int int0 = assurance0.getAnneeCouverture();
		assertEquals("KOJ|3", assurance0.getNumPoliceAssurance());
		assertEquals(0, int0);
		assertEquals("", assurance0.getTypeContrat());
		assertEquals("c.L\"(^E*_Bk", assurance0.getBat());
		assertEquals((-1635.465), assurance0.getMontantPaye(), 0.01);
	}

	@Test(timeout = 4000)
	public void test09() throws Throwable {
		Assurance assurance0 = new Assurance("", "", (-266), (-266), "");
		int int0 = assurance0.getAnneeCouverture();
		assertEquals((-266.0), assurance0.getMontantPaye(), 0.01);
		assertEquals((-266), int0);
	}

	@Test(timeout = 4000)
	public void test10() throws Throwable {
		Assurance assurance0 = new Assurance("", "", (-1), (-1), "");
		Assurance assurance1 = new Assurance("PD#'-", "PD#'-", (-1), 3059.540955744867,
				"Assurance [num_Police_Assurance=, type_Contrat=PD#'-, ann\u00E9e_Couverture=-1, montant_Pay\u00E9=-1.0]");
		boolean boolean0 = assurance0.equals(assurance1);
		assertFalse(boolean0);
		assertEquals("PD#'-", assurance1.getTypeContrat());
		assertEquals("PD#'-", assurance1.getNumPoliceAssurance());
		assertEquals(3059.540955744867, assurance1.getMontantPaye(), 0.01);
		assertEquals(
				"Assurance [num_Police_Assurance=, type_Contrat=PD#'-, ann\u00E9e_Couverture=-1, montant_Pay\u00E9=-1.0]",
				assurance1.getBat());
		assertEquals((-1), assurance1.getAnneeCouverture());
	}

	@Test(timeout = 4000)
	public void test11() throws Throwable {
		Assurance assurance0 = new Assurance((String) null, (String) null, (-4152), (-4152), (String) null);
		boolean boolean0 = assurance0.equals((Object) null);
		assertFalse(boolean0);
		assertEquals((-4152.0), assurance0.getMontantPaye(), 0.01);
		assertEquals((-4152), assurance0.getAnneeCouverture());
	}

	@Test(timeout = 4000)
	public void test12() throws Throwable {
		Assurance assurance0 = new Assurance("KOJ|3", "", 0, (-1635.465), "c.L\"(^E*_Bk");
		boolean boolean0 = assurance0.equals(assurance0);
		assertEquals("KOJ|3", assurance0.getNumPoliceAssurance());
		assertEquals(0, assurance0.getAnneeCouverture());
		assertTrue(boolean0);
		assertEquals("", assurance0.getTypeContrat());
		assertEquals((-1635.465), assurance0.getMontantPaye(), 0.01);
		assertEquals("c.L\"(^E*_Bk", assurance0.getBat());
	}

	@Test(timeout = 4000)
	public void test13() throws Throwable {
		Assurance assurance0 = new Assurance("^1od", ".|Vy_R62&d*[<xY;", 1, 0.0, ", mo\ntan_Pay=");
		Object object0 = new Object();
		boolean boolean0 = assurance0.equals(object0);
		assertEquals(", mo\ntan_Pay=", assurance0.getBat());
		assertEquals("^1od", assurance0.getNumPoliceAssurance());
		assertEquals(1, assurance0.getAnneeCouverture());
		assertFalse(boolean0);
		assertEquals(".|Vy_R62&d*[<xY;", assurance0.getTypeContrat());
		assertEquals(0.0, assurance0.getMontantPaye(), 0.01);
	}

	@Test(timeout = 4000)
	public void test14() throws Throwable {
		Assurance assurance0 = new Assurance("^1od", ".|Vy_R62&d*[<xY;", 1, 0.0, ", mo\ntan_Pay=");
		String string0 = assurance0.getTypeContrat();
		assertEquals(0.0, assurance0.getMontantPaye(), 0.01);
		assertEquals(".|Vy_R62&d*[<xY;", string0);
		assertEquals(1, assurance0.getAnneeCouverture());
		assertEquals("^1od", assurance0.getNumPoliceAssurance());
		assertEquals(", mo\ntan_Pay=", assurance0.getBat());
	}

	@Test(timeout = 4000)
	public void test15() throws Throwable {
		Assurance assurance0 = new Assurance("", "", 0, 0, (String) null);
		String string0 = assurance0.getBat();
		assertNull(string0);
		assertEquals(0.0, assurance0.getMontantPaye(), 0.01);
		assertEquals(0, assurance0.getAnneeCouverture());
	}

	@Test(timeout = 4000)
	public void test16() throws Throwable {
		Assurance assurance0 = new Assurance("KOJ|3", "", 0, (-1635.465), "c.L\"(^E*_Bk");
		assertEquals("", assurance0.getTypeContrat());

		assurance0.setTypeContrat(
				"Assurance [num_Police_Assurance=KOJ|3, type_Contrat=, ann\u00E9e_Couverture=0, montant_Pay\u00E9=-1635.465]");
		assertEquals("KOJ|3", assurance0.getNumPoliceAssurance());
	}

	@Test(timeout = 4000)
	public void test17() throws Throwable {
		Assurance assurance0 = new Assurance("^1od", ".|Vy_R62&d*[<xY;", 1, 0.0, ", mo\ntan_Pay=");
		assertEquals("^1od", assurance0.getNumPoliceAssurance());

		assurance0.setNumPoliceAssurance("^1od");
		assertEquals(", mo\ntan_Pay=", assurance0.getBat());
		assertEquals(1, assurance0.getAnneeCouverture());
		assertEquals(0.0, assurance0.getMontantPaye(), 0.01);
		assertEquals(".|Vy_R62&d*[<xY;", assurance0.getTypeContrat());
	}

	@Test(timeout = 4000)
	public void test18() throws Throwable {
		Assurance assurance0 = new Assurance("KOJ|3", "", 0, (-1635.465), "c.L\"(^E*_Bk");
		String string0 = assurance0.getNumPoliceAssurance();
		assertEquals("KOJ|3", string0);
		assertEquals((-1635.465), assurance0.getMontantPaye(), 0.01);
		assertEquals(0, assurance0.getAnneeCouverture());
		assertEquals("", assurance0.getTypeContrat());
		assertEquals("c.L\"(^E*_Bk", assurance0.getBat());
	}

	@Test(timeout = 4000)
	public void test19() throws Throwable {
		Assurance assurance0 = new Assurance("^1od", ".|Vy_R62&d*[<xY;", 1, 0.0, ", mo\ntan_Pay=");
		assurance0.setAnneeCouverture((-1332));
		assertEquals((-1332), assurance0.getAnneeCouverture());
	}

	@Test(timeout = 4000)
	public void test20() throws Throwable {
		Assurance assurance0 = new Assurance("KOJ|3", "", 0, (-1635.465), "c.L\"(^E*_Bk");
		String string0 = assurance0.toString();
		assertEquals("c.L\"(^E*_Bk", assurance0.getBat());
		assertEquals(
				"Assurance [num_Police_Assurance=KOJ|3, type_Contrat=, ann\u00E9e_Couverture=0, montant_Pay\u00E9=-1635.465]",
				string0);
	}

	@Test(timeout = 4000)
	public void test21() throws Throwable {
		Assurance assurance0 = new Assurance("KOJ|3", "", 0, (-1635.465), "c.L\"(^E*_Bk");
		assurance0.hashCode();
		assertEquals("", assurance0.getTypeContrat());
		assertEquals("c.L\"(^E*_Bk", assurance0.getBat());
		assertEquals(0, assurance0.getAnneeCouverture());
		assertEquals((-1635.465), assurance0.getMontantPaye(), 0.01);
		assertEquals("KOJ|3", assurance0.getNumPoliceAssurance());
	}

	@Test(timeout = 4000)
	public void test22() throws Throwable {
		Assurance assurance0 = new Assurance("xS65})t`J-l", "xS65})t`J-l", 22, 22, "xS65})t`J-l");
		double double0 = assurance0.getMontantPaye();
		assertEquals(22.0, double0, 0.01);
		assertEquals(22, assurance0.getAnneeCouverture());
	}

	@Test(timeout = 4000)
	public void test23() throws Throwable {
		Assurance assurance0 = new Assurance("xS65})t`J-l", "xS65})t`J-l", 1147, 1147, "xS65})t`J-l");
		int int0 = assurance0.getAnneeCouverture();
		assertEquals(1147, int0);
		assertEquals(1147.0, assurance0.getMontantPaye(), 0.01);
	}
}
