/*
 * This file was automatically generated by EvoSuite
 * Fri Jan 16 13:08:51 GMT 2026
 */

package test.modele;

import static org.evosuite.runtime.EvoAssertions.verifyException;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertNull;
import static org.junit.Assert.assertSame;
import static org.junit.Assert.assertTrue;
import static org.junit.Assert.fail;

import java.time.LocalDate;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.time.MockLocalDate;
import org.junit.Test;
import org.junit.runner.RunWith;

import modele.Batiment;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class Batiment_ESTest extends Batiment_ESTest_scaffolding {

	@Test(timeout = 4000)
	public void test00() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Batiment batiment0 = new Batiment("", localDate0, "", "", "", "");
		try {
			batiment0.setIdBat("!Zh9");
			fail("Expecting exception: IllegalArgumentException");

		} catch (IllegalArgumentException e) {
			//
			// L'identificateur du b\u00E2timent n'est pas valable !
			//
			verifyException("modele.Batiment", e);
		}
	}

	@Test(timeout = 4000)
	public void test01() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Batiment batiment0 = new Batiment((String) null, localDate0, (String) null, "/", "/", "");
		assertEquals("/", batiment0.getVille());

		batiment0.setVille((String) null);
		batiment0.getVille();
		assertEquals("", batiment0.getNumFiscal());
		assertEquals("/", batiment0.getCodePostal());
	}

	@Test(timeout = 4000)
	public void test02() throws Throwable {
		Batiment batiment0 = new Batiment("k", (LocalDate) null, "\"N`5|R0M1&29?M", "", "", "");
		String string0 = batiment0.getVille();
		assertEquals("k", batiment0.getIdBat());
		assertEquals("", string0);
		assertEquals("", batiment0.getCodePostal());
		assertEquals("\"N`5|R0M1&29?M", batiment0.getAdresse());
		assertEquals("", batiment0.getNumFiscal());
	}

	@Test(timeout = 4000)
	public void test03() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Batiment batiment0 = new Batiment((String) null, localDate0, (String) null, (String) null, (String) null,
				(String) null);
		String string0 = batiment0.getNumFiscal();
		assertNull(string0);
	}

	@Test(timeout = 4000)
	public void test04() throws Throwable {
		Batiment batiment0 = new Batiment("NnLw$ ", (LocalDate) null, "NnLw$ ", "", "NnLw$ ", "");
		assertEquals("", batiment0.getNumFiscal());

		batiment0.setNumFiscal("9p[SGx7Y");
		batiment0.getNumFiscal();
		assertEquals("NnLw$ ", batiment0.getVille());
	}

	@Test(timeout = 4000)
	public void test05() throws Throwable {
		Batiment batiment0 = new Batiment((String) null, (LocalDate) null, "e4Mpm9UK", "e4Mpm9UK", "", "");
		String string0 = batiment0.getIdBat();
		assertEquals("", batiment0.getNumFiscal());
		assertNull(string0);
		assertEquals("e4Mpm9UK", batiment0.getCodePostal());
		assertEquals("", batiment0.getVille());
		assertEquals("e4Mpm9UK", batiment0.getAdresse());
	}

	@Test(timeout = 4000)
	public void test06() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Batiment batiment0 = new Batiment("", localDate0, "", "", "", "");
		String string0 = batiment0.getIdBat();
		assertEquals("", string0);
	}

	@Test(timeout = 4000)
	public void test07() throws Throwable {
		LocalDate localDate0 = MockLocalDate.ofEpochDay(0L);
		Batiment batiment0 = new Batiment("", localDate0, (String) null, (String) null, (String) null, "");
		LocalDate localDate1 = batiment0.getDateConstruction();
		assertSame(localDate0, localDate1);
	}

	@Test(timeout = 4000)
	public void test08() throws Throwable {
		Batiment batiment0 = new Batiment("", (LocalDate) null, "", "t.|lk*\"J%B'ME:q]", "", "");
		assertEquals("t.|lk*\"J%B'ME:q]", batiment0.getCodePostal());

		batiment0.setCodePostal((String) null);
		batiment0.getCodePostal();
		assertEquals("", batiment0.getNumFiscal());
		assertEquals("", batiment0.getIdBat());
		assertEquals("", batiment0.getAdresse());
		assertEquals("", batiment0.getVille());
	}

	@Test(timeout = 4000)
	public void test09() throws Throwable {
		Batiment batiment0 = new Batiment((String) null, (LocalDate) null, "e4Mpm9UK", "e4Mpm9UK", "", "");
		String string0 = batiment0.getCodePostal();
		assertEquals("", batiment0.getVille());
		assertNotNull(string0);
		assertEquals("e4Mpm9UK", batiment0.getAdresse());
		assertEquals("e4Mpm9UK", string0);
		assertEquals("", batiment0.getNumFiscal());
	}

	@Test(timeout = 4000)
	public void test10() throws Throwable {
		Batiment batiment0 = new Batiment("NnLw$ ", (LocalDate) null, "NnLw$ ", "", "NnLw$ ", "");
		String string0 = batiment0.getAdresse();
		assertEquals("", batiment0.getCodePostal());
		assertEquals("NnLw$ ", batiment0.getVille());
		assertEquals("", batiment0.getNumFiscal());
		assertEquals("NnLw$ ", string0);
		assertEquals("NnLw$ ", batiment0.getIdBat());
	}

	@Test(timeout = 4000)
	public void test11() throws Throwable {
		Batiment batiment0 = new Batiment("", (LocalDate) null, "", "t.|lk*\"J%B'ME:q]", "", "");
		String string0 = batiment0.getAdresse();
		assertEquals("", string0);
		assertEquals("", batiment0.getVille());
		assertEquals("", batiment0.getIdBat());
		assertEquals("t.|lk*\"J%B'ME:q]", batiment0.getCodePostal());
		assertEquals("", batiment0.getNumFiscal());
	}

	@Test(timeout = 4000)
	public void test12() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Batiment batiment0 = new Batiment((String) null, localDate0, (String) null, (String) null, (String) null,
				(String) null);
		// Undeclared exception!
		try {
			batiment0.setIdBat((String) null);
			fail("Expecting exception: NullPointerException");

		} catch (NullPointerException e) {
			//
			// no message in exception (getMessage() returned null)
			//
			verifyException("modele.Batiment", e);
		}
	}

	@Test(timeout = 4000)
	public void test13() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Batiment batiment0 = new Batiment("", localDate0, "", "", "", "");
		boolean boolean0 = batiment0.equals(localDate0);
		assertFalse(boolean0);
	}

	@Test(timeout = 4000)
	public void test14() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Batiment batiment0 = new Batiment((String) null, localDate0, (String) null, (String) null, (String) null,
				(String) null);
		boolean boolean0 = batiment0.equals((Object) null);
		assertFalse(boolean0);
	}

	@Test(timeout = 4000)
	public void test15() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Batiment batiment0 = new Batiment((String) null, localDate0, (String) null, (String) null, (String) null,
				(String) null);
		boolean boolean0 = batiment0.equals(batiment0);
		assertTrue(boolean0);
	}

	@Test(timeout = 4000)
	public void test16() throws Throwable {
		Batiment batiment0 = new Batiment("NnLw$ ", (LocalDate) null, "NnLw$ ", "", "NnLw$ ", "");
		Batiment batiment1 = new Batiment("NnLw$ ", (LocalDate) null, "", "", "NnLw$ ", "");
		boolean boolean0 = batiment0.equals(batiment1);
		assertEquals("NnLw$ ", batiment1.getIdBat());
		assertEquals("NnLw$ ", batiment0.getAdresse());
		assertEquals("", batiment1.getAdresse());
		assertEquals("NnLw$ ", batiment1.getVille());
		assertTrue(boolean0);
		assertEquals("", batiment0.getCodePostal());
		assertEquals("", batiment0.getNumFiscal());
	}

	@Test(timeout = 4000)
	public void test17() throws Throwable {
		Batiment batiment0 = new Batiment("NnLw$ ", (LocalDate) null, "NnLw$ ", "", "NnLw$ ", "");
		try {
			batiment0.setIdBat("B\u00E2timent [id_Bat=NnLw$ , date_Construction=null, adresse=]");
			fail("Expecting exception: IllegalArgumentException");

		} catch (IllegalArgumentException e) {
			//
			// L'identificateur du b\u00E2timent n'est pas valable !
			//
			verifyException("modele.Batiment", e);
		}
	}

	@Test(timeout = 4000)
	public void test18() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Batiment batiment0 = new Batiment("", localDate0, "", "", "", "");
		batiment0.setIdBat(", adresse=");
		assertEquals(", adresse=", batiment0.getIdBat());
	}

	@Test(timeout = 4000)
	public void test19() throws Throwable {
		Batiment batiment0 = new Batiment("NnLw$ ", (LocalDate) null, "NnLw$ ", "", "NnLw$ ", "");
		String string0 = batiment0.getCodePostal();
		assertEquals("", string0);
		assertEquals("", batiment0.getNumFiscal());
		assertEquals("NnLw$ ", batiment0.getIdBat());
		assertEquals("NnLw$ ", batiment0.getVille());
		assertEquals("NnLw$ ", batiment0.getAdresse());
	}

	@Test(timeout = 4000)
	public void test20() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Batiment batiment0 = new Batiment((String) null, localDate0, (String) null, (String) null, (String) null,
				(String) null);
		String string0 = batiment0.getAdresse();
		assertNull(string0);
	}

	@Test(timeout = 4000)
	public void test21() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Batiment batiment0 = new Batiment((String) null, localDate0, (String) null, "/", "/", "");
		String string0 = batiment0.getVille();
		assertNotNull(string0);
		assertEquals("", batiment0.getNumFiscal());
		assertEquals("/", string0);
		assertEquals("/", batiment0.getCodePostal());
	}

	@Test(timeout = 4000)
	public void test22() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Batiment batiment0 = new Batiment("", localDate0, "", "", "", "");
		batiment0.setDateConstruction(localDate0);
		assertEquals("", batiment0.getAdresse());
	}

	@Test(timeout = 4000)
	public void test23() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Batiment batiment0 = new Batiment((String) null, localDate0, (String) null, (String) null, (String) null,
				(String) null);
		batiment0.hashCode();
	}

	@Test(timeout = 4000)
	public void test24() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Batiment batiment0 = new Batiment("", localDate0, "", "", "", "");
		batiment0.setAdresse("]");
		assertEquals("", batiment0.getVille());
	}

	@Test(timeout = 4000)
	public void test25() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Batiment batiment0 = new Batiment("", localDate0, "", "", "", "");
		String string0 = batiment0.toString();
		assertEquals("B\u00E2timent [id_Bat=, date_Construction=2014-02-14, adresse=]", string0);
	}

	@Test(timeout = 4000)
	public void test26() throws Throwable {
		Batiment batiment0 = new Batiment("NnLw$ ", (LocalDate) null, "NnLw$ ", "", "NnLw$ ", "");
		batiment0.getDateConstruction();
		assertEquals("", batiment0.getNumFiscal());
		assertEquals("NnLw$ ", batiment0.getVille());
		assertEquals("NnLw$ ", batiment0.getAdresse());
		assertEquals("", batiment0.getCodePostal());
		assertEquals("NnLw$ ", batiment0.getIdBat());
	}

	@Test(timeout = 4000)
	public void test27() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Batiment batiment0 = new Batiment("[.@%OW%oc)}QD3!/t", localDate0, "[.@%OW%oc)}QD3!/t", "[.@%OW%oc)}QD3!/t",
				"[.@%OW%oc)}QD3!/t", "[.@%OW%oc)}QD3!/t");
		String string0 = batiment0.getIdBat();
		assertEquals("[.@%OW%oc)}QD3!/t", string0);
	}

	@Test(timeout = 4000)
	public void test28() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Batiment batiment0 = new Batiment("", localDate0, "", "", "", "");
		String string0 = batiment0.getNumFiscal();
		assertEquals("", string0);
	}
}
