/*
 * This file was automatically generated by EvoSuite
 * Fri Jan 16 13:13:35 GMT 2026
 */

package test.modele;

import static org.evosuite.runtime.EvoAssertions.verifyException;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertNull;
import static org.junit.Assert.assertTrue;
import static org.junit.Assert.fail;

import java.time.LocalDate;
import java.time.Period;
import java.time.chrono.IsoChronology;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.time.MockLocalDate;
import org.evosuite.runtime.mock.java.time.chrono.MockIsoChronology;
import org.junit.Test;
import org.junit.runner.RunWith;

import modele.BienLouable;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class BienLouable_ESTest extends BienLouable_ESTest_scaffolding {

	@Test(timeout = 4000)
	public void test00() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Integer integer0 = new Integer((-1695));
		BienLouable bienLouable0 = new BienLouable("", ", dateConstruction=", "in4D&", "+44+1B@Z", "W)v8V|<k.6|}X",
				(-1695), (-3325.3557F), "W)v8V|<k.6|}X", localDate0, 0.0F, (-1695), (-3325.3557F), 2254.078833540974,
				"in4D&", integer0);
		try {
			bienLouable0.setNumeroFiscal("W)v8V|<k.6|}X");
			fail("Expecting exception: IllegalArgumentException");

		} catch (IllegalArgumentException e) {
			//
			// La taille du num\u00E9ro fiscal n'est pas valable !
			//
			verifyException("modele.BienLouable", e);
		}
	}

	@Test(timeout = 4000)
	public void test01() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Integer integer0 = new Integer((-2344));
		BienLouable bienLouable0 = new BienLouable("", "", "", (String) null, "", (-441.46027F), (-441.46027F), "",
				localDate0, 2496.6199F, (-2344), (-2344), (-441.46027F), "", integer0);
		bienLouable0.setPourcentageOrduresMenageres(0.0);
		assertEquals(0.0, bienLouable0.getPourcentageOrduresMenageres(), 0.01);
	}

	@Test(timeout = 4000)
	public void test02() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Integer integer0 = new Integer((-2344));
		BienLouable bienLouable0 = new BienLouable("", "", "", (String) null, "", (-441.46027F), (-441.46027F), "",
				localDate0, 2496.6199F, (-2344), (-2344), (-441.46027F), "", integer0);
		bienLouable0.setPourcentageOrduresMenageres(100.0);
		assertEquals(100.0, bienLouable0.getPourcentageOrduresMenageres(), 0.01);
	}

	@Test(timeout = 4000)
	public void test03() throws Throwable {
		Integer integer0 = new Integer((-1208));
		BienLouable bienLouable0 = new BienLouable("", "", "", "", (String) null, 2314.688F, 2314.688F, (String) null,
				(LocalDate) null, 2314.688F, (-1208), 100.0, 0.0, "", integer0);
		String string0 = bienLouable0.getVille();
		assertEquals(0.0, bienLouable0.getPourcentageOrduresMenageres(), 0.01);
		assertEquals(2314.688F, bienLouable0.getLoyer(), 0.01F);
		assertNull(string0);
		assertEquals(2314.688F, bienLouable0.getProvisionPourCharges(), 0.01F);
		assertEquals(2314.688F, bienLouable0.getSurfaceHabitable(), 0.01F);
		assertEquals((-1208), bienLouable0.getNbPieces());
		assertEquals(100.0, bienLouable0.getPourcentageEntretienPartiesCommunes(), 0.01);
	}

	@Test(timeout = 4000)
	public void test04() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Integer integer0 = new Integer(12);
		BienLouable bienLouable0 = new BienLouable("", "", "uI8u;@2,~Tk-VC,g", (String) null, "", 1.0F, 1.0F,
				"OK&f\"YU#zh 4MPD", localDate0, 1.0F, 2146487172, 1.0F, 1.0F, "", integer0);
		String string0 = bienLouable0.getVille();
		assertEquals(1.0F, bienLouable0.getLoyer(), 0.01F);
		assertEquals("", string0);
		assertEquals(1.0, bienLouable0.getPourcentageEntretienPartiesCommunes(), 0.01);
		assertEquals("", bienLouable0.getIdBat());
		assertEquals(1.0F, bienLouable0.getSurfaceHabitable(), 0.01F);
		assertEquals("OK&f\"YU#zh 4MPD", bienLouable0.getTypeBien());
		assertEquals(2146487172, bienLouable0.getNbPieces());
		assertEquals(1.0, bienLouable0.getPourcentageOrduresMenageres(), 0.01);
		assertEquals("", bienLouable0.getIdBien());
		assertEquals(1.0F, bienLouable0.getProvisionPourCharges(), 0.01F);
		assertNotNull(string0);
		assertEquals("uI8u;@2,~Tk-VC,g", bienLouable0.getAdresse());
		assertEquals("", bienLouable0.getNumeroFiscal());
	}

	@Test(timeout = 4000)
	public void test05() throws Throwable {
		Integer integer0 = new Integer((-1208));
		BienLouable bienLouable0 = new BienLouable("", "", "", "", (String) null, 2314.688F, 2314.688F, (String) null,
				(LocalDate) null, 2314.688F, (-1208), 100.0, 0.0, "", integer0);
		String string0 = bienLouable0.getTypeBien();
		assertEquals((-1208), bienLouable0.getNbPieces());
		assertEquals(2314.688F, bienLouable0.getLoyer(), 0.01F);
		assertNull(string0);
		assertEquals(2314.688F, bienLouable0.getProvisionPourCharges(), 0.01F);
		assertEquals(2314.688F, bienLouable0.getSurfaceHabitable(), 0.01F);
		assertEquals(0.0, bienLouable0.getPourcentageOrduresMenageres(), 0.01);
		assertEquals(100.0, bienLouable0.getPourcentageEntretienPartiesCommunes(), 0.01);
	}

	@Test(timeout = 4000)
	public void test06() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		BienLouable bienLouable0 = new BienLouable(", typeBien=", "KdsDr(", "", "]Mg\"xrA7&2N3~g(Wx",
				", pourcentageOrduresM\u00E9nag\u00E8res=", (-1.0F), (-1839.0756F), "", localDate0, (-1.0F), 0,
				554.90457064, 0.0, ", pourcentageOrduresM\u00E9nag\u00E8res=", (Integer) null);
		String string0 = bienLouable0.getTypeBien();
		assertEquals(", pourcentageOrduresM\u00E9nag\u00E8res=", bienLouable0.getVille());
		assertEquals("", bienLouable0.getAdresse());
		assertEquals((-1.0F), bienLouable0.getSurfaceHabitable(), 0.01F);
		assertEquals("KdsDr(", bienLouable0.getIdBat());
		assertEquals("]Mg\"xrA7&2N3~g(Wx", bienLouable0.getCodePostal());
		assertEquals((-1.0F), bienLouable0.getLoyer(), 0.01F);
		assertEquals(0, bienLouable0.getNbPieces());
		assertEquals("", string0);
		assertEquals(", pourcentageOrduresM\u00E9nag\u00E8res=", bienLouable0.getNumeroFiscal());
		assertEquals((-1839.0756F), bienLouable0.getProvisionPourCharges(), 0.01F);
		assertEquals(554.90457064, bienLouable0.getPourcentageEntretienPartiesCommunes(), 0.01);
		assertEquals(0.0, bienLouable0.getPourcentageOrduresMenageres(), 0.01);
		assertEquals(", typeBien=", bienLouable0.getIdBien());
	}

	@Test(timeout = 4000)
	public void test07() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Integer integer0 = new Integer(0);
		BienLouable bienLouable0 = new BienLouable("", "", (String) null, "", (String) null, 1124.542F, (-1.0F),
				(String) null, localDate0, 0.0F, 0, (-3625.66F), 100.0, "8Sie)=n}\"", integer0);
		float float0 = bienLouable0.getSurfaceHabitable();
		assertEquals(0, bienLouable0.getNbPieces());
		assertEquals("", bienLouable0.getIdBat());
		assertEquals(0.0F, float0, 0.01F);
		assertEquals(1124.542F, bienLouable0.getLoyer(), 0.01F);
		assertEquals("", bienLouable0.getCodePostal());
		assertEquals("8Sie)=n}\"", bienLouable0.getNumeroFiscal());
		assertEquals((-1.0F), bienLouable0.getProvisionPourCharges(), 0.01F);
		assertEquals((-3625.659912109375), bienLouable0.getPourcentageEntretienPartiesCommunes(), 0.01);
		assertEquals("", bienLouable0.getIdBien());
		assertEquals(100.0, bienLouable0.getPourcentageOrduresMenageres(), 0.01);
	}

	@Test(timeout = 4000)
	public void test08() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Integer integer0 = new Integer(0);
		BienLouable bienLouable0 = new BienLouable((String) null, (String) null, "djcT]|nRJ})+bi+39",
				", pourcentageEntretienPartiesCommunes=", ", pourcentageEntretienPartiesCommunes=", 1354.8792F, 0.0F,
				(String) null, localDate0, 583.7667F, 0, 0.0, 0.0F, (String) null, integer0);
		float float0 = bienLouable0.getSurfaceHabitable();
		assertEquals(", pourcentageEntretienPartiesCommunes=", bienLouable0.getCodePostal());
		assertEquals(1354.8792F, bienLouable0.getLoyer(), 0.01F);
		assertEquals(0.0, bienLouable0.getPourcentageOrduresMenageres(), 0.01);
		assertEquals(583.7667F, float0, 0.01F);
		assertEquals(0.0F, bienLouable0.getProvisionPourCharges(), 0.01F);
		assertEquals(0.0, bienLouable0.getPourcentageEntretienPartiesCommunes(), 0.01);
		assertEquals("djcT]|nRJ})+bi+39", bienLouable0.getAdresse());
		assertEquals(0, bienLouable0.getNbPieces());
		assertEquals(", pourcentageEntretienPartiesCommunes=", bienLouable0.getVille());
	}

	@Test(timeout = 4000)
	public void test09() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Integer integer0 = new Integer(0);
		BienLouable bienLouable0 = new BienLouable("BienLouable [idBien=", "BienLouable [idBien=",
				", surfaceHabitable=", ", surfaceHabitable=", "", (-1.0F), (-1.0F), "", localDate0, (-1.0F), 0, (-1.0F),
				2544.6774262597087, ", surfaceHabitable=", integer0);
		bienLouable0.setProvisionPourCharges(0.0F);
		float float0 = bienLouable0.getProvisionPourCharges();
		assertEquals(0.0F, float0, 0.01F);
	}

	@Test(timeout = 4000)
	public void test10() throws Throwable {
		Integer integer0 = new Integer(138);
		BienLouable bienLouable0 = new BienLouable("", "", "", "", "", 1.0F, 1.0F, ", codePostal=", (LocalDate) null,
				2725.0F, 2146432698, 2146432698, 3265.0, "", integer0);
		float float0 = bienLouable0.getProvisionPourCharges();
		assertEquals("", bienLouable0.getCodePostal());
		assertEquals(2725.0F, bienLouable0.getSurfaceHabitable(), 0.01F);
		assertEquals("", bienLouable0.getAdresse());
		assertEquals(3265.0, bienLouable0.getPourcentageOrduresMenageres(), 0.01);
		assertEquals(2146432698, bienLouable0.getNbPieces());
		assertEquals(2.146432698E9, bienLouable0.getPourcentageEntretienPartiesCommunes(), 0.01);
		assertEquals(1.0F, float0, 0.01F);
		assertEquals(1.0F, bienLouable0.getLoyer(), 0.01F);
		assertEquals("", bienLouable0.getNumeroFiscal());
		assertEquals(", codePostal=", bienLouable0.getTypeBien());
		assertEquals("", bienLouable0.getVille());
		assertEquals("", bienLouable0.getIdBien());
		assertEquals("", bienLouable0.getIdBat());
	}

	@Test(timeout = 4000)
	public void test11() throws Throwable {
		Integer integer0 = new Integer((-1208));
		BienLouable bienLouable0 = new BienLouable("", "", "", "", (String) null, 2314.688F, 2314.688F, (String) null,
				(LocalDate) null, 2314.688F, (-1208), 100.0, 0.0, "", integer0);
		double double0 = bienLouable0.getPourcentageOrduresMenageres();
		assertEquals(2314.688F, bienLouable0.getProvisionPourCharges(), 0.01F);
		assertEquals(2314.688F, bienLouable0.getSurfaceHabitable(), 0.01F);
		assertEquals(100.0, bienLouable0.getPourcentageEntretienPartiesCommunes(), 0.01);
		assertEquals(0.0, double0, 0.01);
		assertEquals(2314.688F, bienLouable0.getLoyer(), 0.01F);
		assertEquals((-1208), bienLouable0.getNbPieces());
	}

	@Test(timeout = 4000)
	public void test12() throws Throwable {
		Period period0 = Period.of((-1), (-1), (-1));
		IsoChronology isoChronology0 = period0.getChronology();
		LocalDate localDate0 = MockIsoChronology.dateNow(isoChronology0);
		Integer integer0 = new Integer((-663));
		BienLouable bienLouable0 = new BienLouable("", "", "", "", "", 2762.5095F, 1.0F, "", localDate0, (-1), 404,
				1.0F, 404, "", integer0);
		double double0 = bienLouable0.getPourcentageOrduresMenageres();
		assertEquals(404, bienLouable0.getNbPieces());
		assertEquals(2762.5095F, bienLouable0.getLoyer(), 0.01F);
		assertEquals(1.0, bienLouable0.getPourcentageEntretienPartiesCommunes(), 0.01);
		assertEquals(1.0F, bienLouable0.getProvisionPourCharges(), 0.01F);
		assertEquals((-1.0F), bienLouable0.getSurfaceHabitable(), 0.01F);
		assertEquals(404.0, double0, 0.01);
	}

	@Test(timeout = 4000)
	public void test13() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		BienLouable bienLouable0 = new BienLouable(", typeBien=", "KdsDr(", "", "]Mg\"xrA7&2N3~g(Wx",
				", pourcentageOrduresM\u00E9nag\u00E8res=", (-1.0F), (-1839.0756F), "", localDate0, (-1.0F), 0,
				554.90457064, 0.0, ", pourcentageOrduresM\u00E9nag\u00E8res=", (Integer) null);
		assertEquals(554.90457064, bienLouable0.getPourcentageEntretienPartiesCommunes(), 0.01);

		bienLouable0.setPourcentageEntretienPartiesCommunes(0);
		double double0 = bienLouable0.getPourcentageEntretienPartiesCommunes();
		assertEquals(0.0, double0, 0.01);
	}

	@Test(timeout = 4000)
	public void test14() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Integer integer0 = new Integer(0);
		BienLouable bienLouable0 = new BienLouable("", "", (String) null, "", (String) null, 1124.542F, (-1.0F),
				(String) null, localDate0, 0.0F, 0, (-3625.66F), 100.0, "8Sie)=n}\"", integer0);
		bienLouable0.setPourcentageEntretienPartiesCommunes(1.0);
		double double0 = bienLouable0.getPourcentageEntretienPartiesCommunes();
		assertEquals(1.0, double0, 0.01);
	}

	@Test(timeout = 4000)
	public void test15() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Integer integer0 = new Integer(0);
		BienLouable bienLouable0 = new BienLouable((String) null, ",69m", (String) null, (String) null, (String) null,
				1124.542F, 1124.542F, (String) null, localDate0, 0.0F, 0, (-3625.66F), (-4537.0), (String) null,
				integer0);
		String string0 = bienLouable0.getNumeroFiscal();
		assertNull(string0);
		assertEquals(0, bienLouable0.getNbPieces());
		assertEquals(0.0F, bienLouable0.getSurfaceHabitable(), 0.01F);
		assertEquals((-3625.659912109375), bienLouable0.getPourcentageEntretienPartiesCommunes(), 0.01);
		assertEquals(1124.542F, bienLouable0.getProvisionPourCharges(), 0.01F);
		assertEquals(1124.542F, bienLouable0.getLoyer(), 0.01F);
		assertEquals((-4537.0), bienLouable0.getPourcentageOrduresMenageres(), 0.01);
	}

	@Test(timeout = 4000)
	public void test16() throws Throwable {
		LocalDate localDate0 = MockLocalDate.ofEpochDay((-2244L));
		Integer integer0 = new Integer(0);
		BienLouable bienLouable0 = new BienLouable("6e", "6e", "6e", "", "", 1.0F, 1.0F, ", dateConstruction=",
				localDate0, 0.0F, 0, 1962.816563437166, 0.0, "", integer0);
		String string0 = bienLouable0.getNumeroFiscal();
		assertEquals("6e", bienLouable0.getAdresse());
		assertEquals(1.0F, bienLouable0.getLoyer(), 0.01F);
		assertEquals(1.0F, bienLouable0.getProvisionPourCharges(), 0.01F);
		assertEquals("6e", bienLouable0.getIdBien());
		assertEquals(0, bienLouable0.getNbPieces());
		assertEquals(0.0F, bienLouable0.getSurfaceHabitable(), 0.01F);
		assertEquals(", dateConstruction=", bienLouable0.getTypeBien());
		assertEquals(1962.816563437166, bienLouable0.getPourcentageEntretienPartiesCommunes(), 0.01);
		assertEquals("", bienLouable0.getVille());
		assertEquals("6e", bienLouable0.getIdBat());
		assertEquals("", string0);
		assertEquals("", bienLouable0.getCodePostal());
		assertEquals(0.0, bienLouable0.getPourcentageOrduresMenageres(), 0.01);
	}

	@Test(timeout = 4000)
	public void test17() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Integer integer0 = new Integer(423);
		BienLouable bienLouable0 = new BienLouable("", "", "", "U5_B^}O1f", "P9V{Og|1#-|P", 436.13F, 436.13F, "",
				localDate0, (-1255.767F), 0, 0.0, (-1255.767F), "&p7SNo/d oC]t", integer0);
		int int0 = bienLouable0.getNbPieces();
		assertEquals("P9V{Og|1#-|P", bienLouable0.getVille());
		assertEquals("", bienLouable0.getIdBat());
		assertEquals(436.13F, bienLouable0.getLoyer(), 0.01F);
		assertEquals("&p7SNo/d oC]t", bienLouable0.getNumeroFiscal());
		assertEquals(436.13F, bienLouable0.getProvisionPourCharges(), 0.01F);
		assertEquals(0.0, bienLouable0.getPourcentageEntretienPartiesCommunes(), 0.01);
		assertEquals("", bienLouable0.getAdresse());
		assertEquals("U5_B^}O1f", bienLouable0.getCodePostal());
		assertEquals((-1255.767F), bienLouable0.getSurfaceHabitable(), 0.01F);
		assertEquals("", bienLouable0.getTypeBien());
		assertEquals("", bienLouable0.getIdBien());
		assertEquals((-1255.7669677734375), bienLouable0.getPourcentageOrduresMenageres(), 0.01);
		assertEquals(0, int0);
	}

	@Test(timeout = 4000)
	public void test18() throws Throwable {
		Integer integer0 = new Integer((-1348));
		BienLouable bienLouable0 = new BienLouable("<_!zC", (String) null, "<_!zC", "<_!zC", (String) null, (-1.0F),
				0.0F, "", (LocalDate) null, 0.0F, 12, (-1039.1270776484403), 3325.612513, (String) null, integer0);
		int int0 = bienLouable0.getNbPieces();
		assertEquals((-1039.1270776484403), bienLouable0.getPourcentageEntretienPartiesCommunes(), 0.01);
		assertEquals("<_!zC", bienLouable0.getIdBien());
		assertEquals(0.0F, bienLouable0.getSurfaceHabitable(), 0.01F);
		assertEquals(0.0F, bienLouable0.getProvisionPourCharges(), 0.01F);
		assertEquals((-1.0F), bienLouable0.getLoyer(), 0.01F);
		assertEquals(3325.612513, bienLouable0.getPourcentageOrduresMenageres(), 0.01);
		assertEquals("<_!zC", bienLouable0.getAdresse());
		assertEquals("<_!zC", bienLouable0.getCodePostal());
		assertEquals(12, int0);
		assertEquals("", bienLouable0.getTypeBien());
	}

	@Test(timeout = 4000)
	public void test19() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Integer integer0 = new Integer((-2126221433));
		BienLouable bienLouable0 = new BienLouable("", ", dateConstruction=", "", "", (String) null, 0.0F, (-1250.053F),
				"", localDate0, 1099.6345F, 2757, (-1250.053F), 1099.6345F, (String) null, integer0);
		float float0 = bienLouable0.getLoyer();
		assertEquals(1099.6345F, bienLouable0.getSurfaceHabitable(), 0.01F);
		assertEquals(1099.634521484375, bienLouable0.getPourcentageOrduresMenageres(), 0.01);
		assertEquals((-1250.052978515625), bienLouable0.getPourcentageEntretienPartiesCommunes(), 0.01);
		assertEquals("", bienLouable0.getIdBien());
		assertEquals(2757, bienLouable0.getNbPieces());
		assertEquals("", bienLouable0.getTypeBien());
		assertEquals(", dateConstruction=", bienLouable0.getIdBat());
		assertEquals("", bienLouable0.getCodePostal());
		assertEquals((-1250.053F), bienLouable0.getProvisionPourCharges(), 0.01F);
		assertEquals(0.0F, float0, 0.01F);
		assertEquals("", bienLouable0.getAdresse());
	}

	@Test(timeout = 4000)
	public void test20() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Integer integer0 = new Integer(0);
		BienLouable bienLouable0 = new BienLouable("", "", (String) null, "", (String) null, 1138.8206F, (-1.0F),
				(String) null, localDate0, 0.0F, 0, (-3625.66F), 100.0, "8Sie)=n}\"", integer0);
		float float0 = bienLouable0.getLoyer();
		assertEquals("", bienLouable0.getIdBien());
		assertEquals(100.0, bienLouable0.getPourcentageOrduresMenageres(), 0.01);
		assertEquals(1138.8206F, float0, 0.01F);
		assertEquals(0, bienLouable0.getNbPieces());
		assertEquals("", bienLouable0.getIdBat());
		assertEquals(0.0F, bienLouable0.getSurfaceHabitable(), 0.01F);
		assertEquals("8Sie)=n}\"", bienLouable0.getNumeroFiscal());
		assertEquals((-3625.659912109375), bienLouable0.getPourcentageEntretienPartiesCommunes(), 0.01);
		assertEquals("", bienLouable0.getCodePostal());
		assertEquals((-1.0F), bienLouable0.getProvisionPourCharges(), 0.01F);
	}

	@Test(timeout = 4000)
	public void test21() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Integer integer0 = new Integer(12);
		BienLouable bienLouable0 = new BienLouable((String) null, "X>zkI&oXdMs-C^$*D", "",
				"La taille du num\u00E9ro fiscal n'est pas valable !", "}<}.Ue[DLM", 12, 0.0F, "j<e4yr,*", localDate0,
				0.0F, 12, 12, 2133.6856719050515, "", integer0);
		String string0 = bienLouable0.getIdBien();
		assertEquals("La taille du num\u00E9ro fiscal n'est pas valable !", bienLouable0.getCodePostal());
		assertEquals(0.0F, bienLouable0.getSurfaceHabitable(), 0.01F);
		assertNull(string0);
		assertEquals(12.0, bienLouable0.getPourcentageEntretienPartiesCommunes(), 0.01);
		assertEquals("j<e4yr,*", bienLouable0.getTypeBien());
		assertEquals("}<}.Ue[DLM", bienLouable0.getVille());
		assertEquals(2133.6856719050515, bienLouable0.getPourcentageOrduresMenageres(), 0.01);
		assertEquals(12, bienLouable0.getNbPieces());
		assertEquals(0.0F, bienLouable0.getProvisionPourCharges(), 0.01F);
		assertEquals(12.0F, bienLouable0.getLoyer(), 0.01F);
		assertEquals("X>zkI&oXdMs-C^$*D", bienLouable0.getIdBat());
		assertEquals("", bienLouable0.getAdresse());
		assertEquals("", bienLouable0.getNumeroFiscal());
	}

	@Test(timeout = 4000)
	public void test22() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Integer integer0 = new Integer(0);
		BienLouable bienLouable0 = new BienLouable("", "", (String) null, "", (String) null, 1124.542F, (-1.0F),
				(String) null, localDate0, 0.0F, 0, (-3625.66F), 100.0, "8Sie)=n}\"", integer0);
		String string0 = bienLouable0.getIdBien();
		assertEquals("8Sie)=n}\"", bienLouable0.getNumeroFiscal());
		assertEquals("", bienLouable0.getCodePostal());
		assertEquals((-1.0F), bienLouable0.getProvisionPourCharges(), 0.01F);
		assertEquals(1124.542F, bienLouable0.getLoyer(), 0.01F);
		assertEquals(0.0F, bienLouable0.getSurfaceHabitable(), 0.01F);
		assertEquals(0, bienLouable0.getNbPieces());
		assertEquals("", string0);
		assertEquals(100.0, bienLouable0.getPourcentageOrduresMenageres(), 0.01);
		assertEquals((-3625.659912109375), bienLouable0.getPourcentageEntretienPartiesCommunes(), 0.01);
		assertEquals("", bienLouable0.getIdBat());
		assertNotNull(string0);
	}

	@Test(timeout = 4000)
	public void test23() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Integer integer0 = new Integer(41);
		BienLouable bienLouable0 = new BienLouable((String) null, (String) null, "WeZ", "", "jXpc`3%%iu>[", (-1.0F),
				22, "", localDate0, 41, 22, 1124.542F, 41, "'$zpkcJ;Qh[&t9mKt", integer0);
		String string0 = bienLouable0.getIdBat();
		assertEquals("", bienLouable0.getTypeBien());
		assertEquals(41.0F, bienLouable0.getSurfaceHabitable(), 0.01F);
		assertNull(string0);
		assertEquals((-1.0F), bienLouable0.getLoyer(), 0.01F);
		assertEquals(22.0F, bienLouable0.getProvisionPourCharges(), 0.01F);
		assertEquals("", bienLouable0.getCodePostal());
		assertEquals(1124.5419921875, bienLouable0.getPourcentageEntretienPartiesCommunes(), 0.01);
		assertEquals("'$zpkcJ;Qh[&t9mKt", bienLouable0.getNumeroFiscal());
		assertEquals("WeZ", bienLouable0.getAdresse());
		assertEquals(22, bienLouable0.getNbPieces());
		assertEquals(41.0, bienLouable0.getPourcentageOrduresMenageres(), 0.01);
		assertEquals("jXpc`3%%iu>[", bienLouable0.getVille());
	}

	@Test(timeout = 4000)
	public void test24() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Integer integer0 = new Integer(0);
		BienLouable bienLouable0 = new BienLouable("", "", (String) null, "", (String) null, 1124.542F, (-1.0F),
				(String) null, localDate0, 0.0F, 0, (-3625.66F), 100.0, "8Sie)=n}\"", integer0);
		String string0 = bienLouable0.getIdBat();
		assertEquals("", string0);
		assertEquals(100.0, bienLouable0.getPourcentageOrduresMenageres(), 0.01);
		assertEquals("8Sie)=n}\"", bienLouable0.getNumeroFiscal());
		assertEquals((-3625.659912109375), bienLouable0.getPourcentageEntretienPartiesCommunes(), 0.01);
		assertEquals(0, bienLouable0.getNbPieces());
		assertEquals((-1.0F), bienLouable0.getProvisionPourCharges(), 0.01F);
		assertEquals("", bienLouable0.getIdBien());
		assertEquals("", bienLouable0.getCodePostal());
		assertNotNull(string0);
		assertEquals(1124.542F, bienLouable0.getLoyer(), 0.01F);
		assertEquals(0.0F, bienLouable0.getSurfaceHabitable(), 0.01F);
	}

	@Test(timeout = 4000)
	public void test25() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Integer integer0 = new Integer(0);
		BienLouable bienLouable0 = new BienLouable("BienLouable [idBien=", "BienLouable [idBien=",
				", surfaceHabitable=", ", surfaceHabitable=", "", (-1.0F), (-1.0F), "", localDate0, (-1.0F), 0, (-1.0F),
				(-3279.971137), ", surfaceHabitable=", integer0);
		bienLouable0.getDerniereAnneeModifLoyer();
		assertEquals("", bienLouable0.getVille());
		assertEquals("", bienLouable0.getTypeBien());
		assertEquals((-3279.971137), bienLouable0.getPourcentageOrduresMenageres(), 0.01);
		assertEquals((-1.0F), bienLouable0.getLoyer(), 0.01F);
		assertEquals((-1.0), bienLouable0.getPourcentageEntretienPartiesCommunes(), 0.01);
		assertEquals((-1.0F), bienLouable0.getSurfaceHabitable(), 0.01F);
		assertEquals(", surfaceHabitable=", bienLouable0.getAdresse());
		assertEquals(", surfaceHabitable=", bienLouable0.getNumeroFiscal());
		assertEquals(0, bienLouable0.getNbPieces());
		assertEquals(", surfaceHabitable=", bienLouable0.getCodePostal());
		assertEquals("BienLouable [idBien=", bienLouable0.getIdBien());
		assertEquals((-1.0F), bienLouable0.getProvisionPourCharges(), 0.01F);
		assertEquals("BienLouable [idBien=", bienLouable0.getIdBat());
	}

	@Test(timeout = 4000)
	public void test26() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Integer integer0 = new Integer(12);
		BienLouable bienLouable0 = new BienLouable("", "", "", "j<e4yr,*", "j<e4yr,*", (-1839.0756F), (-1839.0756F),
				", typeBien=", localDate0, (-1839.0756F), 12, (-1839.0756F), (-1839.0756F), "j<e4yr,*", integer0);
		bienLouable0.getDerniereAnneeModifLoyer();
		assertEquals((-1839.0756F), bienLouable0.getProvisionPourCharges(), 0.01F);
		assertEquals((-1839.0755615234375), bienLouable0.getPourcentageEntretienPartiesCommunes(), 0.01);
		assertEquals(", typeBien=", bienLouable0.getTypeBien());
		assertEquals("j<e4yr,*", bienLouable0.getVille());
		assertEquals(12, bienLouable0.getNbPieces());
		assertEquals((-1839.0756F), bienLouable0.getLoyer(), 0.01F);
		assertEquals((-1839.0756F), bienLouable0.getSurfaceHabitable(), 0.01F);
		assertEquals("", bienLouable0.getAdresse());
		assertEquals("j<e4yr,*", bienLouable0.getCodePostal());
		assertEquals("", bienLouable0.getIdBien());
		assertEquals("", bienLouable0.getIdBat());
		assertEquals((-1839.0755615234375), bienLouable0.getPourcentageOrduresMenageres(), 0.01);
		assertEquals("j<e4yr,*", bienLouable0.getNumeroFiscal());
	}

	@Test(timeout = 4000)
	public void test27() throws Throwable {
		BienLouable bienLouable0 = new BienLouable("", "", "1@fRN7:}I$k", (String) null, "", (-1.0F), 1.0F,
				"1@fRN7:}I$k", (LocalDate) null, 0.0F, 2589, (-809.798856304185), (-687.958), "^ b0mZ!Uh/#f/",
				(Integer) null);
		bienLouable0.getDerniereAnneeModifLoyer();
		assertEquals("", bienLouable0.getIdBat());
		assertEquals((-1.0F), bienLouable0.getLoyer(), 0.01F);
		assertEquals("^ b0mZ!Uh/#f/", bienLouable0.getNumeroFiscal());
		assertEquals("", bienLouable0.getIdBien());
		assertEquals("", bienLouable0.getVille());
		assertEquals(0.0F, bienLouable0.getSurfaceHabitable(), 0.01F);
		assertEquals(1.0F, bienLouable0.getProvisionPourCharges(), 0.01F);
		assertEquals((-687.958), bienLouable0.getPourcentageOrduresMenageres(), 0.01);
		assertEquals((-809.798856304185), bienLouable0.getPourcentageEntretienPartiesCommunes(), 0.01);
		assertEquals(2589, bienLouable0.getNbPieces());
	}

	@Test(timeout = 4000)
	public void test28() throws Throwable {
		Integer integer0 = new Integer((-1208));
		BienLouable bienLouable0 = new BienLouable("", "", "", "", (String) null, 2314.688F, 2314.688F, (String) null,
				(LocalDate) null, 2314.688F, (-1208), 100.0, 0.0, "", integer0);
		bienLouable0.getDateConstruction();
		assertEquals(2314.688F, bienLouable0.getLoyer(), 0.01F);
		assertEquals(100.0, bienLouable0.getPourcentageEntretienPartiesCommunes(), 0.01);
		assertEquals((-1208), bienLouable0.getNbPieces());
		assertEquals(2314.688F, bienLouable0.getSurfaceHabitable(), 0.01F);
		assertEquals(2314.688F, bienLouable0.getProvisionPourCharges(), 0.01F);
		assertEquals(0.0, bienLouable0.getPourcentageOrduresMenageres(), 0.01);
	}

	@Test(timeout = 4000)
	public void test29() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Integer integer0 = new Integer(0);
		BienLouable bienLouable0 = new BienLouable((String) null, ",69m", (String) null, (String) null, (String) null,
				1124.542F, 1124.542F, (String) null, localDate0, 0.0F, 0, (-3625.66F), (-4537.0), (String) null,
				integer0);
		String string0 = bienLouable0.getCodePostal();
		assertNull(string0);
		assertEquals(0, bienLouable0.getNbPieces());
		assertEquals(1124.542F, bienLouable0.getProvisionPourCharges(), 0.01F);
		assertEquals((-3625.659912109375), bienLouable0.getPourcentageEntretienPartiesCommunes(), 0.01);
		assertEquals((-4537.0), bienLouable0.getPourcentageOrduresMenageres(), 0.01);
		assertEquals(0.0F, bienLouable0.getSurfaceHabitable(), 0.01F);
		assertEquals(1124.542F, bienLouable0.getLoyer(), 0.01F);
	}

	@Test(timeout = 4000)
	public void test30() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Integer integer0 = new Integer((-2146474966));
		BienLouable bienLouable0 = new BienLouable(", num\u00E9roFiscal=", ", num\u00E9roFiscal=", "", "", "5e+%'C};",
				(-2344), 2496.6199F, ", num\u00E9roFiscal=", localDate0, 2496.6199F, (-2146474966), (-2146474966),
				650.159934027, ", surfaceHabitable=", integer0);
		String string0 = bienLouable0.getCodePostal();
		assertEquals(", num\u00E9roFiscal=", bienLouable0.getIdBat());
		assertEquals(", num\u00E9roFiscal=", bienLouable0.getIdBien());
		assertEquals("", string0);
		assertEquals("5e+%'C};", bienLouable0.getVille());
		assertEquals("", bienLouable0.getAdresse());
		assertEquals(2496.6199F, bienLouable0.getProvisionPourCharges(), 0.01F);
		assertEquals(650.159934027, bienLouable0.getPourcentageOrduresMenageres(), 0.01);
		assertEquals((-2146474966), bienLouable0.getNbPieces());
		assertEquals(", num\u00E9roFiscal=", bienLouable0.getTypeBien());
		assertEquals((-2.146474966E9), bienLouable0.getPourcentageEntretienPartiesCommunes(), 0.01);
		assertEquals((-2344.0F), bienLouable0.getLoyer(), 0.01F);
		assertEquals(2496.6199F, bienLouable0.getSurfaceHabitable(), 0.01F);
		assertEquals(", surfaceHabitable=", bienLouable0.getNumeroFiscal());
	}

	@Test(timeout = 4000)
	public void test31() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Integer integer0 = new Integer(0);
		BienLouable bienLouable0 = new BienLouable("", "", (String) null, "", (String) null, 1124.542F, (-1.0F),
				(String) null, localDate0, 0.0F, 0, (-3625.66F), 100.0, "8Sie)=n}\"", integer0);
		String string0 = bienLouable0.getAdresse();
		assertEquals("8Sie)=n}\"", bienLouable0.getNumeroFiscal());
		assertEquals(0.0F, bienLouable0.getSurfaceHabitable(), 0.01F);
		assertEquals((-3625.659912109375), bienLouable0.getPourcentageEntretienPartiesCommunes(), 0.01);
		assertEquals("", bienLouable0.getCodePostal());
		assertEquals(1124.542F, bienLouable0.getLoyer(), 0.01F);
		assertEquals((-1.0F), bienLouable0.getProvisionPourCharges(), 0.01F);
		assertEquals("", bienLouable0.getIdBien());
		assertEquals(100.0, bienLouable0.getPourcentageOrduresMenageres(), 0.01);
		assertNull(string0);
		assertEquals(0, bienLouable0.getNbPieces());
		assertEquals("", bienLouable0.getIdBat());
	}

	@Test(timeout = 4000)
	public void test32() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Integer integer0 = new Integer(12);
		BienLouable bienLouable0 = new BienLouable("", "", "", "j<e4yr,*", "j<e4yr,*", (-1839.0756F), (-1839.0756F),
				", typeBien=", localDate0, (-1839.0756F), 12, (-1839.0756F), (-1839.0756F), "j<e4yr,*", integer0);
		String string0 = bienLouable0.getAdresse();
		assertEquals("j<e4yr,*", bienLouable0.getNumeroFiscal());
		assertEquals(12, bienLouable0.getNbPieces());
		assertEquals((-1839.0755615234375), bienLouable0.getPourcentageEntretienPartiesCommunes(), 0.01);
		assertEquals(", typeBien=", bienLouable0.getTypeBien());
		assertEquals("j<e4yr,*", bienLouable0.getVille());
		assertEquals((-1839.0756F), bienLouable0.getLoyer(), 0.01F);
		assertEquals((-1839.0756F), bienLouable0.getSurfaceHabitable(), 0.01F);
		assertEquals("", string0);
		assertEquals("j<e4yr,*", bienLouable0.getCodePostal());
		assertEquals("", bienLouable0.getIdBien());
		assertEquals((-1839.0756F), bienLouable0.getProvisionPourCharges(), 0.01F);
		assertEquals("", bienLouable0.getIdBat());
		assertEquals((-1839.0755615234375), bienLouable0.getPourcentageOrduresMenageres(), 0.01);
	}

	@Test(timeout = 4000)
	public void test33() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Integer integer0 = new Integer(1174);
		BienLouable bienLouable0 = new BienLouable(", pourcentageEntretienPartiesCommunes=",
				", pourcentageEntretienPartiesCommunes=", ", pourcentageEntretienPartiesCommunes=",
				", pourcentageEntretienPartiesCommunes=", ", pourcentageEntretienPartiesCommunes=", (-1838.1376F),
				(-1838.1376F), ", pourcentageEntretienPartiesCommunes=", localDate0, (-1838.1376F), 1174, (-1838.1376F),
				(-1838.1376F), ", pourcentageEntretienPartiesCommunes=", integer0);
		// Undeclared exception!
		try {
			bienLouable0.setNumeroFiscal((String) null);
			fail("Expecting exception: NullPointerException");

		} catch (NullPointerException e) {
			//
			// no message in exception (getMessage() returned null)
			//
			verifyException("modele.BienLouable", e);
		}
	}

	@Test(timeout = 4000)
	public void test34() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Integer integer0 = new Integer((-2146923935));
		BienLouable bienLouable0 = new BienLouable("o(x", "o(x", "o(x", "o(x", "o(x", (-2146923935), (-2146923935),
				"o(x", localDate0, (-2146923935), (-2146923935), (-2146923935), (-2146923935), "o(x", integer0);
		BienLouable bienLouable1 = new BienLouable("o(x", "", "", "o(x", ", adresse=", (-2146923935), 2016.6F,
				"0(_DUnIQ;", localDate0, (-2146923935), (-2146923935), 2016.6F, (-2146923935), "", integer0);
		boolean boolean0 = bienLouable0.equals(bienLouable1);
		assertEquals("", bienLouable1.getNumeroFiscal());
		assertEquals((-2.1469239E9F), bienLouable1.getSurfaceHabitable(), 0.01F);
		assertEquals(2016.6F, bienLouable1.getProvisionPourCharges(), 0.01F);
		assertEquals(2016.5999755859375, bienLouable1.getPourcentageEntretienPartiesCommunes(), 0.01);
		assertEquals("0(_DUnIQ;", bienLouable1.getTypeBien());
		assertEquals("", bienLouable1.getAdresse());
		assertEquals((-2.146923935E9), bienLouable1.getPourcentageOrduresMenageres(), 0.01);
		assertEquals((-2.1469239E9F), bienLouable1.getLoyer(), 0.01F);
		assertEquals("", bienLouable1.getIdBat());
		assertEquals((-2146923935), bienLouable1.getNbPieces());
		assertEquals("o(x", bienLouable1.getCodePostal());
		assertEquals(", adresse=", bienLouable1.getVille());
		assertTrue(boolean0);
	}

	@Test(timeout = 4000)
	public void test35() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Integer integer0 = new Integer(2126221398);
		BienLouable bienLouable0 = new BienLouable("N*2pq:l<N8*[Q9cw*", "N*2pq:l<N8*[Q9cw*", "N*2pq:l<N8*[Q9cw*",
				"N*2pq:l<N8*[Q9cw*", "N*2pq:l<N8*[Q9cw*", 2126221398, 2126221398, "N*2pq:l<N8*[Q9cw*", localDate0,
				2126221398, 2126221398, 2126221398, 2126221398, "N*2pq:l<N8*[Q9cw*", integer0);
		boolean boolean0 = bienLouable0.equals((Object) null);
		assertEquals(2.12622144E9F, bienLouable0.getSurfaceHabitable(), 0.01F);
		assertEquals(2.12622144E9F, bienLouable0.getProvisionPourCharges(), 0.01F);
		assertEquals(2.12622144E9F, bienLouable0.getLoyer(), 0.01F);
		assertFalse(boolean0);
		assertEquals(2.126221398E9, bienLouable0.getPourcentageOrduresMenageres(), 0.01);
		assertEquals(2126221398, bienLouable0.getNbPieces());
		assertEquals(2.126221398E9, bienLouable0.getPourcentageEntretienPartiesCommunes(), 0.01);
	}

	@Test(timeout = 4000)
	public void test36() throws Throwable {
		Integer integer0 = new Integer((-1208));
		BienLouable bienLouable0 = new BienLouable("", "", "", "", (String) null, 2314.688F, 2314.688F, (String) null,
				(LocalDate) null, 2314.688F, (-1208), 100.0, 0.0, "", integer0);
		boolean boolean0 = bienLouable0.equals(bienLouable0);
		assertEquals(0.0, bienLouable0.getPourcentageOrduresMenageres(), 0.01);
		assertEquals(2314.688F, bienLouable0.getLoyer(), 0.01F);
		assertTrue(boolean0);
		assertEquals(100.0, bienLouable0.getPourcentageEntretienPartiesCommunes(), 0.01);
		assertEquals(2314.688F, bienLouable0.getProvisionPourCharges(), 0.01F);
		assertEquals(2314.688F, bienLouable0.getSurfaceHabitable(), 0.01F);
		assertEquals((-1208), bienLouable0.getNbPieces());
	}

	@Test(timeout = 4000)
	public void test37() throws Throwable {
		Integer integer0 = new Integer((-1897));
		BienLouable bienLouable0 = new BienLouable("tB>rX;J-xFN[hD4", ", codePostal=", ", ville=", ", codePostal=", "",
				1988.4F, (-159.08606F), (String) null, (LocalDate) null, (-2570.3F), (-1), 88.293011077, (-159.08606F),
				"tB>rX;J-xFN[hD4", integer0);
		boolean boolean0 = bienLouable0.equals("tB>rX;J-xFN[hD4");
		assertEquals("tB>rX;J-xFN[hD4", bienLouable0.getIdBien());
		assertEquals((-1), bienLouable0.getNbPieces());
		assertEquals("", bienLouable0.getVille());
		assertEquals(", codePostal=", bienLouable0.getIdBat());
		assertEquals(1988.4F, bienLouable0.getLoyer(), 0.01F);
		assertEquals("tB>rX;J-xFN[hD4", bienLouable0.getNumeroFiscal());
		assertEquals(", codePostal=", bienLouable0.getCodePostal());
		assertEquals((-159.08606F), bienLouable0.getProvisionPourCharges(), 0.01F);
		assertFalse(boolean0);
		assertEquals((-159.0860595703125), bienLouable0.getPourcentageOrduresMenageres(), 0.01);
		assertEquals(", ville=", bienLouable0.getAdresse());
		assertEquals(88.293011077, bienLouable0.getPourcentageEntretienPartiesCommunes(), 0.01);
		assertEquals((-2570.3F), bienLouable0.getSurfaceHabitable(), 0.01F);
	}

	@Test(timeout = 4000)
	public void test38() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Integer integer0 = Integer.getInteger("(A", (-2146923915));
		BienLouable bienLouable0 = new BienLouable("(A", "(A", "(A", "(A", "(A", (-2146923915), (-2146923915), "(A",
				localDate0, (-2146923915), (-2146923915), (-2146923915), (-2146923915), "(A", integer0);
		try {
			bienLouable0.setNumeroFiscal("(A");
			fail("Expecting exception: IllegalArgumentException");

		} catch (IllegalArgumentException e) {
			//
			// La taille du num\u00E9ro fiscal n'est pas valable !
			//
			verifyException("modele.BienLouable", e);
		}
	}

	@Test(timeout = 4000)
	public void test39() throws Throwable {
		Integer integer0 = new Integer((-1208));
		BienLouable bienLouable0 = new BienLouable("", "", "", "", (String) null, 2314.688F, 2314.688F, (String) null,
				(LocalDate) null, 2314.688F, (-1208), 100.0, 0.0, "", integer0);
		bienLouable0.setNumeroFiscal("er8K2<ZSX|!S");
		assertEquals((-1208), bienLouable0.getNbPieces());
		assertEquals(0.0, bienLouable0.getPourcentageOrduresMenageres(), 0.01);
		assertEquals(100.0, bienLouable0.getPourcentageEntretienPartiesCommunes(), 0.01);
		assertEquals(2314.688F, bienLouable0.getProvisionPourCharges(), 0.01F);
		assertEquals(2314.688F, bienLouable0.getLoyer(), 0.01F);
		assertEquals(2314.688F, bienLouable0.getSurfaceHabitable(), 0.01F);
	}

	@Test(timeout = 4000)
	public void test40() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Integer integer0 = new Integer((-2789));
		BienLouable bienLouable0 = new BienLouable(", pourcentageEntretienPartiesCommunes=",
				", pourcentageEntretienPartiesCommunes=", ", pourcentageEntretienPartiesCommunes=",
				", pourcentageEntretienPartiesCommunes=", ", pourcentageEntretienPartiesCommunes=", (-1839.0756F),
				(-1839.0756F), ", pourcentageEntretienPartiesCommunes=", localDate0, (-1839.0756F), (-2789),
				(-1839.0756F), (-1839.0756F), ", pourcentageEntretienPartiesCommunes=", integer0);
		try {
			bienLouable0.setPourcentageOrduresMenageres((-2789));
			fail("Expecting exception: IllegalArgumentException");

		} catch (IllegalArgumentException e) {
			//
			// Le pourcentage d'ordures m\u00E9nag\u00E8res n'est pas bon !
			//
			verifyException("modele.BienLouable", e);
		}
	}

	@Test(timeout = 4000)
	public void test41() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Integer integer0 = new Integer(1155);
		BienLouable bienLouable0 = new BienLouable(", pourcentageEntretienPartiesCommunes=",
				", pourcentageEntretienPartiesCommunes=", ", pourcentageEntretienPartiesCommunes=",
				", pourcentageEntretienPartiesCommunes=", ", pourcentageEntretienPartiesCommunes=", (-1839.0756F),
				(-1839.0756F), ", pourcentageEntretienPartiesCommunes=", localDate0, (-1839.0756F), 1155, (-1839.0756F),
				(-1839.0756F), ", pourcentageEntretienPartiesCommunes=", integer0);
		try {
			bienLouable0.setPourcentageOrduresMenageres(1155);
			fail("Expecting exception: IllegalArgumentException");

		} catch (IllegalArgumentException e) {
			//
			// Le pourcentage d'ordures m\u00E9nag\u00E8res n'est pas bon !
			//
			verifyException("modele.BienLouable", e);
		}
	}

	@Test(timeout = 4000)
	public void test42() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		BienLouable bienLouable0 = new BienLouable("o(x", "o(x", "o(x", "o(x", "o(x", (-2146923967), (-2146923967),
				"o(x", localDate0, (-2146923967), (-2146923967), (-2146923967), (-2146923967), "o(x", (Integer) null);
		try {
			bienLouable0.setPourcentageEntretienPartiesCommunes((-2146923967));
			fail("Expecting exception: IllegalArgumentException");

		} catch (IllegalArgumentException e) {
			//
			// Le pourcentage d'entretien parties communes n'est pas bon !
			//
			verifyException("modele.BienLouable", e);
		}
	}

	@Test(timeout = 4000)
	public void test43() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Integer integer0 = new Integer(2126221433);
		BienLouable bienLouable0 = new BienLouable("w :oFx", "w :oFx", "w :oFx", "w :oFx", "w :oFx", 2126221433,
				2126221433, "w :oFx", localDate0, 2126221433, 2126221433, 2126221433, 2126221433, "w :oFx", integer0);
		bienLouable0.setPourcentageEntretienPartiesCommunes(100.0);
		assertEquals(100.0, bienLouable0.getPourcentageEntretienPartiesCommunes(), 0.01);
	}

	@Test(timeout = 4000)
	public void test44() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Integer integer0 = new Integer(2126221466);
		BienLouable bienLouable0 = new BienLouable("", "", "", "", "", 2126221466, 2126221466, "", localDate0,
				2126221466, 2126221466, 2126221466, 2126221466, "", integer0);
		try {
			bienLouable0.setPourcentageEntretienPartiesCommunes(2126221466);
			fail("Expecting exception: IllegalArgumentException");

		} catch (IllegalArgumentException e) {
			//
			// Le pourcentage d'entretien parties communes n'est pas bon !
			//
			verifyException("modele.BienLouable", e);
		}
	}

	@Test(timeout = 4000)
	public void test45() throws Throwable {
		Integer integer0 = new Integer((-1208));
		BienLouable bienLouable0 = new BienLouable("", "", "", "", (String) null, 2314.688F, 2314.688F, (String) null,
				(LocalDate) null, 2314.688F, (-1208), 100.0, 0.0, "", integer0);
		bienLouable0.setIdBat("");
		assertEquals(2314.688F, bienLouable0.getLoyer(), 0.01F);
		assertEquals(0.0, bienLouable0.getPourcentageOrduresMenageres(), 0.01);
		assertEquals(2314.688F, bienLouable0.getSurfaceHabitable(), 0.01F);
		assertEquals(2314.688F, bienLouable0.getProvisionPourCharges(), 0.01F);
		assertEquals((-1208), bienLouable0.getNbPieces());
		assertEquals(100.0, bienLouable0.getPourcentageEntretienPartiesCommunes(), 0.01);
	}

	@Test(timeout = 4000)
	public void test46() throws Throwable {
		Integer integer0 = new Integer((-1208));
		BienLouable bienLouable0 = new BienLouable("", "", "", "", (String) null, 2314.688F, 2314.688F, (String) null,
				(LocalDate) null, 2314.688F, (-1208), 100.0, 0.0, "", integer0);
		String string0 = bienLouable0.toString();
		assertEquals(
				"BienLouable [idBien=, idBat=, adresse=, codePostal=, ville=null, loyer=2314.688, provisionPourCharges=2314.688, typeBien=null, dateConstruction=null, surfaceHabitable=2314.688, nbPi\u00E8ces=-1208, pourcentageEntretienPartiesCommunes=100.0, pourcentageOrduresM\u00E9nag\u00E8res=0.0, num\u00E9roFiscal=]",
				string0);
	}

	@Test(timeout = 4000)
	public void test47() throws Throwable {
		Integer integer0 = new Integer((-1208));
		BienLouable bienLouable0 = new BienLouable("", "", "", "", (String) null, 2314.688F, 2314.688F, (String) null,
				(LocalDate) null, 2314.688F, (-1208), 100.0, 0.0, "", integer0);
		bienLouable0.hashCode();
		assertEquals((-1208), bienLouable0.getNbPieces());
		assertEquals(0.0, bienLouable0.getPourcentageOrduresMenageres(), 0.01);
		assertEquals(2314.688F, bienLouable0.getLoyer(), 0.01F);
		assertEquals(100.0, bienLouable0.getPourcentageEntretienPartiesCommunes(), 0.01);
		assertEquals(2314.688F, bienLouable0.getProvisionPourCharges(), 0.01F);
		assertEquals(2314.688F, bienLouable0.getSurfaceHabitable(), 0.01F);
	}

	@Test(timeout = 4000)
	public void test48() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Integer integer0 = new Integer((-31));
		BienLouable bienLouable0 = new BienLouable("B", "B", "B", "B", "B", (-1839.0756F), (-1839.0756F), ", ypeBien=",
				localDate0, (-1839.0756F), (-31), (-1839.0756F), (-1839.0756F), "B", integer0);
		bienLouable0.getDateConstruction();
		assertEquals(", ypeBien=", bienLouable0.getTypeBien());
		assertEquals("B", bienLouable0.getAdresse());
		assertEquals("B", bienLouable0.getCodePostal());
		assertEquals((-1839.0756F), bienLouable0.getSurfaceHabitable(), 0.01F);
		assertEquals((-1839.0755615234375), bienLouable0.getPourcentageOrduresMenageres(), 0.01);
		assertEquals((-31), bienLouable0.getNbPieces());
		assertEquals("B", bienLouable0.getIdBat());
		assertEquals((-1839.0755615234375), bienLouable0.getPourcentageEntretienPartiesCommunes(), 0.01);
		assertEquals("B", bienLouable0.getVille());
		assertEquals("B", bienLouable0.getNumeroFiscal());
		assertEquals((-1839.0756F), bienLouable0.getProvisionPourCharges(), 0.01F);
		assertEquals((-1839.0756F), bienLouable0.getLoyer(), 0.01F);
		assertEquals("B", bienLouable0.getIdBien());
	}

	@Test(timeout = 4000)
	public void test49() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Integer integer0 = new Integer(2126221433);
		BienLouable bienLouable0 = new BienLouable("o(x", "o(x", "o(x", "o(x", "o(x", 2126221433, 2126221433, "o(x",
				localDate0, 2126221433, 2126221433, 2126221433, 2126221433, "o(x", integer0);
		bienLouable0.setDateConstruction(localDate0);
		assertEquals(2126221433, bienLouable0.getNbPieces());
		assertEquals(2.126221433E9, bienLouable0.getPourcentageEntretienPartiesCommunes(), 0.01);
		assertEquals(2.126221433E9, bienLouable0.getPourcentageOrduresMenageres(), 0.01);
		assertEquals(2.12622144E9F, bienLouable0.getLoyer(), 0.01F);
		assertEquals(2.12622144E9F, bienLouable0.getSurfaceHabitable(), 0.01F);
		assertEquals(2.12622144E9F, bienLouable0.getProvisionPourCharges(), 0.01F);
	}

	@Test(timeout = 4000)
	public void test50() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Integer integer0 = new Integer(1178);
		BienLouable bienLouable0 = new BienLouable(", pourcentageEntretienPartiesCommunes=",
				", pourcentageEntretienPartiesCommunes=", ", pourcentageEntretienPartiesCommunes=",
				", pourcentageEntretienPartiesCommunes=", ", pourcentageEntretienPartiesCommunes=", (-1838.3551F),
				(-1838.3551F), ", pourcentageEntretienPartiesCommunes=", localDate0, (-1838.3551F), 1178, (-1838.3551F),
				(-1838.3551F), ", pourcentageEntretienPartiesCommunes=", integer0);
		bienLouable0.setCodePostal(", pourcentageEntretienPartiesCommunes=");
		assertEquals(1178, bienLouable0.getNbPieces());
		assertEquals((-1838.3551025390625), bienLouable0.getPourcentageEntretienPartiesCommunes(), 0.01);
		assertEquals((-1838.3551F), bienLouable0.getSurfaceHabitable(), 0.01F);
		assertEquals((-1838.3551F), bienLouable0.getProvisionPourCharges(), 0.01F);
		assertEquals((-1838.3551F), bienLouable0.getLoyer(), 0.01F);
		assertEquals((-1838.3551025390625), bienLouable0.getPourcentageOrduresMenageres(), 0.01);
	}

	@Test(timeout = 4000)
	public void test51() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Integer integer0 = new Integer(0);
		BienLouable bienLouable0 = new BienLouable("BienLouable [idBien=", "BienLouable [idBien=",
				", surfaceHabitable=", ", surfaceHabitable=", "BienLouable [idBien=", (-1.0F), (-1.0F),
				"BienLouable [idBien=", localDate0, (-1.0F), 0, (-1.0F), (-3279.971137), ", surfaceHabitable=",
				integer0);
		float float0 = bienLouable0.getSurfaceHabitable();
		assertEquals((-1.0), bienLouable0.getPourcentageEntretienPartiesCommunes(), 0.01);
		assertEquals(", surfaceHabitable=", bienLouable0.getCodePostal());
		assertEquals("BienLouable [idBien=", bienLouable0.getIdBat());
		assertEquals(", surfaceHabitable=", bienLouable0.getAdresse());
		assertEquals("BienLouable [idBien=", bienLouable0.getTypeBien());
		assertEquals("BienLouable [idBien=", bienLouable0.getIdBien());
		assertEquals((-1.0F), float0, 0.01F);
		assertEquals("BienLouable [idBien=", bienLouable0.getVille());
		assertEquals((-1.0F), bienLouable0.getLoyer(), 0.01F);
		assertEquals(0, bienLouable0.getNbPieces());
		assertEquals((-1.0F), bienLouable0.getProvisionPourCharges(), 0.01F);
		assertEquals(", surfaceHabitable=", bienLouable0.getNumeroFiscal());
		assertEquals((-3279.971137), bienLouable0.getPourcentageOrduresMenageres(), 0.01);
	}

	@Test(timeout = 4000)
	public void test52() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Integer integer0 = new Integer(2126221433);
		BienLouable bienLouable0 = new BienLouable("a+x", "a+x", "a+x", "a+x", "a+x", 2126221433, 2126221433, "a+x",
				localDate0, 2126221433, 2126221433, 2126221433, 2126221433, "a+x", integer0);
		bienLouable0.setSurfaceHabitable(2126221433);
		assertEquals(2.12622144E9F, bienLouable0.getSurfaceHabitable(), 0.01F);
		assertEquals(2.126221433E9, bienLouable0.getPourcentageEntretienPartiesCommunes(), 0.01);
		assertEquals(2.126221433E9, bienLouable0.getPourcentageOrduresMenageres(), 0.01);
		assertEquals(2.12622144E9F, bienLouable0.getProvisionPourCharges(), 0.01F);
		assertEquals(2126221433, bienLouable0.getNbPieces());
		assertEquals(2.12622144E9F, bienLouable0.getLoyer(), 0.01F);
	}

	@Test(timeout = 4000)
	public void test53() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Integer integer0 = new Integer((-32));
		BienLouable bienLouable0 = new BienLouable("B", "B", "B", "B", "B", (-839.2734F), (-839.2734F), ", ypeBen7",
				localDate0, (-839.2734F), (-32), (-839.2734F), (-839.2734F), "B", integer0);
		double double0 = bienLouable0.getPourcentageOrduresMenageres();
		assertEquals((-839.2734F), bienLouable0.getSurfaceHabitable(), 0.01F);
		assertEquals("B", bienLouable0.getVille());
		assertEquals("B", bienLouable0.getIdBien());
		assertEquals("B", bienLouable0.getCodePostal());
		assertEquals("B", bienLouable0.getAdresse());
		assertEquals((-839.2733764648438), double0, 0.01);
		assertEquals("B", bienLouable0.getNumeroFiscal());
		assertEquals((-839.2734F), bienLouable0.getProvisionPourCharges(), 0.01F);
		assertEquals((-839.2734F), bienLouable0.getLoyer(), 0.01F);
		assertEquals(", ypeBen7", bienLouable0.getTypeBien());
		assertEquals((-839.2733764648438), bienLouable0.getPourcentageEntretienPartiesCommunes(), 0.01);
		assertEquals((-32), bienLouable0.getNbPieces());
		assertEquals("B", bienLouable0.getIdBat());
	}

	@Test(timeout = 4000)
	public void test54() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Integer integer0 = new Integer(2126221433);
		BienLouable bienLouable0 = new BienLouable("a+x", "a+x", "a+x", "a+x", "a+x", 2126221433, 2126221433, "a+x",
				localDate0, 2126221433, 2126221433, 2126221433, 2126221433, "a+x", integer0);
		bienLouable0.setVille("a+x");
		assertEquals(2126221433, bienLouable0.getNbPieces());
		assertEquals(2.126221433E9, bienLouable0.getPourcentageEntretienPartiesCommunes(), 0.01);
		assertEquals(2.12622144E9F, bienLouable0.getSurfaceHabitable(), 0.01F);
		assertEquals(2.126221433E9, bienLouable0.getPourcentageOrduresMenageres(), 0.01);
		assertEquals(2.12622144E9F, bienLouable0.getLoyer(), 0.01F);
		assertEquals(2.12622144E9F, bienLouable0.getProvisionPourCharges(), 0.01F);
	}

	@Test(timeout = 4000)
	public void test55() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		BienLouable bienLouable0 = new BienLouable(", idBat=", ", idBat=", ", idBat=", ", idBat=", ", idBat=",
				(-1848.5719F), 1185, ", idBat=", localDate0, (-1848.5719F), 1185, 1185, 1185, ", idBat=",
				(Integer) null);
		bienLouable0.getIdBat();
		assertEquals(1185.0, bienLouable0.getPourcentageOrduresMenageres(), 0.01);
		assertEquals(1185, bienLouable0.getNbPieces());
		assertEquals((-1848.5719F), bienLouable0.getSurfaceHabitable(), 0.01F);
		assertEquals(1185.0, bienLouable0.getPourcentageEntretienPartiesCommunes(), 0.01);
		assertEquals((-1848.5719F), bienLouable0.getLoyer(), 0.01F);
		assertEquals(1185.0F, bienLouable0.getProvisionPourCharges(), 0.01F);
	}

	@Test(timeout = 4000)
	public void test56() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Integer integer0 = new Integer(1180);
		BienLouable bienLouable0 = new BienLouable(", idBat=", ", idBat=", ", idBat=", ", idBat=", ", idBat=",
				(-1848.5719F), (-1848.5719F), ", idBat=", localDate0, (-1848.5719F), 1180, (-1848.5719F), (-1848.5719F),
				", idBat=", integer0);
		bienLouable0.setNbPieces(1180);
		assertEquals(1180, bienLouable0.getNbPieces());
		assertEquals((-1848.5718994140625), bienLouable0.getPourcentageEntretienPartiesCommunes(), 0.01);
		assertEquals((-1848.5719F), bienLouable0.getSurfaceHabitable(), 0.01F);
		assertEquals((-1848.5718994140625), bienLouable0.getPourcentageOrduresMenageres(), 0.01);
		assertEquals((-1848.5719F), bienLouable0.getProvisionPourCharges(), 0.01F);
		assertEquals((-1848.5719F), bienLouable0.getLoyer(), 0.01F);
	}

	@Test(timeout = 4000)
	public void test57() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Integer integer0 = new Integer(0);
		BienLouable bienLouable0 = new BienLouable("BienLouable [idBien=", "BienLouable [idBien=",
				", surfaceHabitable=", ", surfaceHabitable=", "BienLouable [idBien=", (-1.0F), (-1.0F),
				"BienLouable [idBien=", localDate0, (-1.0F), 0, (-1.0F), (-3279.971137), ", surfaceHabitable=",
				integer0);
		String string0 = bienLouable0.getCodePostal();
		assertEquals((-1.0), bienLouable0.getPourcentageEntretienPartiesCommunes(), 0.01);
		assertEquals(", surfaceHabitable=", bienLouable0.getAdresse());
		assertEquals("BienLouable [idBien=", bienLouable0.getIdBat());
		assertEquals((-1.0F), bienLouable0.getSurfaceHabitable(), 0.01F);
		assertEquals((-3279.971137), bienLouable0.getPourcentageOrduresMenageres(), 0.01);
		assertEquals("BienLouable [idBien=", bienLouable0.getVille());
		assertEquals((-1.0F), bienLouable0.getProvisionPourCharges(), 0.01F);
		assertEquals((-1.0F), bienLouable0.getLoyer(), 0.01F);
		assertEquals(0, bienLouable0.getNbPieces());
		assertEquals(", surfaceHabitable=", bienLouable0.getNumeroFiscal());
		assertEquals("BienLouable [idBien=", bienLouable0.getTypeBien());
		assertEquals(", surfaceHabitable=", string0);
		assertEquals("BienLouable [idBien=", bienLouable0.getIdBien());
	}

	@Test(timeout = 4000)
	public void test58() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Integer integer0 = new Integer(0);
		BienLouable bienLouable0 = new BienLouable("BienLouable [idBien=", "BienLouable [idBien=",
				", surfaceHabitable=", ", surfaceHabitable=", "BienLouable [idBien=", (-1.0F), (-1.0F),
				"BienLouable [idBien=", localDate0, (-1.0F), 0, (-1.0F), (-3279.971137), ", surfaceHabitable=",
				integer0);
		String string0 = bienLouable0.getNumeroFiscal();
		assertEquals((-1.0), bienLouable0.getPourcentageEntretienPartiesCommunes(), 0.01);
		assertEquals(", surfaceHabitable=", bienLouable0.getCodePostal());
		assertEquals(", surfaceHabitable=", bienLouable0.getAdresse());
		assertEquals("BienLouable [idBien=", bienLouable0.getIdBat());
		assertEquals((-1.0F), bienLouable0.getSurfaceHabitable(), 0.01F);
		assertEquals(", surfaceHabitable=", string0);
		assertEquals(0, bienLouable0.getNbPieces());
		assertEquals("BienLouable [idBien=", bienLouable0.getIdBien());
		assertEquals("BienLouable [idBien=", bienLouable0.getTypeBien());
		assertEquals((-1.0F), bienLouable0.getProvisionPourCharges(), 0.01F);
		assertEquals("BienLouable [idBien=", bienLouable0.getVille());
		assertEquals((-1.0F), bienLouable0.getLoyer(), 0.01F);
		assertEquals((-3279.971137), bienLouable0.getPourcentageOrduresMenageres(), 0.01);
	}

	@Test(timeout = 4000)
	public void test59() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Integer integer0 = new Integer((-32));
		BienLouable bienLouable0 = new BienLouable("B", "B", "B", "B", "B", (-839.2734F), (-839.2734F), ", ypeBen7",
				localDate0, (-839.2734F), (-32), (-839.2734F), (-839.2734F), "B", integer0);
		int int0 = bienLouable0.getNbPieces();
		assertEquals((-839.2733764648438), bienLouable0.getPourcentageOrduresMenageres(), 0.01);
		assertEquals("B", bienLouable0.getCodePostal());
		assertEquals("B", bienLouable0.getAdresse());
		assertEquals((-839.2733764648438), bienLouable0.getPourcentageEntretienPartiesCommunes(), 0.01);
		assertEquals("B", bienLouable0.getVille());
		assertEquals("B", bienLouable0.getIdBat());
		assertEquals((-839.2734F), bienLouable0.getProvisionPourCharges(), 0.01F);
		assertEquals("B", bienLouable0.getIdBien());
		assertEquals(", ypeBen7", bienLouable0.getTypeBien());
		assertEquals((-32), int0);
		assertEquals("B", bienLouable0.getNumeroFiscal());
		assertEquals((-839.2734F), bienLouable0.getSurfaceHabitable(), 0.01F);
		assertEquals((-839.2734F), bienLouable0.getLoyer(), 0.01F);
	}

	@Test(timeout = 4000)
	public void test60() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Integer integer0 = new Integer((-31));
		BienLouable bienLouable0 = new BienLouable("B", "B", "B", "B", "B", (-838.75476F), (-838.75476F), ", ypeBen=",
				localDate0, (-838.75476F), (-31), (-838.75476F), (-838.75476F), "B", integer0);
		double double0 = bienLouable0.getPourcentageEntretienPartiesCommunes();
		assertEquals((-838.75476F), bienLouable0.getSurfaceHabitable(), 0.01F);
		assertEquals("B", bienLouable0.getNumeroFiscal());
		assertEquals(", ypeBen=", bienLouable0.getTypeBien());
		assertEquals("B", bienLouable0.getIdBien());
		assertEquals((-838.7547607421875), bienLouable0.getPourcentageOrduresMenageres(), 0.01);
		assertEquals((-838.7547607421875), double0, 0.01);
		assertEquals((-838.75476F), bienLouable0.getProvisionPourCharges(), 0.01F);
		assertEquals("B", bienLouable0.getAdresse());
		assertEquals((-838.75476F), bienLouable0.getLoyer(), 0.01F);
		assertEquals("B", bienLouable0.getCodePostal());
		assertEquals("B", bienLouable0.getIdBat());
		assertEquals((-31), bienLouable0.getNbPieces());
		assertEquals("B", bienLouable0.getVille());
	}

	@Test(timeout = 4000)
	public void test61() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Integer integer0 = new Integer((-31));
		BienLouable bienLouable0 = new BienLouable("B", "B", "B", "B", "B", (-838.75476F), (-838.75476F), ", ypeBen=",
				localDate0, (-838.75476F), (-31), (-838.75476F), (-838.75476F), "B", integer0);
		float float0 = bienLouable0.getProvisionPourCharges();
		assertEquals((-838.75476F), bienLouable0.getLoyer(), 0.01F);
		assertEquals((-838.7547607421875), bienLouable0.getPourcentageOrduresMenageres(), 0.01);
		assertEquals("B", bienLouable0.getNumeroFiscal());
		assertEquals("B", bienLouable0.getAdresse());
		assertEquals("B", bienLouable0.getCodePostal());
		assertEquals((-838.75476F), bienLouable0.getSurfaceHabitable(), 0.01F);
		assertEquals("B", bienLouable0.getIdBien());
		assertEquals(", ypeBen=", bienLouable0.getTypeBien());
		assertEquals("B", bienLouable0.getVille());
		assertEquals("B", bienLouable0.getIdBat());
		assertEquals((-31), bienLouable0.getNbPieces());
		assertEquals((-838.75476F), float0, 0.01F);
		assertEquals((-838.7547607421875), bienLouable0.getPourcentageEntretienPartiesCommunes(), 0.01);
	}

	@Test(timeout = 4000)
	public void test62() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		BienLouable bienLouable0 = new BienLouable(", idBat=", ", idBat=", ", idBat=", ", idBat=", ", idBat=",
				(-1848.5719F), 1185, ", idBat=", localDate0, (-1848.5719F), 1185, 1185, 1185, ", idBat=",
				(Integer) null);
		float float0 = bienLouable0.getLoyer();
		assertEquals((-1848.5719F), float0, 0.01F);
		assertEquals(1185, bienLouable0.getNbPieces());
		assertEquals((-1848.5719F), bienLouable0.getSurfaceHabitable(), 0.01F);
		assertEquals(1185.0, bienLouable0.getPourcentageOrduresMenageres(), 0.01);
		assertEquals(1185.0F, bienLouable0.getProvisionPourCharges(), 0.01F);
		assertEquals(1185.0, bienLouable0.getPourcentageEntretienPartiesCommunes(), 0.01);
	}

	@Test(timeout = 4000)
	public void test63() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Integer integer0 = new Integer(2126221414);
		BienLouable bienLouable0 = new BienLouable("o(x", "o(x", "o(x", "o(x", "o(x", 2126221414, 2126221414, "o(x",
				localDate0, 2126221414, 2126221414, 2126221414, 2126221414, "o(x", integer0);
		bienLouable0.setDerniereAnneeModifLoyer(2126221414);
		assertEquals(2.12622144E9F, bienLouable0.getLoyer(), 0.01F);
		assertEquals(2.12622144E9F, bienLouable0.getSurfaceHabitable(), 0.01F);
		assertEquals(2.12622144E9F, bienLouable0.getProvisionPourCharges(), 0.01F);
		assertEquals(2.126221414E9, bienLouable0.getPourcentageOrduresMenageres(), 0.01);
		assertEquals(2126221414, bienLouable0.getNbPieces());
		assertEquals(2126221414, (int) bienLouable0.getDerniereAnneeModifLoyer());
		assertEquals(2.126221414E9, bienLouable0.getPourcentageEntretienPartiesCommunes(), 0.01);
	}

	@Test(timeout = 4000)
	public void test64() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Integer integer0 = new Integer((-1));
		BienLouable bienLouable0 = new BienLouable("B", "B", "B", "B", "B", (-838.75476F), (-838.75476F), ", ypeBen=",
				localDate0, (-838.75476F), (-1), (-838.75476F), (-838.75476F), "B", integer0);
		bienLouable0.getDerniereAnneeModifLoyer();
		assertEquals("B", bienLouable0.getIdBien());
		assertEquals("B", bienLouable0.getVille());
		assertEquals((-1), bienLouable0.getNbPieces());
		assertEquals("B", bienLouable0.getAdresse());
		assertEquals((-838.75476F), bienLouable0.getProvisionPourCharges(), 0.01F);
		assertEquals("B", bienLouable0.getNumeroFiscal());
		assertEquals((-838.7547607421875), bienLouable0.getPourcentageOrduresMenageres(), 0.01);
		assertEquals("B", bienLouable0.getIdBat());
		assertEquals((-838.7547607421875), bienLouable0.getPourcentageEntretienPartiesCommunes(), 0.01);
		assertEquals(", ypeBen=", bienLouable0.getTypeBien());
		assertEquals("B", bienLouable0.getCodePostal());
		assertEquals((-838.75476F), bienLouable0.getLoyer(), 0.01F);
		assertEquals((-838.75476F), bienLouable0.getSurfaceHabitable(), 0.01F);
	}

	@Test(timeout = 4000)
	public void test65() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Integer integer0 = new Integer(465);
		BienLouable bienLouable0 = new BienLouable("", "", "", "", "", 465, 465, "", localDate0, 465, 465, 465, 465, "",
				integer0);
		bienLouable0.setTypeBien("");
		assertEquals(465, bienLouable0.getNbPieces());
		assertEquals(465.0, bienLouable0.getPourcentageOrduresMenageres(), 0.01);
		assertEquals(465.0F, bienLouable0.getSurfaceHabitable(), 0.01F);
		assertEquals(465.0F, bienLouable0.getProvisionPourCharges(), 0.01F);
		assertEquals(465.0F, bienLouable0.getLoyer(), 0.01F);
		assertEquals(465.0, bienLouable0.getPourcentageEntretienPartiesCommunes(), 0.01);
	}

	@Test(timeout = 4000)
	public void test66() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Integer integer0 = new Integer((-31));
		BienLouable bienLouable0 = new BienLouable("B", "B", "B", "B", "B", (-838.75476F), (-838.75476F), ", ypeBen=",
				localDate0, (-838.75476F), (-31), (-838.75476F), (-838.75476F), "B", integer0);
		String string0 = bienLouable0.getAdresse();
		assertEquals((-31), bienLouable0.getNbPieces());
		assertEquals("B", bienLouable0.getNumeroFiscal());
		assertEquals("B", bienLouable0.getVille());
		assertEquals((-838.75476F), bienLouable0.getSurfaceHabitable(), 0.01F);
		assertEquals("B", bienLouable0.getCodePostal());
		assertEquals((-838.75476F), bienLouable0.getProvisionPourCharges(), 0.01F);
		assertEquals("B", bienLouable0.getIdBat());
		assertEquals((-838.75476F), bienLouable0.getLoyer(), 0.01F);
		assertEquals((-838.7547607421875), bienLouable0.getPourcentageEntretienPartiesCommunes(), 0.01);
		assertEquals(", ypeBen=", bienLouable0.getTypeBien());
		assertEquals("B", bienLouable0.getIdBien());
		assertEquals((-838.7547607421875), bienLouable0.getPourcentageOrduresMenageres(), 0.01);
		assertEquals("B", string0);
	}

	@Test(timeout = 4000)
	public void test67() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Integer integer0 = new Integer(2126221433);
		BienLouable bienLouable0 = new BienLouable("h ", "h ", "h ", "h ", "h ", 2126221433, 2126221433, "h ",
				localDate0, 2126221433, 2126221433, 2126221433, 2126221433, "h ", integer0);
		bienLouable0.setAdresse("h ");
		assertEquals(2.126221433E9, bienLouable0.getPourcentageOrduresMenageres(), 0.01);
		assertEquals(2.12622144E9F, bienLouable0.getLoyer(), 0.01F);
		assertEquals(2.12622144E9F, bienLouable0.getProvisionPourCharges(), 0.01F);
		assertEquals(2126221433, bienLouable0.getNbPieces());
		assertEquals(2.126221433E9, bienLouable0.getPourcentageEntretienPartiesCommunes(), 0.01);
		assertEquals(2.12622144E9F, bienLouable0.getSurfaceHabitable(), 0.01F);
	}

	@Test(timeout = 4000)
	public void test68() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Integer integer0 = new Integer(12);
		BienLouable bienLouable0 = new BienLouable("", "", "uI8u;@2,~Tk-VC,g", (String) null, "}BouoB&!!", 1.0F,
				(-2217.069F), "OK&f\"YU#zh 4MPD", localDate0, 0.0F, 2146487172, 0.0F, (-1.0), "H1=fn8Nks", integer0);
		String string0 = bienLouable0.getVille();
		assertEquals("}BouoB&!!", string0);
		assertEquals(0.0, bienLouable0.getPourcentageEntretienPartiesCommunes(), 0.01);
		assertEquals((-1.0), bienLouable0.getPourcentageOrduresMenageres(), 0.01);
		assertEquals((-2217.069F), bienLouable0.getProvisionPourCharges(), 0.01F);
		assertEquals(0.0F, bienLouable0.getSurfaceHabitable(), 0.01F);
		assertEquals("", bienLouable0.getIdBien());
		assertEquals(1.0F, bienLouable0.getLoyer(), 0.01F);
		assertEquals("H1=fn8Nks", bienLouable0.getNumeroFiscal());
		assertEquals("", bienLouable0.getIdBat());
		assertEquals("OK&f\"YU#zh 4MPD", bienLouable0.getTypeBien());
		assertEquals("uI8u;@2,~Tk-VC,g", bienLouable0.getAdresse());
		assertEquals(2146487172, bienLouable0.getNbPieces());
		assertNotNull(string0);
	}

	@Test(timeout = 4000)
	public void test69() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Integer integer0 = new Integer((-31));
		BienLouable bienLouable0 = new BienLouable("B", "B", "B", "B", "B", (-1839.0756F), (-1839.0756F), "B",
				localDate0, (-1839.0756F), (-31), (-1839.0756F), (-1839.0756F), "B", integer0);
		bienLouable0.getTypeBien();
		assertEquals((-1839.0756F), bienLouable0.getLoyer(), 0.01F);
		assertEquals((-1839.0756F), bienLouable0.getProvisionPourCharges(), 0.01F);
		assertEquals((-1839.0756F), bienLouable0.getSurfaceHabitable(), 0.01F);
		assertEquals((-31), bienLouable0.getNbPieces());
		assertEquals((-1839.0755615234375), bienLouable0.getPourcentageOrduresMenageres(), 0.01);
		assertEquals((-1839.0755615234375), bienLouable0.getPourcentageEntretienPartiesCommunes(), 0.01);
	}

	@Test(timeout = 4000)
	public void test70() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Integer integer0 = new Integer((-1));
		BienLouable bienLouable0 = new BienLouable("#", "#", "#", "#", "#", (-838.75476F), (-838.75476F),
				", \u0004peBen=", localDate0, (-838.75476F), (-1), (-838.75476F), (-838.75476F), "#", integer0);
		String string0 = bienLouable0.getIdBien();
		assertEquals((-838.75476F), bienLouable0.getSurfaceHabitable(), 0.01F);
		assertEquals("#", string0);
		assertEquals((-1), bienLouable0.getNbPieces());
		assertEquals("#", bienLouable0.getVille());
		assertEquals((-838.7547607421875), bienLouable0.getPourcentageOrduresMenageres(), 0.01);
		assertEquals("#", bienLouable0.getIdBat());
		assertEquals((-838.7547607421875), bienLouable0.getPourcentageEntretienPartiesCommunes(), 0.01);
		assertEquals((-838.75476F), bienLouable0.getLoyer(), 0.01F);
		assertEquals((-838.75476F), bienLouable0.getProvisionPourCharges(), 0.01F);
		assertEquals(", \u0004peBen=", bienLouable0.getTypeBien());
		assertEquals("#", bienLouable0.getNumeroFiscal());
		assertEquals("#", bienLouable0.getAdresse());
		assertEquals("#", bienLouable0.getCodePostal());
	}

	@Test(timeout = 4000)
	public void test71() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Integer integer0 = new Integer(2126221433);
		BienLouable bienLouable0 = new BienLouable("<Y%lT:of=QBi3O", "<Y%lT:of=QBi3O", "<Y%lT:of=QBi3O",
				"<Y%lT:of=QBi3O", "<Y%lT:of=QBi3O", 2126221433, 2126221433, "<Y%lT:of=QBi3O", localDate0, 2126221433,
				2126221433, 2126221433, 2126221433, "<Y%lT:of=QBi3O", integer0);
		bienLouable0.setLoyer(2126221433);
		assertEquals(2126221433, bienLouable0.getNbPieces());
		assertEquals(2.126221433E9, bienLouable0.getPourcentageOrduresMenageres(), 0.01);
		assertEquals(2.126221433E9, bienLouable0.getPourcentageEntretienPartiesCommunes(), 0.01);
		assertEquals(2.12622144E9F, bienLouable0.getSurfaceHabitable(), 0.01F);
		assertEquals(2.12622144E9F, bienLouable0.getProvisionPourCharges(), 0.01F);
		assertEquals(2.12622144E9F, bienLouable0.getLoyer(), 0.01F);
	}
}
