/*
 * This file was automatically generated by EvoSuite
 * Fri Jan 16 13:24:10 GMT 2026
 */

package test.modele;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertNull;
import static org.junit.Assert.assertTrue;

import java.time.Clock;
import java.time.LocalDate;
import java.time.Period;
import java.time.ZoneId;
import java.time.ZoneOffset;
import java.time.chrono.IsoChronology;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.time.MockClock;
import org.evosuite.runtime.mock.java.time.MockLocalDate;
import org.evosuite.runtime.mock.java.time.chrono.MockIsoChronology;
import org.junit.Test;
import org.junit.runner.RunWith;

import modele.Charge;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class Charge_ESTest extends Charge_ESTest_scaffolding {

	@Test(timeout = 4000)
	public void test00() throws Throwable {
		Period period0 = Period.ofMonths(0);
		IsoChronology isoChronology0 = period0.getChronology();
		ZoneOffset zoneOffset0 = ZoneOffset.ofHoursMinutes(0, 0);
		LocalDate localDate0 = MockIsoChronology.dateNow(isoChronology0, (ZoneId) zoneOffset0);
		Charge charge0 = new Charge((String) null, ", description=", localDate0, 0, ", description=", ", description=",
				(String) null, localDate0, localDate0);
		int int0 = charge0.getMontant();
		assertEquals(0, int0);
	}

	@Test(timeout = 4000)
	public void test01() throws Throwable {
		Clock clock0 = MockClock.systemDefaultZone();
		LocalDate localDate0 = MockLocalDate.now(clock0);
		Charge charge0 = new Charge("]", "v0l-l`MMCe>Nzq", localDate0, 1725, "Charge [idCharge=", "LmXAp", "",
				(LocalDate) null, localDate0);
		int int0 = charge0.getMontant();
		assertEquals("v0l-l`MMCe>Nzq", charge0.getLibelle());
		assertEquals(1725, int0);
		assertEquals("]", charge0.getIdCharge());
		assertEquals("", charge0.getIdBienLouable());
		assertEquals("Charge [idCharge=", charge0.getCommentaire());
		assertEquals("LmXAp", charge0.getIdBatiment());
	}

	@Test(timeout = 4000)
	public void test02() throws Throwable {
		Charge charge0 = new Charge("5&}/l@}Ar{w~VWA5", (String) null, (LocalDate) null, (-1), (String) null,
				(String) null, "", (LocalDate) null, (LocalDate) null);
		String string0 = charge0.getLibelle();
		assertNull(string0);
		assertEquals("5&}/l@}Ar{w~VWA5", charge0.getIdCharge());
		assertEquals("", charge0.getIdBienLouable());
		assertEquals((-1), charge0.getMontant());
	}

	@Test(timeout = 4000)
	public void test03() throws Throwable {
		Clock clock0 = MockClock.systemDefaultZone();
		LocalDate localDate0 = MockLocalDate.now(clock0);
		Charge charge0 = new Charge("", "", localDate0, (-1), "", "]", "LmXAp", localDate0, (LocalDate) null);
		assertEquals("", charge0.getLibelle());

		charge0.setLibelle("eN");
		charge0.getLibelle();
		assertEquals("]", charge0.getIdBatiment());
	}

	@Test(timeout = 4000)
	public void test04() throws Throwable {
		Clock clock0 = MockClock.systemDefaultZone();
		LocalDate localDate0 = MockLocalDate.now(clock0);
		Charge charge0 = new Charge("7D*", "7D*", localDate0, 2182, "7D*", "7D*", "7D*", localDate0, localDate0);
		charge0.getIdCharge();
		assertEquals(2182, charge0.getMontant());
	}

	@Test(timeout = 4000)
	public void test05() throws Throwable {
		Charge charge0 = new Charge("", "aZU!l#GUj~zd", (LocalDate) null, 4309, "", "z>|au", "z>|au", (LocalDate) null,
				(LocalDate) null);
		String string0 = charge0.getIdCharge();
		assertEquals("", string0);
		assertEquals("z>|au", charge0.getIdBatiment());
		assertEquals("z>|au", charge0.getIdBienLouable());
		assertEquals(4309, charge0.getMontant());
		assertEquals("aZU!l#GUj~zd", charge0.getLibelle());
		assertEquals("", charge0.getCommentaire());
	}

	@Test(timeout = 4000)
	public void test06() throws Throwable {
		Charge charge0 = new Charge("", (String) null, (LocalDate) null, 0, "", (String) null, (String) null,
				(LocalDate) null, (LocalDate) null);
		String string0 = charge0.getIdBienLouable();
		assertNull(string0);
		assertEquals(0, charge0.getMontant());
	}

	@Test(timeout = 4000)
	public void test07() throws Throwable {
		Period period0 = Period.ofMonths((-1062));
		IsoChronology isoChronology0 = period0.getChronology();
		LocalDate localDate0 = MockIsoChronology.dateNow(isoChronology0);
		Charge charge0 = new Charge("WRW&}*nRD7C@", "", localDate0, (-1062), "", "WRW&}*nRD7C@", "fP", localDate0,
				localDate0);
		String string0 = charge0.getIdBienLouable();
		assertEquals("fP", string0);
		assertEquals("WRW&}*nRD7C@", charge0.getIdBatiment());
		assertEquals("WRW&}*nRD7C@", charge0.getIdCharge());
		assertEquals("", charge0.getCommentaire());
		assertEquals("", charge0.getLibelle());
		assertEquals((-1062), charge0.getMontant());
	}

	@Test(timeout = 4000)
	public void test08() throws Throwable {
		Charge charge0 = new Charge((String) null, (String) null, (LocalDate) null, (-4), (String) null, (String) null,
				(String) null, (LocalDate) null, (LocalDate) null);
		charge0.getIdBatiment();
		assertEquals((-4), charge0.getMontant());
	}

	@Test(timeout = 4000)
	public void test09() throws Throwable {
		Charge charge0 = new Charge("", "", (LocalDate) null, 0, "", "", "", (LocalDate) null, (LocalDate) null);
		charge0.getIdBatiment();
		assertEquals(0, charge0.getMontant());
	}

	@Test(timeout = 4000)
	public void test10() throws Throwable {
		Charge charge0 = new Charge("5&}/l@}Ar{w~VWA5", (String) null, (LocalDate) null, (-1), (String) null,
				(String) null, "", (LocalDate) null, (LocalDate) null);
		charge0.getDateFinPeriode();
		assertEquals("5&}/l@}Ar{w~VWA5", charge0.getIdCharge());
		assertEquals((-1), charge0.getMontant());
		assertEquals("", charge0.getIdBienLouable());
	}

	@Test(timeout = 4000)
	public void test11() throws Throwable {
		Charge charge0 = new Charge((String) null, (String) null, (LocalDate) null, 1, (String) null, (String) null,
				(String) null, (LocalDate) null, (LocalDate) null);
		charge0.getDateFacturation();
		assertEquals(1, charge0.getMontant());
	}

	@Test(timeout = 4000)
	public void test12() throws Throwable {
		Clock clock0 = MockClock.systemDefaultZone();
		LocalDate localDate0 = MockLocalDate.now(clock0);
		Charge charge0 = new Charge("", "", localDate0, (-1), "", "]", "LmXAp", localDate0, (LocalDate) null);
		LocalDate localDate1 = charge0.getDateDebutPeriode();
		assertEquals("LmXAp", charge0.getIdBienLouable());
		assertEquals("", charge0.getCommentaire());
		assertEquals("", charge0.getIdCharge());
		assertNotNull(localDate1);
		assertEquals((-1), charge0.getMontant());
		assertEquals("]", charge0.getIdBatiment());
		assertEquals("", charge0.getLibelle());
	}

	@Test(timeout = 4000)
	public void test13() throws Throwable {
		Charge charge0 = new Charge("", (String) null, (LocalDate) null, 0, "", (String) null, (String) null,
				(LocalDate) null, (LocalDate) null);
		String string0 = charge0.getCommentaire();
		assertEquals(0, charge0.getMontant());
		assertNotNull(string0);
	}

	@Test(timeout = 4000)
	public void test14() throws Throwable {
		Charge charge0 = new Charge((String) null, (String) null, (LocalDate) null, (-28), (String) null, (String) null,
				(String) null, (LocalDate) null, (LocalDate) null);
		Charge charge1 = new Charge((String) null, (String) null, (LocalDate) null, (-28), (String) null, (String) null,
				(String) null, (LocalDate) null, (LocalDate) null);
		boolean boolean0 = charge0.equals(charge1);
		assertTrue(boolean0);
		assertEquals((-28), charge1.getMontant());
	}

	@Test(timeout = 4000)
	public void test15() throws Throwable {
		Clock clock0 = MockClock.systemDefaultZone();
		LocalDate localDate0 = MockLocalDate.now(clock0);
		Charge charge0 = new Charge("", "", localDate0, (-1), "", "]", "LmXAp", localDate0, (LocalDate) null);
		Charge charge1 = new Charge("]", "v0l-l`MMCe>Nzq", localDate0, 1725, "Charge [idCharge=", "LmXAp", "",
				(LocalDate) null, localDate0);
		boolean boolean0 = charge0.equals(charge1);
		assertEquals("Charge [idCharge=", charge1.getCommentaire());
		assertEquals("v0l-l`MMCe>Nzq", charge1.getLibelle());
		assertFalse(boolean0);
		assertEquals("LmXAp", charge1.getIdBatiment());
		assertEquals("]", charge1.getIdCharge());
		assertEquals("", charge1.getIdBienLouable());
		assertEquals(1725, charge1.getMontant());
	}

	@Test(timeout = 4000)
	public void test16() throws Throwable {
		Charge charge0 = new Charge((String) null, (String) null, (LocalDate) null, (-4), (String) null, (String) null,
				(String) null, (LocalDate) null, (LocalDate) null);
		boolean boolean0 = charge0.equals((Object) null);
		assertEquals((-4), charge0.getMontant());
		assertFalse(boolean0);
	}

	@Test(timeout = 4000)
	public void test17() throws Throwable {
		Charge charge0 = new Charge("41'\"K`Id}xJO", (String) null, (LocalDate) null, 25, (String) null,
				"41'\"K`Id}xJO", "m/", (LocalDate) null, (LocalDate) null);
		boolean boolean0 = charge0.equals(charge0);
		assertEquals("41'\"K`Id}xJO", charge0.getIdCharge());
		assertTrue(boolean0);
		assertEquals(25, charge0.getMontant());
		assertEquals("m/", charge0.getIdBienLouable());
		assertEquals("41'\"K`Id}xJO", charge0.getIdBatiment());
	}

	@Test(timeout = 4000)
	public void test18() throws Throwable {
		LocalDate localDate0 = MockLocalDate.ofEpochDay(0L);
		Charge charge0 = new Charge("", "", localDate0, 0, "K+7PYb$#M#U", "", ", bienLouable=", localDate0, localDate0);
		boolean boolean0 = charge0.equals(localDate0);
		assertEquals("", charge0.getLibelle());
		assertFalse(boolean0);
		assertEquals(0, charge0.getMontant());
		assertEquals("", charge0.getIdCharge());
		assertEquals("", charge0.getIdBatiment());
		assertEquals(", bienLouable=", charge0.getIdBienLouable());
		assertEquals("K+7PYb$#M#U", charge0.getCommentaire());
	}

	@Test(timeout = 4000)
	public void test19() throws Throwable {
		LocalDate localDate0 = MockLocalDate.ofEpochDay(0L);
		Charge charge0 = new Charge("}'LA-$ ", "", localDate0, 731, "}'LA-$ ", "", "", localDate0, localDate0);
		charge0.getDateFinPeriode();
		assertEquals("", charge0.getLibelle());
		assertEquals("}'LA-$ ", charge0.getIdCharge());
		assertEquals(731, charge0.getMontant());
		assertEquals("", charge0.getIdBienLouable());
		assertEquals("", charge0.getIdBatiment());
		assertEquals("}'LA-$ ", charge0.getCommentaire());
	}

	@Test(timeout = 4000)
	public void test20() throws Throwable {
		LocalDate localDate0 = MockLocalDate.ofEpochDay(0L);
		Charge charge0 = new Charge("}'LA-$ ", "", localDate0, 731, "}'LA-$ ", "", "", localDate0, localDate0);
		String string0 = charge0.getIdBienLouable();
		assertEquals(731, charge0.getMontant());
		assertEquals("}'LA-$ ", charge0.getIdCharge());
		assertEquals("", charge0.getIdBatiment());
		assertEquals("", charge0.getLibelle());
		assertEquals("", string0);
		assertEquals("}'LA-$ ", charge0.getCommentaire());
	}

	@Test(timeout = 4000)
	public void test21() throws Throwable {
		Charge charge0 = new Charge("5&}/l@}Ar{w~VWA5", (String) null, (LocalDate) null, (-1), (String) null,
				(String) null, "", (LocalDate) null, (LocalDate) null);
		charge0.getDateDebutPeriode();
		assertEquals((-1), charge0.getMontant());
		assertEquals("5&}/l@}Ar{w~VWA5", charge0.getIdCharge());
		assertEquals("", charge0.getIdBienLouable());
	}

	@Test(timeout = 4000)
	public void test22() throws Throwable {
		Clock clock0 = MockClock.systemDefaultZone();
		LocalDate localDate0 = MockLocalDate.now(clock0);
		Charge charge0 = new Charge("", "", localDate0, (-1), "", "]", "LmXAp", localDate0, (LocalDate) null);
		String string0 = charge0.getIdBatiment();
		assertEquals("]", string0);
		assertEquals((-1), charge0.getMontant());
		assertEquals("", charge0.getCommentaire());
		assertEquals("LmXAp", charge0.getIdBienLouable());
		assertEquals("", charge0.getIdCharge());
		assertEquals("", charge0.getLibelle());
	}

	@Test(timeout = 4000)
	public void test23() throws Throwable {
		Clock clock0 = MockClock.systemDefaultZone();
		LocalDate localDate0 = MockLocalDate.now(clock0);
		Charge charge0 = new Charge("", "", localDate0, (-1), "", "]", "LmXAp", localDate0, (LocalDate) null);
		int int0 = charge0.getMontant();
		assertEquals((-1), int0);
		assertEquals("", charge0.getCommentaire());
		assertEquals("", charge0.getIdCharge());
		assertEquals("LmXAp", charge0.getIdBienLouable());
		assertEquals("]", charge0.getIdBatiment());
		assertEquals("", charge0.getLibelle());
	}

	@Test(timeout = 4000)
	public void test24() throws Throwable {
		LocalDate localDate0 = MockLocalDate.ofEpochDay(0L);
		Charge charge0 = new Charge("", "", localDate0, 0, "K+7PYb$#M#U", "", ", bienLouable=", localDate0, localDate0);
		charge0.hashCode();
		assertEquals("K+7PYb$#M#U", charge0.getCommentaire());
		assertEquals(0, charge0.getMontant());
		assertEquals(", bienLouable=", charge0.getIdBienLouable());
		assertEquals("", charge0.getIdCharge());
		assertEquals("", charge0.getLibelle());
		assertEquals("", charge0.getIdBatiment());
	}

	@Test(timeout = 4000)
	public void test25() throws Throwable {
		Charge charge0 = new Charge((String) null, (String) null, (LocalDate) null, (-21), (String) null, (String) null,
				(String) null, (LocalDate) null, (LocalDate) null);
		charge0.setMontant((-21));
		assertEquals((-21), charge0.getMontant());
	}

	@Test(timeout = 4000)
	public void test26() throws Throwable {
		LocalDate localDate0 = MockLocalDate.ofEpochDay(0L);
		Charge charge0 = new Charge("", "", localDate0, 0, "K+7PYb$#M#U", "", ", bienLouable=", localDate0, localDate0);
		charge0.setDateDebutPeriode(localDate0);
		assertEquals(0, charge0.getMontant());
		assertEquals("", charge0.getLibelle());
		assertEquals("K+7PYb$#M#U", charge0.getCommentaire());
		assertEquals(", bienLouable=", charge0.getIdBienLouable());
		assertEquals("", charge0.getIdBatiment());
		assertEquals("", charge0.getIdCharge());
	}

	@Test(timeout = 4000)
	public void test27() throws Throwable {
		LocalDate localDate0 = MockLocalDate.ofEpochDay(0L);
		Charge charge0 = new Charge("", "", localDate0, 0, "K+7PYb$#M#U", "", ", bienLouable=", localDate0, localDate0);
		charge0.getDateFacturation();
		assertEquals("", charge0.getIdBatiment());
		assertEquals("", charge0.getIdCharge());
		assertEquals(", bienLouable=", charge0.getIdBienLouable());
		assertEquals("K+7PYb$#M#U", charge0.getCommentaire());
		assertEquals(0, charge0.getMontant());
		assertEquals("", charge0.getLibelle());
	}

	@Test(timeout = 4000)
	public void test28() throws Throwable {
		Period period0 = Period.ofMonths(0);
		IsoChronology isoChronology0 = period0.getChronology();
		ZoneOffset zoneOffset0 = ZoneOffset.ofHoursMinutes(0, 0);
		LocalDate localDate0 = MockIsoChronology.dateNow(isoChronology0, (ZoneId) zoneOffset0);
		Charge charge0 = new Charge((String) null, ", description=", localDate0, 0, ", description=", ", description=",
				(String) null, localDate0, localDate0);
		String string0 = charge0.getIdCharge();
		assertNull(string0);
		assertEquals(0, charge0.getMontant());
	}

	@Test(timeout = 4000)
	public void test29() throws Throwable {
		Charge charge0 = new Charge((String) null, (String) null, (LocalDate) null, 0, (String) null, (String) null,
				(String) null, (LocalDate) null, (LocalDate) null);
		charge0.setIdBatiment((String) null);
		assertEquals(0, charge0.getMontant());
	}

	@Test(timeout = 4000)
	public void test30() throws Throwable {
		Charge charge0 = new Charge((String) null, (String) null, (LocalDate) null, (-4), (String) null, (String) null,
				(String) null, (LocalDate) null, (LocalDate) null);
		charge0.setIdBienLouable((String) null);
		assertEquals((-4), charge0.getMontant());
	}

	@Test(timeout = 4000)
	public void test31() throws Throwable {
		LocalDate localDate0 = MockLocalDate.ofEpochDay(0L);
		Charge charge0 = new Charge("", "", localDate0, 0, "K+7PYb$#M#U", "", ", bienLouable=", localDate0, localDate0);
		charge0.setDateFacturation(localDate0);
		assertEquals(", bienLouable=", charge0.getIdBienLouable());
		assertEquals("", charge0.getIdCharge());
		assertEquals(0, charge0.getMontant());
		assertEquals("K+7PYb$#M#U", charge0.getCommentaire());
		assertEquals("", charge0.getLibelle());
		assertEquals("", charge0.getIdBatiment());
	}

	@Test(timeout = 4000)
	public void test32() throws Throwable {
		LocalDate localDate0 = MockLocalDate.ofEpochDay(0L);
		Charge charge0 = new Charge("", "", localDate0, 0, "K+7PYb$#M#U", "", ", bienLouable=", localDate0, localDate0);
		String string0 = charge0.getLibelle();
		assertEquals("", charge0.getIdCharge());
		assertEquals("K+7PYb$#M#U", charge0.getCommentaire());
		assertEquals(", bienLouable=", charge0.getIdBienLouable());
		assertEquals("", charge0.getIdBatiment());
		assertEquals("", string0);
		assertEquals(0, charge0.getMontant());
	}

	@Test(timeout = 4000)
	public void test33() throws Throwable {
		LocalDate localDate0 = MockLocalDate.ofEpochDay(0L);
		Charge charge0 = new Charge("", "", localDate0, 0, "K+7PYb$#M#U", "", ", bienLouable=", localDate0, localDate0);
		assertEquals("K+7PYb$#M#U", charge0.getCommentaire());

		charge0.setCommentaire((String) null);
		charge0.getCommentaire();
		assertEquals("", charge0.getLibelle());
		assertEquals(", bienLouable=", charge0.getIdBienLouable());
		assertEquals(0, charge0.getMontant());
		assertEquals("", charge0.getIdCharge());
		assertEquals("", charge0.getIdBatiment());
	}

	@Test(timeout = 4000)
	public void test34() throws Throwable {
		Clock clock0 = MockClock.systemDefaultZone();
		LocalDate localDate0 = MockLocalDate.now(clock0);
		Charge charge0 = new Charge("", "", localDate0, (-1), "", "]", "LmXAp", localDate0, (LocalDate) null);
		String string0 = charge0.toString();
		assertEquals(
				"Charge [idCharge=, libell\u00E9=, dateFacturation=2014-02-14, montant=-1, description=, batiment=], bienLouable=LmXAp]",
				string0);
	}

	@Test(timeout = 4000)
	public void test35() throws Throwable {
		LocalDate localDate0 = MockLocalDate.ofEpochDay(0L);
		Charge charge0 = new Charge("", "", localDate0, 0, "K+7PYb$#M#U", "", ", bienLouable=", localDate0, localDate0);
		charge0.setDateFinPeriode(localDate0);
		assertEquals("", charge0.getIdBatiment());
		assertEquals("K+7PYb$#M#U", charge0.getCommentaire());
		assertEquals(", bienLouable=", charge0.getIdBienLouable());
		assertEquals("", charge0.getLibelle());
		assertEquals(0, charge0.getMontant());
		assertEquals("", charge0.getIdCharge());
	}

	@Test(timeout = 4000)
	public void test36() throws Throwable {
		Charge charge0 = new Charge((String) null, (String) null, (LocalDate) null, 7, (String) null, (String) null,
				(String) null, (LocalDate) null, (LocalDate) null);
		charge0.setIdCharge((String) null);
		assertEquals(7, charge0.getMontant());
	}

	@Test(timeout = 4000)
	public void test37() throws Throwable {
		LocalDate localDate0 = MockLocalDate.ofEpochDay(0L);
		Charge charge0 = new Charge("", "", localDate0, 0, "K+7PYb$#M#U", "", ", bienLouable=", localDate0, localDate0);
		String string0 = charge0.getCommentaire();
		assertEquals("K+7PYb$#M#U", string0);
		assertEquals(0, charge0.getMontant());
		assertEquals("", charge0.getIdBatiment());
		assertEquals("", charge0.getIdCharge());
		assertEquals(", bienLouable=", charge0.getIdBienLouable());
		assertEquals("", charge0.getLibelle());
	}
}
