/*
 * This file was automatically generated by EvoSuite
 * Fri Jan 16 13:26:57 GMT 2026
 */

package test.modele;

import static org.evosuite.runtime.EvoAssertions.verifyException;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertNull;
import static org.junit.Assert.assertSame;
import static org.junit.Assert.assertTrue;
import static org.junit.Assert.fail;

import java.time.Clock;
import java.time.LocalDate;
import java.time.Month;
import java.time.Period;
import java.time.ZoneId;
import java.time.ZoneOffset;
import java.time.chrono.IsoChronology;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.time.MockClock;
import org.evosuite.runtime.mock.java.time.MockLocalDate;
import org.evosuite.runtime.mock.java.time.chrono.MockIsoChronology;
import org.junit.Test;
import org.junit.runner.RunWith;

import modele.Compteur;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class Compteur_ESTest extends Compteur_ESTest_scaffolding {

	@Test(timeout = 4000)
	public void test00() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Compteur compteur0 = new Compteur((String) null, (String) null, "Pa", "Pa", localDate0, (Float) null);
		try {
			compteur0.setIdCompteur("");
			fail("Expecting exception: IllegalArgumentException");

		} catch (IllegalArgumentException e) {
			//
			// L'identificateur du relev\u00E9 du compteur n'est pas valable !
			//
			verifyException("modele.Compteur", e);
		}
	}

	@Test(timeout = 4000)
	public void test01() throws Throwable {
		Clock clock0 = MockClock.systemUTC();
		LocalDate localDate0 = MockLocalDate.now(clock0);
		Float float0 = new Float(1.0F);
		Compteur compteur0 = new Compteur("z!", "z!", "z!", "z!", localDate0, float0);
		String string0 = compteur0.getTypeCompteur();
		assertEquals("z!", string0);
	}

	@Test(timeout = 4000)
	public void test02() throws Throwable {
		Float float0 = new Float(1.0F);
		Compteur compteur0 = new Compteur("", "92he!1?", "", "?/", (LocalDate) null, float0);
		String string0 = compteur0.getTypeCompteur();
		assertEquals("", string0);
		assertEquals("92he!1?", compteur0.getIdBien());
		assertEquals("?/", compteur0.getIdCompteur());
		assertEquals("", compteur0.getIdBat());
	}

	@Test(timeout = 4000)
	public void test03() throws Throwable {
		Period period0 = Period.ZERO;
		IsoChronology isoChronology0 = period0.getChronology();
		LocalDate localDate0 = MockIsoChronology.dateNow(isoChronology0);
		Float float0 = new Float(0.0);
		Compteur compteur0 = new Compteur("]", "]", ">_0sDoZrxbnA//", (String) null, localDate0, float0);
		compteur0.getIndexDepart();
		assertEquals("]", compteur0.getIdBat());
		assertEquals("]", compteur0.getIdBien());
		assertEquals(">_0sDoZrxbnA//", compteur0.getTypeCompteur());
	}

	@Test(timeout = 4000)
	public void test04() throws Throwable {
		ZoneOffset zoneOffset0 = ZoneOffset.ofHours(1);
		LocalDate localDate0 = MockLocalDate.now((ZoneId) zoneOffset0);
		Compteur compteur0 = new Compteur("0AV>YFb7\"T", "", "", "", localDate0, (Float) null);
		compteur0.getIndexDepart();
		assertEquals("", compteur0.getIdCompteur());
		assertEquals("", compteur0.getTypeCompteur());
		assertEquals("0AV>YFb7\"T", compteur0.getIdBat());
		assertEquals("", compteur0.getIdBien());
	}

	@Test(timeout = 4000)
	public void test05() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Float float0 = new Float((-2218.681));
		Compteur compteur0 = new Compteur((String) null, "^yjNoq0YvchbnqZ", "NwQ$K`l=8st-B5?]P>$", "", localDate0,
				float0);
		compteur0.getIndexDepart();
		assertEquals("", compteur0.getIdCompteur());
		assertEquals("NwQ$K`l=8st-B5?]P>$", compteur0.getTypeCompteur());
		assertEquals("^yjNoq0YvchbnqZ", compteur0.getIdBien());
	}

	@Test(timeout = 4000)
	public void test06() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Float float0 = new Float(0.0F);
		Compteur compteur0 = new Compteur((String) null, "^yjNoq0YvchbnqZ", "", (String) null, localDate0, float0);
		String string0 = compteur0.getIdCompteur();
		assertEquals("^yjNoq0YvchbnqZ", compteur0.getIdBien());
		assertNull(string0);
		assertEquals("", compteur0.getTypeCompteur());
	}

	@Test(timeout = 4000)
	public void test07() throws Throwable {
		Month month0 = Month.DECEMBER;
		LocalDate localDate0 = MockLocalDate.of(1, month0, 1);
		Float float0 = new Float((float) 1);
		Compteur compteur0 = new Compteur("", "", "", "", localDate0, float0);
		String string0 = compteur0.getIdCompteur();
		assertEquals("", string0);
	}

	@Test(timeout = 4000)
	public void test08() throws Throwable {
		ZoneOffset zoneOffset0 = ZoneOffset.ofHours(1);
		LocalDate localDate0 = MockLocalDate.now((ZoneId) zoneOffset0);
		Float float0 = new Float((float) 1);
		Compteur compteur0 = new Compteur("9%aw1Il:+va1feK", (String) null,
				"Compteur [bat=, bien=, typeCompteur=NE'u5di*l9W{M]S, idCompteur=]", "", localDate0, float0);
		String string0 = compteur0.getIdBien();
		assertEquals("9%aw1Il:+va1feK", compteur0.getIdBat());
		assertNull(string0);
		assertEquals("", compteur0.getIdCompteur());
		assertEquals("Compteur [bat=, bien=, typeCompteur=NE'u5di*l9W{M]S, idCompteur=]", compteur0.getTypeCompteur());
	}

	@Test(timeout = 4000)
	public void test09() throws Throwable {
		ZoneOffset zoneOffset0 = ZoneOffset.ofHours(1);
		LocalDate localDate0 = MockLocalDate.now((ZoneId) zoneOffset0);
		Compteur compteur0 = new Compteur("0AV>YFb7\"T", "", "", "", localDate0, (Float) null);
		String string0 = compteur0.getIdBien();
		assertEquals("", compteur0.getTypeCompteur());
		assertEquals("", compteur0.getIdCompteur());
		assertEquals("", string0);
		assertEquals("0AV>YFb7\"T", compteur0.getIdBat());
	}

	@Test(timeout = 4000)
	public void test10() throws Throwable {
		Clock clock0 = MockClock.systemUTC();
		LocalDate localDate0 = MockLocalDate.now(clock0);
		Float float0 = new Float(1.0F);
		Compteur compteur0 = new Compteur("z!", "z!", "z!", "z!", localDate0, float0);
		compteur0.setIdBat((String) null);
		String string0 = compteur0.getIdBat();
		assertNull(string0);
	}

	@Test(timeout = 4000)
	public void test11() throws Throwable {
		ZoneOffset zoneOffset0 = ZoneOffset.ofHours(1);
		LocalDate localDate0 = MockLocalDate.now((ZoneId) zoneOffset0);
		Float float0 = new Float((float) 1);
		Compteur compteur0 = new Compteur("NE'u5di*l9W{M]S", "NE'u5di*l9W{M]S", "NE'u5di*l9W{M]S", "", localDate0,
				float0);
		assertEquals("NE'u5di*l9W{M]S", compteur0.getIdBat());

		compteur0.setIdBat("");
		compteur0.getIdBat();
		assertEquals("", compteur0.getIdCompteur());
	}

	@Test(timeout = 4000)
	public void test12() throws Throwable {
		Float float0 = new Float((-3414.36F));
		Compteur compteur0 = new Compteur("", "", "ts:oCOrf[L", "ts:oCOrf[L", (LocalDate) null, float0);
		compteur0.getDateInstallation();
		assertEquals("ts:oCOrf[L", compteur0.getTypeCompteur());
		assertEquals("", compteur0.getIdBien());
		assertEquals("", compteur0.getIdBat());
		assertEquals("ts:oCOrf[L", compteur0.getIdCompteur());
	}

	@Test(timeout = 4000)
	public void test13() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Compteur compteur0 = new Compteur((String) null, (String) null, (String) null, (String) null, localDate0,
				(Float) null);
		// Undeclared exception!
		try {
			compteur0.setIdCompteur((String) null);
			fail("Expecting exception: NullPointerException");

		} catch (NullPointerException e) {
			//
			// no message in exception (getMessage() returned null)
			//
			verifyException("modele.Compteur", e);
		}
	}

	@Test(timeout = 4000)
	public void test14() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Compteur compteur0 = new Compteur("modele.Compteur", "modele.Compteur", "modele.Compteur", "modele.Compteur",
				localDate0, (Float) null);
		Compteur compteur1 = new Compteur("", "modele.Compteur", "modele.Compteur", "modele.Compteur", localDate0,
				(Float) null);
		boolean boolean0 = compteur0.equals(compteur1);
		assertEquals("modele.Compteur", compteur1.getTypeCompteur());
		assertEquals("", compteur1.getIdBat());
		assertTrue(boolean0);
		assertEquals("modele.Compteur", compteur1.getIdBien());
	}

	@Test(timeout = 4000)
	public void test15() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Compteur compteur0 = new Compteur((String) null, (String) null, (String) null, (String) null, localDate0,
				(Float) null);
		boolean boolean0 = compteur0.equals((Object) null);
		assertFalse(boolean0);
	}

	@Test(timeout = 4000)
	public void test16() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Float float0 = new Float((float) (-1235));
		Compteur compteur0 = new Compteur((String) null, (String) null, (String) null, (String) null, localDate0,
				float0);
		boolean boolean0 = compteur0.equals(compteur0);
		assertTrue(boolean0);
	}

	@Test(timeout = 4000)
	public void test17() throws Throwable {
		Float float0 = new Float((-3414.36F));
		Compteur compteur0 = new Compteur("", "", "ts:oCOrf[L", "ts:oCOrf[L", (LocalDate) null, float0);
		Object object0 = new Object();
		boolean boolean0 = compteur0.equals(object0);
		assertFalse(boolean0);
		assertEquals("", compteur0.getIdBat());
		assertEquals("ts:oCOrf[L", compteur0.getTypeCompteur());
		assertEquals("", compteur0.getIdBien());
		assertEquals("ts:oCOrf[L", compteur0.getIdCompteur());
	}

	@Test(timeout = 4000)
	public void test18() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Compteur compteur0 = new Compteur("Or=z&a_,B#Ywg/8$", "Or=z&a_,B#Ywg/8$", "Or=z&a_,B#Ywg/8$",
				"Or=z&a_,B#Ywg/8$", localDate0, (Float) null);
		try {
			compteur0.setIdCompteur("Or=z&a_,B#Ywg/8$");
			fail("Expecting exception: IllegalArgumentException");

		} catch (IllegalArgumentException e) {
			//
			// L'identificateur du relev\u00E9 du compteur n'est pas valable !
			//
			verifyException("modele.Compteur", e);
		}
	}

	@Test(timeout = 4000)
	public void test19() throws Throwable {
		Float float0 = new Float((-3414.36F));
		Compteur compteur0 = new Compteur("", "", "ts:oCOrf[L", "ts:oCOrf[L", (LocalDate) null, float0);
		assertEquals("ts:oCOrf[L", compteur0.getIdCompteur());

		compteur0.setIdCompteur("ts:oCOrf[L");
		assertEquals("", compteur0.getIdBien());
		assertEquals("ts:oCOrf[L", compteur0.getTypeCompteur());
		assertEquals("", compteur0.getIdBat());
	}

	@Test(timeout = 4000)
	public void test20() throws Throwable {
		Clock clock0 = MockClock.systemUTC();
		LocalDate localDate0 = MockLocalDate.now(clock0);
		Float float0 = new Float(1.0F);
		Compteur compteur0 = new Compteur("z!", "z!", "z!", "z!", localDate0, float0);
		String string0 = compteur0.getIdCompteur();
		assertEquals("z!", string0);
	}

	@Test(timeout = 4000)
	public void test21() throws Throwable {
		Clock clock0 = MockClock.systemUTC();
		LocalDate localDate0 = MockLocalDate.now(clock0);
		Float float0 = new Float(1.0F);
		Compteur compteur0 = new Compteur("z!", "z!", "z!", "z!", localDate0, float0);
		Float float1 = compteur0.getIndexDepart();
		assertEquals(1.0F, (float) float1, 0.01F);
	}

	@Test(timeout = 4000)
	public void test22() throws Throwable {
		Clock clock0 = MockClock.systemUTC();
		LocalDate localDate0 = MockLocalDate.now(clock0);
		Float float0 = new Float(1.0F);
		Compteur compteur0 = new Compteur("z!", "z!", "z!", "z!", localDate0, float0);
		String string0 = compteur0.getIdBat();
		assertEquals("z!", string0);
	}

	@Test(timeout = 4000)
	public void test23() throws Throwable {
		Clock clock0 = MockClock.systemUTC();
		LocalDate localDate0 = MockLocalDate.now(clock0);
		Float float0 = new Float(1.0F);
		Compteur compteur0 = new Compteur("z!", "z!", "z!", "z!", localDate0, float0);
		String string0 = compteur0.getIdBien();
		assertEquals("z!", string0);
	}

	@Test(timeout = 4000)
	public void test24() throws Throwable {
		Clock clock0 = MockClock.systemUTC();
		LocalDate localDate0 = MockLocalDate.now(clock0);
		Float float0 = new Float(1.0F);
		Compteur compteur0 = new Compteur("z!", "z!", "z!", "z!", localDate0, float0);
		compteur0.setIndexDepart(float0);
		assertEquals(1.0F, compteur0.getIndexDepart(), 0.01F);
	}

	@Test(timeout = 4000)
	public void test25() throws Throwable {
		Clock clock0 = MockClock.systemUTC();
		LocalDate localDate0 = MockLocalDate.now(clock0);
		Float float0 = new Float(1.0F);
		Compteur compteur0 = new Compteur("z!", "z!", "z!", "z!", localDate0, float0);
		compteur0.setIdBien("z!");
		assertEquals("z!", compteur0.getIdBien());
	}

	@Test(timeout = 4000)
	public void test26() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Compteur compteur0 = new Compteur((String) null, (String) null, (String) null, (String) null, localDate0,
				(Float) null);
		String string0 = compteur0.getTypeCompteur();
		assertNull(string0);
	}

	@Test(timeout = 4000)
	public void test27() throws Throwable {
		Float float0 = new Float((-3414.36F));
		Compteur compteur0 = new Compteur("", "", "ts:oCOrf[L", "ts:oCOrf[L", (LocalDate) null, float0);
		assertEquals("ts:oCOrf[L", compteur0.getTypeCompteur());

		compteur0.setTypeCompteur("");
		assertEquals("", compteur0.getIdBat());
	}

	@Test(timeout = 4000)
	public void test28() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Compteur compteur0 = new Compteur((String) null, (String) null, (String) null, (String) null, localDate0,
				(Float) null);
		String string0 = compteur0.toString();
		assertEquals("Compteur [bat=null, bien=null, typeCompteur=null, idCompteur=null]", string0);
	}

	@Test(timeout = 4000)
	public void test29() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Compteur compteur0 = new Compteur(";dele.Cmptvr", ";dele.Cmptvr", ";dele.Cmptvr", ";dele.Cmptvr", localDate0,
				(Float) null);
		LocalDate localDate1 = compteur0.getDateInstallation();
		assertSame(localDate0, localDate1);
	}

	@Test(timeout = 4000)
	public void test30() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Compteur compteur0 = new Compteur((String) null, (String) null, (String) null, (String) null, localDate0,
				(Float) null);
		compteur0.hashCode();
	}

	@Test(timeout = 4000)
	public void test31() throws Throwable {
		Clock clock0 = MockClock.systemUTC();
		LocalDate localDate0 = MockLocalDate.now(clock0);
		Float float0 = new Float(1.0F);
		Compteur compteur0 = new Compteur("z!", "z!", "z!", "z!", localDate0, float0);
		compteur0.setDateInstallation(localDate0);
		assertEquals("z!", compteur0.getIdCompteur());
	}
}
