/*
 * This file was automatically generated by EvoSuite
 * Fri Jan 16 13:43:19 GMT 2026
 */

package test.modele;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertNull;
import static org.junit.Assert.assertSame;
import static org.junit.Assert.assertTrue;

import java.time.LocalDate;
import java.time.Month;
import java.time.Period;
import java.time.ZoneId;
import java.time.ZoneOffset;
import java.time.chrono.IsoChronology;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.time.MockLocalDate;
import org.evosuite.runtime.mock.java.time.chrono.MockIsoChronology;
import org.junit.Test;
import org.junit.runner.RunWith;

import modele.Diagnostic;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class Diagnostic_ESTest extends Diagnostic_ESTest_scaffolding {

	@Test(timeout = 4000)
	public void test00() throws Throwable {
		LocalDate localDate0 = MockLocalDate.ofEpochDay(223L);
		Diagnostic diagnostic0 = new Diagnostic("ulL0D", localDate0, localDate0, "ulL0D", (String) null);
		diagnostic0.setLibelle((String) null);
		String string0 = diagnostic0.getLibelle();
		assertNull(string0);
	}

	@Test(timeout = 4000)
	public void test01() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Diagnostic diagnostic0 = new Diagnostic("F}x", localDate0, localDate0, (String) null, (String) null);
		diagnostic0.setLibelle("");
		String string0 = diagnostic0.getLibelle();
		assertEquals("", string0);
	}

	@Test(timeout = 4000)
	public void test02() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Diagnostic diagnostic0 = new Diagnostic("F}x", localDate0, localDate0, (String) null, (String) null);
		String string0 = diagnostic0.getIdBien();
		assertNull(string0);
	}

	@Test(timeout = 4000)
	public void test03() throws Throwable {
		Diagnostic diagnostic0 = new Diagnostic("", (LocalDate) null, (LocalDate) null, (String) null, "+Zwz<JQxff");
		String string0 = diagnostic0.getIdBien();
		assertNotNull(string0);
		assertEquals("+Zwz<JQxff", string0);
		assertEquals("", diagnostic0.getLibelle());
	}

	@Test(timeout = 4000)
	public void test04() throws Throwable {
		Diagnostic diagnostic0 = new Diagnostic((String) null, (LocalDate) null, (LocalDate) null, (String) null,
				(String) null);
		String string0 = diagnostic0.getDetails();
		assertNull(string0);
	}

	@Test(timeout = 4000)
	public void test05() throws Throwable {
		Diagnostic diagnostic0 = new Diagnostic("", (LocalDate) null, (LocalDate) null, "", "HdeB");
		String string0 = diagnostic0.getDetails();
		assertEquals("", diagnostic0.getLibelle());
		assertEquals("", string0);
		assertEquals("HdeB", diagnostic0.getIdBien());
	}

	@Test(timeout = 4000)
	public void test06() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Diagnostic diagnostic0 = new Diagnostic("F}x", localDate0, localDate0, (String) null, (String) null);
		LocalDate localDate1 = diagnostic0.getDateFin();
		assertSame(localDate1, localDate0);
	}

	@Test(timeout = 4000)
	public void test07() throws Throwable {
		Period period0 = Period.ofYears(1);
		IsoChronology isoChronology0 = period0.getChronology();
		ZoneOffset zoneOffset0 = ZoneOffset.ofHoursMinutes(1, 1);
		LocalDate localDate0 = MockIsoChronology.dateNow(isoChronology0, (ZoneId) zoneOffset0);
		Diagnostic diagnostic0 = new Diagnostic("", localDate0, localDate0, "", "HdeB");
		diagnostic0.getDateDebut();
		assertEquals("", diagnostic0.getDetails());
		assertEquals("HdeB", diagnostic0.getIdBien());
		assertEquals("", diagnostic0.getLibelle());
	}

	@Test(timeout = 4000)
	public void test08() throws Throwable {
		Diagnostic diagnostic0 = new Diagnostic("", (LocalDate) null, (LocalDate) null, "", "");
		Diagnostic diagnostic1 = new Diagnostic("", (LocalDate) null, (LocalDate) null, (String) null,
				"BsB{2OiTO\u0005J0Hzh6B");
		boolean boolean0 = diagnostic0.equals(diagnostic1);
		assertEquals("BsB{2OiTO\u0005J0Hzh6B", diagnostic1.getIdBien());
		assertTrue(boolean0);
	}

	@Test(timeout = 4000)
	public void test09() throws Throwable {
		LocalDate localDate0 = MockLocalDate.ofEpochDay((-4510L));
		Diagnostic diagnostic0 = new Diagnostic("B#6", (LocalDate) null, localDate0, "B#6", "B#6");
		Diagnostic diagnostic1 = new Diagnostic("B#6", localDate0, localDate0, "B#6", "B#6");
		boolean boolean0 = diagnostic0.equals(diagnostic1);
		assertFalse(boolean0);
	}

	@Test(timeout = 4000)
	public void test10() throws Throwable {
		Diagnostic diagnostic0 = new Diagnostic("", (LocalDate) null, (LocalDate) null, "", "");
		boolean boolean0 = diagnostic0.equals("");
		assertFalse(boolean0);
	}

	@Test(timeout = 4000)
	public void test11() throws Throwable {
		Diagnostic diagnostic0 = new Diagnostic("C", (LocalDate) null, (LocalDate) null, "C", "C");
		boolean boolean0 = diagnostic0.equals((Object) null);
		assertFalse(boolean0);
	}

	@Test(timeout = 4000)
	public void test12() throws Throwable {
		Diagnostic diagnostic0 = new Diagnostic("Dianotics7libel3=", (LocalDate) null, (LocalDate) null,
				"Dianotics7libel3=", "Dianotics7libel3=");
		boolean boolean0 = diagnostic0.equals(diagnostic0);
		assertTrue(boolean0);
	}

	@Test(timeout = 4000)
	public void test13() throws Throwable {
		Diagnostic diagnostic0 = new Diagnostic("", (LocalDate) null, (LocalDate) null, "", "");
		Diagnostic diagnostic1 = new Diagnostic("LWKJK!RC$/`voW_w", (LocalDate) null, (LocalDate) null, "", ")dPbL[");
		boolean boolean0 = diagnostic0.equals(diagnostic1);
		assertEquals("", diagnostic1.getDetails());
		assertEquals(")dPbL[", diagnostic1.getIdBien());
		assertEquals("LWKJK!RC$/`voW_w", diagnostic1.getLibelle());
		assertFalse(boolean0);
	}

	@Test(timeout = 4000)
	public void test14() throws Throwable {
		Diagnostic diagnostic0 = new Diagnostic("rhHsv^`D-p*K$.@14", (LocalDate) null, (LocalDate) null,
				"rhHsv^`D-p*K$.@14", "rhHsv^`D-p*K$.@14");
		LocalDate localDate0 = diagnostic0.getDateFin();
		assertNull(localDate0);
	}

	@Test(timeout = 4000)
	public void test15() throws Throwable {
		Month month0 = Month.JANUARY;
		LocalDate localDate0 = MockLocalDate.of((-2686), month0, 1);
		Diagnostic diagnostic0 = new Diagnostic("", localDate0, localDate0, "", "");
		String string0 = diagnostic0.getIdBien();
		assertEquals("", string0);
	}

	@Test(timeout = 4000)
	public void test16() throws Throwable {
		Diagnostic diagnostic0 = new Diagnostic("C", (LocalDate) null, (LocalDate) null, "C", "C");
		diagnostic0.setDateDebut((LocalDate) null);
		assertEquals("C", diagnostic0.getDetails());
	}

	@Test(timeout = 4000)
	public void test17() throws Throwable {
		Diagnostic diagnostic0 = new Diagnostic("W", (LocalDate) null, (LocalDate) null, "W", "W");
		LocalDate localDate0 = diagnostic0.getDateDebut();
		assertNull(localDate0);
	}

	@Test(timeout = 4000)
	public void test18() throws Throwable {
		Diagnostic diagnostic0 = new Diagnostic("", (LocalDate) null, (LocalDate) null, "", "");
		diagnostic0.setIdBien("\"p-\"");
		assertEquals("", diagnostic0.getLibelle());
	}

	@Test(timeout = 4000)
	public void test19() throws Throwable {
		Diagnostic diagnostic0 = new Diagnostic("", (LocalDate) null, (LocalDate) null, "", "");
		diagnostic0.setDetails("BsB{2OiTO\u0005J0Hzh6B");
		assertEquals("", diagnostic0.getIdBien());
	}

	@Test(timeout = 4000)
	public void test20() throws Throwable {
		Diagnostic diagnostic0 = new Diagnostic("O9M&i-", (LocalDate) null, (LocalDate) null, "O9M&i-", "O9M&i-");
		diagnostic0.setDateFin((LocalDate) null);
		assertEquals("O9M&i-", diagnostic0.getIdBien());
	}

	@Test(timeout = 4000)
	public void test21() throws Throwable {
		Diagnostic diagnostic0 = new Diagnostic("C", (LocalDate) null, (LocalDate) null, "C", "C");
		diagnostic0.hashCode();
	}

	@Test(timeout = 4000)
	public void test22() throws Throwable {
		Diagnostic diagnostic0 = new Diagnostic("29ki-", (LocalDate) null, (LocalDate) null, "29ki-", "29ki-");
		String string0 = diagnostic0.getDetails();
		assertEquals("29ki-", string0);
	}

	@Test(timeout = 4000)
	public void test23() throws Throwable {
		Diagnostic diagnostic0 = new Diagnostic("rhHsv^`D-p*K$.@14", (LocalDate) null, (LocalDate) null,
				"rhHsv^`D-p*K$.@14", "rhHsv^`D-p*K$.@14");
		String string0 = diagnostic0.toString();
		assertNotNull(string0);
	}

	@Test(timeout = 4000)
	public void test24() throws Throwable {
		Diagnostic diagnostic0 = new Diagnostic("C", (LocalDate) null, (LocalDate) null, "C", "C");
		String string0 = diagnostic0.getLibelle();
		assertEquals("C", string0);
	}
}
