/*
 * This file was automatically generated by EvoSuite
 * Fri Jan 16 13:52:47 GMT 2026
 */

package test.modele;

import static org.evosuite.runtime.EvoAssertions.verifyException;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertNull;
import static org.junit.Assert.assertTrue;
import static org.junit.Assert.fail;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;

import modele.Garant;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class Garant_ESTest extends Garant_ESTest_scaffolding {

	@Test(timeout = 4000)
	public void test00() throws Throwable {
		Garant garant0 = new Garant("", (String) null, "", "");
		try {
			garant0.setTel("\"8F(zH&*(n=Q>");
			fail("Expecting exception: IllegalArgumentException");

		} catch (IllegalArgumentException e) {
			//
			// Le num\u00E9ro de t\u00E9l\u00E9phone n'est pas de la bonne longueur !
			//
			verifyException("modele.Garant", e);
		}
	}

	@Test(timeout = 4000)
	public void test01() throws Throwable {
		Garant garant0 = new Garant("2t8;", "o", "", (String) null);
		String string0 = garant0.getTel();
		assertEquals("", garant0.getMail());
		assertEquals("o", garant0.getAdresse());
		assertNull(string0);
		assertEquals("2t8;", garant0.getIdGarant());
	}

	@Test(timeout = 4000)
	public void test02() throws Throwable {
		Garant garant0 = new Garant((String) null, "", "P]xjR", "P]xjR");
		String string0 = garant0.getTel();
		assertEquals("P]xjR", string0);
		assertNotNull(string0);
		assertEquals("P]xjR", garant0.getMail());
		assertEquals("", garant0.getAdresse());
	}

	@Test(timeout = 4000)
	public void test03() throws Throwable {
		Garant garant0 = new Garant("'5W*Nz~_CC&3\"a", "m,G6O.m|QV_", "m,G6O.m|QV_", "m,G6O.m|QV_");
		String string0 = garant0.getMail();
		assertEquals("m,G6O.m|QV_", garant0.getAdresse());
		assertEquals("m,G6O.m|QV_", string0);
		assertEquals("m,G6O.m|QV_", garant0.getTel());
		assertEquals("'5W*Nz~_CC&3\"a", garant0.getIdGarant());
	}

	@Test(timeout = 4000)
	public void test04() throws Throwable {
		Garant garant0 = new Garant("", (String) null, "", "");
		String string0 = garant0.getMail();
		assertEquals("", string0);
	}

	@Test(timeout = 4000)
	public void test05() throws Throwable {
		Garant garant0 = new Garant((String) null, (String) null, "<<\"D[+<", "o6psqgTWn2[I/NYQ");
		String string0 = garant0.getIdGarant();
		assertEquals("<<\"D[+<", garant0.getMail());
		assertNull(string0);
		assertEquals("o6psqgTWn2[I/NYQ", garant0.getTel());
	}

	@Test(timeout = 4000)
	public void test06() throws Throwable {
		Garant garant0 = new Garant("", (String) null, "", "");
		String string0 = garant0.getIdGarant();
		assertEquals("", string0);
	}

	@Test(timeout = 4000)
	public void test07() throws Throwable {
		Garant garant0 = new Garant("", (String) null, "", "");
		String string0 = garant0.getAdresse();
		assertNull(string0);
	}

	@Test(timeout = 4000)
	public void test08() throws Throwable {
		Garant garant0 = new Garant("", "Le num\u00E9ro de t\u00E9l\u00E9phone n'est pas de la bonne longueur !", "",
				(String) null);
		String string0 = garant0.getAdresse();
		assertEquals("Le num\u00E9ro de t\u00E9l\u00E9phone n'est pas de la bonne longueur !", string0);
		assertEquals("", garant0.getMail());
		assertNotNull(string0);
		assertEquals("", garant0.getIdGarant());
	}

	@Test(timeout = 4000)
	public void test09() throws Throwable {
		Garant garant0 = new Garant((String) null, (String) null, (String) null, (String) null);
		// Undeclared exception!
		try {
			garant0.setTel((String) null);
			fail("Expecting exception: NullPointerException");

		} catch (NullPointerException e) {
			//
			// no message in exception (getMessage() returned null)
			//
			verifyException("modele.Garant", e);
		}
	}

	@Test(timeout = 4000)
	public void test10() throws Throwable {
		Garant garant0 = new Garant((String) null, (String) null, (String) null, (String) null);
		// Undeclared exception!
		try {
			garant0.setMail((String) null);
			fail("Expecting exception: NullPointerException");

		} catch (NullPointerException e) {
			//
			// no message in exception (getMessage() returned null)
			//
			verifyException("modele.Garant", e);
		}
	}

	@Test(timeout = 4000)
	public void test11() throws Throwable {
		Garant garant0 = new Garant("0", "8K;du-njPzS\"8g;w", "8K;du-njPzS\"8g;w", "");
		Object object0 = new Object();
		boolean boolean0 = garant0.equals(object0);
		assertEquals("0", garant0.getIdGarant());
		assertFalse(boolean0);
		assertEquals("8K;du-njPzS\"8g;w", garant0.getAdresse());
		assertEquals("", garant0.getTel());
		assertEquals("8K;du-njPzS\"8g;w", garant0.getMail());
	}

	@Test(timeout = 4000)
	public void test12() throws Throwable {
		Garant garant0 = new Garant("Qswpf>baD ", "T.gFF:ma", (String) null, " ;bDHcT");
		boolean boolean0 = garant0.equals((Object) null);
		assertFalse(boolean0);
		assertEquals(" ;bDHcT", garant0.getTel());
		assertEquals("T.gFF:ma", garant0.getAdresse());
		assertEquals("Qswpf>baD ", garant0.getIdGarant());
	}

	@Test(timeout = 4000)
	public void test13() throws Throwable {
		Garant garant0 = new Garant("V4[T|[Vm^:Q17B!", (String) null, (String) null, "");
		boolean boolean0 = garant0.equals(garant0);
		assertEquals("V4[T|[Vm^:Q17B!", garant0.getIdGarant());
		assertTrue(boolean0);
		assertEquals("", garant0.getTel());
	}

	@Test(timeout = 4000)
	public void test14() throws Throwable {
		Garant garant0 = new Garant("", "", ",1'Y</DfN", (String) null);
		Garant garant1 = new Garant("", "[tlJp!(Xf ", ",1'Y</DfN", "$DL?");
		boolean boolean0 = garant0.equals(garant1);
		assertEquals("$DL?", garant1.getTel());
		assertEquals("", garant1.getIdGarant());
		assertTrue(boolean0);
		assertEquals(",1'Y</DfN", garant1.getMail());
		assertEquals("[tlJp!(Xf ", garant1.getAdresse());
	}

	@Test(timeout = 4000)
	public void test15() throws Throwable {
		Garant garant0 = new Garant("", "", "", "");
		try {
			garant0.setTel("");
			fail("Expecting exception: IllegalArgumentException");

		} catch (IllegalArgumentException e) {
			//
			// Le num\u00E9ro de t\u00E9l\u00E9phone n'est pas de la bonne longueur !
			//
			verifyException("modele.Garant", e);
		}
	}

	@Test(timeout = 4000)
	public void test16() throws Throwable {
		Garant garant0 = new Garant("", "", ",1'Y</DfN", (String) null);
		garant0.setTel("[tlJp!(Xf ");
		assertEquals("", garant0.getIdGarant());
		assertEquals("", garant0.getAdresse());
		assertEquals(",1'Y</DfN", garant0.getMail());
	}

	@Test(timeout = 4000)
	public void test17() throws Throwable {
		Garant garant0 = new Garant(".com", ".com", ".com", ".com");
		try {
			garant0.setMail(".com");
			fail("Expecting exception: IllegalArgumentException");

		} catch (IllegalArgumentException e) {
			//
			// Le mail n'est donc pas valable
			//
			verifyException("modele.Garant", e);
		}
	}

	@Test(timeout = 4000)
	public void test18() throws Throwable {
		Garant garant0 = new Garant("Z:k}", "Z:k}", "Z:k}", "Z:k}");
		try {
			garant0.setMail("Z:k}");
			fail("Expecting exception: IllegalArgumentException");

		} catch (IllegalArgumentException e) {
			//
			// Le mail n'est donc pas valable
			//
			verifyException("modele.Garant", e);
		}
	}

	@Test(timeout = 4000)
	public void test19() throws Throwable {
		Garant garant0 = new Garant("A.com", ".fr", "A.com", "1qg+");
		assertEquals("A.com", garant0.getMail());

		garant0.setMail("Garant [id_Garant=A.com, adresse=.fr, mail=A.com, tel=1qg+]");
		assertEquals("1qg+", garant0.getTel());
	}

	@Test(timeout = 4000)
	public void test20() throws Throwable {
		Garant garant0 = new Garant("0", "8K;du-njPzS\"8g;w", "8K;du-njPzS\"8g;w", "");
		assertEquals("8K;du-njPzS\"8g;w", garant0.getMail());

		garant0.setMail("@");
		assertEquals("0", garant0.getIdGarant());
	}

	@Test(timeout = 4000)
	public void test21() throws Throwable {
		Garant garant0 = new Garant("0", "8K;du-njPzS\"8g;w", "8K;du-njPzS\"8g;w", "");
		String string0 = garant0.getIdGarant();
		assertEquals("8K;du-njPzS\"8g;w", garant0.getAdresse());
		assertEquals("", garant0.getTel());
		assertEquals("8K;du-njPzS\"8g;w", garant0.getMail());
		assertEquals("0", string0);
	}

	@Test(timeout = 4000)
	public void test22() throws Throwable {
		Garant garant0 = new Garant("A.com", ".fr", "A.com", "1qg+");
		String string0 = garant0.toString();
		assertEquals("Garant [id_Garant=A.com, adresse=.fr, mail=A.com, tel=1qg+]", string0);
	}

	@Test(timeout = 4000)
	public void test23() throws Throwable {
		Garant garant0 = new Garant("0", "8K;du-njPzS\"8g;w", "8K;du-njPzS\"8g;w", "");
		String string0 = garant0.getTel();
		assertEquals("0", garant0.getIdGarant());
		assertEquals("8K;du-njPzS\"8g;w", garant0.getMail());
		assertEquals("8K;du-njPzS\"8g;w", garant0.getAdresse());
		assertEquals("", string0);
	}

	@Test(timeout = 4000)
	public void test24() throws Throwable {
		Garant garant0 = new Garant("N%", "N%", "N%", "N%");
		garant0.setAdresse("N%");
		assertEquals("N%", garant0.getMail());
	}

	@Test(timeout = 4000)
	public void test25() throws Throwable {
		Garant garant0 = new Garant("", "", "8K;du-njPzS\"8g;w", "8K;du-njPzS\"8g;w");
		String string0 = garant0.getAdresse();
		assertEquals("", garant0.getIdGarant());
		assertEquals("8K;du-njPzS\"8g;w", garant0.getTel());
		assertEquals("", string0);
		assertEquals("8K;du-njPzS\"8g;w", garant0.getMail());
	}

	@Test(timeout = 4000)
	public void test26() throws Throwable {
		Garant garant0 = new Garant("@", "@", "@", "@");
		garant0.setIdGarant("@");
		assertEquals("@", garant0.getTel());
	}

	@Test(timeout = 4000)
	public void test27() throws Throwable {
		Garant garant0 = new Garant("Z:k}", "Z:k}", "Z:k}", "Z:k}");
		garant0.hashCode();
	}

	@Test(timeout = 4000)
	public void test28() throws Throwable {
		Garant garant0 = new Garant("", "&", (String) null, " ");
		String string0 = garant0.getMail();
		assertEquals("&", garant0.getAdresse());
		assertEquals(" ", garant0.getTel());
		assertEquals("", garant0.getIdGarant());
		assertNull(string0);
	}
}
