/*
 * This file was automatically generated by EvoSuite
 * Fri Jan 16 13:53:56 GMT 2026
 */

package test.modele;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNull;
import static org.junit.Assert.assertSame;

import java.time.Instant;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.time.ZoneOffset;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.time.MockInstant;
import org.evosuite.runtime.mock.java.time.MockLocalDateTime;
import org.junit.Test;
import org.junit.runner.RunWith;

import modele.Historique;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class Historique_ESTest extends Historique_ESTest_scaffolding {

	@Test(timeout = 4000)
	public void test0() throws Throwable {
		Instant instant0 = MockInstant.ofEpochSecond(0L);
		ZoneOffset zoneOffset0 = ZoneOffset.UTC;
		LocalDateTime localDateTime0 = MockLocalDateTime.ofInstant(instant0, zoneOffset0);
		Historique historique0 = new Historique(localDateTime0, (String) null, (String) null);
		String string0 = historique0.getDetails();
		assertNull(string0);
	}

	@Test(timeout = 4000)
	public void test1() throws Throwable {
		Historique historique0 = new Historique((LocalDateTime) null, "pGbNAFwk~", "]\"p:]XT1c");
		assertEquals("]\"p:]XT1c", historique0.getDetails());

		historique0.setDetails("");
		historique0.getDetails();
		assertEquals("pGbNAFwk~", historique0.getAction());
	}

	@Test(timeout = 4000)
	public void test2() throws Throwable {
		ZoneId zoneId0 = ZoneId.systemDefault();
		LocalDateTime localDateTime0 = MockLocalDateTime.now(zoneId0);
		Historique historique0 = new Historique(localDateTime0, "", "");
		LocalDateTime localDateTime1 = historique0.getDate();
		assertSame(localDateTime1, localDateTime0);
	}

	@Test(timeout = 4000)
	public void test3() throws Throwable {
		Historique historique0 = new Historique((LocalDateTime) null, "modele.Historique", "pcHmC6{lfE[rq`M(H");
		assertEquals("modele.Historique", historique0.getAction());

		historique0.setAction((String) null);
		historique0.getAction();
		assertEquals("pcHmC6{lfE[rq`M(H", historique0.getDetails());
	}

	@Test(timeout = 4000)
	public void test4() throws Throwable {
		Historique historique0 = new Historique((LocalDateTime) null, "modele.Historique", "pcHmC6{lfE[rq`M(H");
		String string0 = historique0.getDetails();
		assertEquals("pcHmC6{lfE[rq`M(H", string0);
		assertEquals("modele.Historique", historique0.getAction());
	}

	@Test(timeout = 4000)
	public void test5() throws Throwable {
		Historique historique0 = new Historique((LocalDateTime) null, "modele.Historique", "pcHmC6{lfE[rq`M(H");
		assertEquals("modele.Historique", historique0.getAction());

		historique0.setAction("");
		historique0.getAction();
		assertEquals("pcHmC6{lfE[rq`M(H", historique0.getDetails());
	}

	@Test(timeout = 4000)
	public void test6() throws Throwable {
		Historique historique0 = new Historique((LocalDateTime) null, "modele.Historique", "pcHmC6{lfE[rq`M(H");
		String string0 = historique0.getAction();
		assertEquals("pcHmC6{lfE[rq`M(H", historique0.getDetails());
		assertEquals("modele.Historique", string0);
	}

	@Test(timeout = 4000)
	public void test7() throws Throwable {
		Historique historique0 = new Historique((LocalDateTime) null, "modele.Historique", "pcHmC6{lfE[rq`M(H");
		historique0.getDate();
		assertEquals("modele.Historique", historique0.getAction());
		assertEquals("pcHmC6{lfE[rq`M(H", historique0.getDetails());
	}

	@Test(timeout = 4000)
	public void test8() throws Throwable {
		Historique historique0 = new Historique((LocalDateTime) null, "modele.Historique", "pcHmC6{lfE[rq`M(H");
		historique0.setDate((LocalDateTime) null);
		assertEquals("pcHmC6{lfE[rq`M(H", historique0.getDetails());
		assertEquals("modele.Historique", historique0.getAction());
	}
}
