/*
 * This file was automatically generated by EvoSuite
 * Fri Jan 16 13:57:40 GMT 2026
 */

package test.modele;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNull;
import static org.junit.Assert.assertSame;

import java.time.Clock;
import java.time.LocalDate;
import java.time.Period;
import java.time.ZoneId;
import java.time.ZoneOffset;
import java.time.chrono.IsoChronology;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.time.MockClock;
import org.evosuite.runtime.mock.java.time.MockLocalDate;
import org.evosuite.runtime.mock.java.time.chrono.MockIsoChronology;
import org.junit.Test;
import org.junit.runner.RunWith;

import modele.HistoriqueLoyer;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class HistoriqueLoyer_ESTest extends HistoriqueLoyer_ESTest_scaffolding {

	@Test(timeout = 4000)
	public void test00() throws Throwable {
		Float float0 = new Float(3542.381838);
		Float float1 = new Float(0.0);
		LocalDate localDate0 = MockLocalDate.ofEpochDay(5588L);
		HistoriqueLoyer historiqueLoyer0 = new HistoriqueLoyer(float0, float1, "`m", localDate0);
		Float float2 = historiqueLoyer0.getProvision();
		assertEquals(3542.3818F, historiqueLoyer0.getLoyer(), 0.01F);
		assertEquals(0.0F, (float) float2, 0.01F);
	}

	@Test(timeout = 4000)
	public void test01() throws Throwable {
		Float float0 = new Float(3542.381838);
		LocalDate localDate0 = MockLocalDate.ofEpochDay(5588L);
		HistoriqueLoyer historiqueLoyer0 = new HistoriqueLoyer(float0, float0, "`m", localDate0);
		Float float1 = historiqueLoyer0.getProvision();
		assertEquals(3542.3818F, (float) float1, 0.01F);
	}

	@Test(timeout = 4000)
	public void test02() throws Throwable {
		Float float0 = new Float(1429.852);
		HistoriqueLoyer historiqueLoyer0 = new HistoriqueLoyer(float0, float0, "{hra#X+kPp0x", (LocalDate) null);
		LocalDate localDate0 = historiqueLoyer0.getMoisConcerne();
		assertNull(localDate0);
	}

	@Test(timeout = 4000)
	public void test03() throws Throwable {
		Float float0 = new Float(3932.222717);
		ZoneId zoneId0 = ZoneId.systemDefault();
		Clock clock0 = MockClock.system(zoneId0);
		LocalDate localDate0 = MockLocalDate.now(clock0);
		HistoriqueLoyer historiqueLoyer0 = new HistoriqueLoyer(float0, float0, "", localDate0);
		Float float1 = new Float((float) 0L);
		historiqueLoyer0.setLoyer(float1);
		Float float2 = historiqueLoyer0.getLoyer();
		assertEquals(0.0F, (float) float2, 0.01F);
	}

	@Test(timeout = 4000)
	public void test04() throws Throwable {
		Float float0 = new Float(3542.381838);
		LocalDate localDate0 = MockLocalDate.ofEpochDay(5588L);
		HistoriqueLoyer historiqueLoyer0 = new HistoriqueLoyer(float0, float0, "`m", localDate0);
		Float float1 = historiqueLoyer0.getLoyer();
		assertEquals(3542.3818F, (float) float1, 0.01F);
	}

	@Test(timeout = 4000)
	public void test05() throws Throwable {
		Float float0 = new Float((-779.67395F));
		LocalDate localDate0 = MockLocalDate.ofEpochDay(0L);
		HistoriqueLoyer historiqueLoyer0 = new HistoriqueLoyer(float0, float0, "modele.HistoriqueLoyer", localDate0);
		Float float1 = historiqueLoyer0.getLoyer();
		assertEquals((-779.67395F), (float) float1, 0.01F);
	}

	@Test(timeout = 4000)
	public void test06() throws Throwable {
		Float float0 = new Float((float) (-2069L));
		HistoriqueLoyer historiqueLoyer0 = new HistoriqueLoyer(float0, float0, (String) null, (LocalDate) null);
		String string0 = historiqueLoyer0.getIdBien();
		assertNull(string0);
	}

	@Test(timeout = 4000)
	public void test07() throws Throwable {
		Float float0 = new Float(1429.852);
		HistoriqueLoyer historiqueLoyer0 = new HistoriqueLoyer(float0, float0, "{hra#X+kPp0x", (LocalDate) null);
		String string0 = historiqueLoyer0.getIdBien();
		assertEquals("{hra#X+kPp0x", string0);
	}

	@Test(timeout = 4000)
	public void test08() throws Throwable {
		Float float0 = new Float(3542.381838);
		LocalDate localDate0 = MockLocalDate.ofEpochDay(5588L);
		HistoriqueLoyer historiqueLoyer0 = new HistoriqueLoyer(float0, float0, "`m", localDate0);
		historiqueLoyer0.setMoisConcerne(localDate0);
		assertEquals(3542.3818F, historiqueLoyer0.getLoyer(), 0.01F);
	}

	@Test(timeout = 4000)
	public void test09() throws Throwable {
		Float float0 = new Float(3932.222717);
		ZoneId zoneId0 = ZoneId.systemDefault();
		Clock clock0 = MockClock.system(zoneId0);
		LocalDate localDate0 = MockLocalDate.now(clock0);
		HistoriqueLoyer historiqueLoyer0 = new HistoriqueLoyer(float0, float0, "", localDate0);
		String string0 = historiqueLoyer0.getIdBien();
		assertEquals("", string0);
	}

	@Test(timeout = 4000)
	public void test10() throws Throwable {
		Float float0 = new Float(3932.222717);
		ZoneId zoneId0 = ZoneId.systemDefault();
		Clock clock0 = MockClock.system(zoneId0);
		LocalDate localDate0 = MockLocalDate.now(clock0);
		HistoriqueLoyer historiqueLoyer0 = new HistoriqueLoyer(float0, float0, "", localDate0);
		historiqueLoyer0.setProvision((Float) null);
		Float float1 = historiqueLoyer0.getProvision();
		assertNull(float1);
	}

	@Test(timeout = 4000)
	public void test11() throws Throwable {
		Float float0 = new Float(3932.222717);
		ZoneId zoneId0 = ZoneId.systemDefault();
		Clock clock0 = MockClock.system(zoneId0);
		LocalDate localDate0 = MockLocalDate.now(clock0);
		HistoriqueLoyer historiqueLoyer0 = new HistoriqueLoyer(float0, float0, "", localDate0);
		LocalDate localDate1 = historiqueLoyer0.getMoisConcerne();
		assertSame(localDate1, localDate0);
	}

	@Test(timeout = 4000)
	public void test12() throws Throwable {
		Float float0 = new Float(3542.381838);
		LocalDate localDate0 = MockLocalDate.ofEpochDay(5588L);
		HistoriqueLoyer historiqueLoyer0 = new HistoriqueLoyer(float0, float0, "`m", localDate0);
		historiqueLoyer0.setIdBien("");
		assertEquals(3542.3818F, historiqueLoyer0.getLoyer(), 0.01F);
	}

	@Test(timeout = 4000)
	public void test13() throws Throwable {
		Period period0 = Period.ZERO;
		IsoChronology isoChronology0 = period0.getChronology();
		LocalDate localDate0 = MockIsoChronology.dateNow(isoChronology0);
		HistoriqueLoyer historiqueLoyer0 = new HistoriqueLoyer((Float) null, (Float) null, "zWQp{", localDate0);
		Float float0 = historiqueLoyer0.getLoyer();
		assertNull(float0);
	}

	@Test(timeout = 4000)
	public void test14() throws Throwable {
		Float float0 = new Float((-1.0F));
		ZoneOffset zoneOffset0 = ZoneOffset.ofHoursMinutesSeconds((-1), (-1), (-1));
		Clock clock0 = MockClock.tickMinutes(zoneOffset0);
		LocalDate localDate0 = MockLocalDate.now(clock0);
		HistoriqueLoyer historiqueLoyer0 = new HistoriqueLoyer(float0, float0, "R/-g`a[N[p6w[Q}", localDate0);
		Float float1 = historiqueLoyer0.getProvision();
		assertEquals((-1.0F), (float) float1, 0.01F);
	}
}
