/*
 * This file was automatically generated by EvoSuite
 * Fri Jan 16 14:00:37 GMT 2026
 */

package test.modele;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertNull;
import static org.junit.Assert.assertTrue;

import java.time.LocalDate;
import java.time.Month;
import java.time.Period;
import java.time.chrono.IsoChronology;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.time.MockLocalDate;
import org.evosuite.runtime.mock.java.time.chrono.MockIsoChronology;
import org.junit.Test;
import org.junit.runner.RunWith;

import modele.Intervention;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class Intervention_ESTest extends Intervention_ESTest_scaffolding {

	@Test(timeout = 4000)
	public void test00() throws Throwable {
		Float float0 = new Float(617.0F);
		Float float1 = new Float((float) 0);
		Intervention intervention0 = new Intervention(";aBs&b=Q/u9!%u|V", "sVcSTFV12%5M@Y{n*", (LocalDate) null, "",
				(LocalDate) null, float0, (LocalDate) null, float1, "?Fuc|U1jr", float1, float1, float1,
				", numFacture=", "?Fuc|U1jr", 1052, 0);
		Float float2 = intervention0.getReduction();
		assertEquals(0.0F, intervention0.getAcompteFacture(), 0.01F);
		assertEquals(0.0F, (float) float2, 0.01F);
		assertEquals("?Fuc|U1jr", intervention0.getNumDevis());
		assertEquals("", intervention0.getNumFacture());
		assertEquals(0, intervention0.getOrdures());
		assertEquals(0.0F, intervention0.getMontantNonDeductible(), 0.01F);
		assertEquals(0.0F, intervention0.getMontantDevis(), 0.01F);
		assertEquals("sVcSTFV12%5M@Y{n*", intervention0.getIntitule());
		assertEquals(1052, intervention0.getEntretienPc());
		assertEquals(";aBs&b=Q/u9!%u|V", intervention0.getIdIntervention());
		assertEquals(617.0F, intervention0.getMontantFacture(), 0.01F);
		assertEquals("?Fuc|U1jr", intervention0.getIdBatiment());
		assertEquals(", numFacture=", intervention0.getIdOrganisme());
	}

	@Test(timeout = 4000)
	public void test01() throws Throwable {
		Float float0 = new Float(617.0F);
		Intervention intervention0 = new Intervention("", "*", (LocalDate) null, "", (LocalDate) null, (Float) null,
				(LocalDate) null, float0, "", float0, float0, float0, "sVcSTFV12%5M@Y{n*", "^q'^Syq-*V\"T5T)*", (-2551),
				(-2551));
		Float float1 = intervention0.getReduction();
		assertEquals((-2551), intervention0.getEntretienPc());
		assertEquals("*", intervention0.getIntitule());
		assertEquals("", intervention0.getNumDevis());
		assertEquals((-2551), intervention0.getOrdures());
		assertEquals("sVcSTFV12%5M@Y{n*", intervention0.getIdOrganisme());
		assertEquals("", intervention0.getIdIntervention());
		assertEquals("^q'^Syq-*V\"T5T)*", intervention0.getIdBatiment());
		assertNotNull(float1);
		assertEquals("", intervention0.getNumFacture());
	}

	@Test(timeout = 4000)
	public void test02() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Float float0 = new Float(0.0);
		Float float1 = Float.valueOf((-3528.2F));
		Intervention intervention0 = new Intervention("", "", localDate0, "", localDate0, float0, localDate0, float0,
				"", float0, float1, float1, "", "", 0, 0);
		Float float2 = intervention0.getReduction();
		assertEquals(0.0F, intervention0.getAcompteFacture(), 0.01F);
		assertEquals((-3528.2F), intervention0.getMontantNonDeductible(), 0.01F);
		assertEquals(0, intervention0.getEntretienPc());
		assertEquals((-3528.2F), (float) float2, 0.01F);
		assertEquals(0.0F, intervention0.getMontantFacture(), 0.01F);
		assertEquals(0, intervention0.getOrdures());
		assertEquals(0.0F, intervention0.getMontantDevis(), 0.01F);
	}

	@Test(timeout = 4000)
	public void test03() throws Throwable {
		Float float0 = new Float(1.0);
		Intervention intervention0 = new Intervention(", idBatiment=", "S.^2,k", (LocalDate) null, ", idBatiment=",
				(LocalDate) null, float0, (LocalDate) null, float0, "", float0, float0, (Float) null, "", "S.^2,k", 0,
				1);
		int int0 = intervention0.getOrdures();
		assertEquals("S.^2,k", intervention0.getIdBatiment());
		assertEquals(0, intervention0.getEntretienPc());
		assertEquals(1, int0);
		assertEquals("", intervention0.getNumDevis());
		assertEquals(", idBatiment=", intervention0.getNumFacture());
		assertEquals(", idBatiment=", intervention0.getIdIntervention());
		assertEquals("S.^2,k", intervention0.getIntitule());
		assertEquals("", intervention0.getIdOrganisme());
	}

	@Test(timeout = 4000)
	public void test04() throws Throwable {
		Float float0 = new Float(617.0F);
		LocalDate localDate0 = MockLocalDate.ofEpochDay(0);
		Intervention intervention0 = new Intervention("9{po", "", (LocalDate) null, "", (LocalDate) null, float0,
				localDate0, float0, "Intervention [idIntervention=", (Float) null, float0, float0, "", "9{po", 0,
				(-1967));
		int int0 = intervention0.getOrdures();
		assertEquals("9{po", intervention0.getIdIntervention());
		assertEquals("", intervention0.getIdOrganisme());
		assertEquals(0, intervention0.getEntretienPc());
		assertEquals("Intervention [idIntervention=", intervention0.getNumDevis());
		assertEquals("", intervention0.getNumFacture());
		assertEquals("9{po", intervention0.getIdBatiment());
		assertEquals((-1967), int0);
		assertEquals("", intervention0.getIntitule());
	}

	@Test(timeout = 4000)
	public void test05() throws Throwable {
		Float float0 = new Float(617.0F);
		Intervention intervention0 = new Intervention(";aBs&b=Q/u9!%u|V", "sVcSTFV12%5MY{n*", (LocalDate) null,
				";aBs&b=Q/u9!%u|V", (LocalDate) null, float0, (LocalDate) null, float0, ";aBs&b=Q/u9!%u|V", float0,
				float0, float0, ";aBs&b=Q/u9!%u|V", ";aBs&b=Q/u9!%u|V", 0, 0);
		String string0 = intervention0.getNumFacture();
		assertEquals(";aBs&b=Q/u9!%u|V", intervention0.getIdOrganisme());
		assertEquals("sVcSTFV12%5MY{n*", intervention0.getIntitule());
		assertEquals(";aBs&b=Q/u9!%u|V", intervention0.getIdBatiment());
		assertEquals(";aBs&b=Q/u9!%u|V", string0);
		assertEquals(";aBs&b=Q/u9!%u|V", intervention0.getIdIntervention());
		assertEquals(0, intervention0.getEntretienPc());
		assertEquals(";aBs&b=Q/u9!%u|V", intervention0.getNumDevis());
		assertEquals(0, intervention0.getOrdures());
	}

	@Test(timeout = 4000)
	public void test06() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Float float0 = new Float((-1.0F));
		Intervention intervention0 = new Intervention("", "", localDate0, "", localDate0, (Float) null, localDate0,
				(Float) null, "", (Float) null, float0, (Float) null, "", ", montantFacture=", 3992, 1);
		String string0 = intervention0.getNumFacture();
		assertEquals(1, intervention0.getOrdures());
		assertEquals(", montantFacture=", intervention0.getIdBatiment());
		assertEquals(3992, intervention0.getEntretienPc());
		assertEquals("", string0);
		assertEquals("", intervention0.getIdIntervention());
		assertEquals("", intervention0.getIdOrganisme());
		assertEquals("", intervention0.getNumDevis());
		assertEquals("", intervention0.getIntitule());
	}

	@Test(timeout = 4000)
	public void test07() throws Throwable {
		LocalDate localDate0 = MockLocalDate.ofEpochDay(1508L);
		Float float0 = new Float((double) 1508L);
		Intervention intervention0 = new Intervention("A)apEHgC#`", "/1!S&", localDate0, "", (LocalDate) null, float0,
				(LocalDate) null, (Float) null, (String) null, float0, float0, float0, (String) null, (String) null, 0,
				0);
		String string0 = intervention0.getNumDevis();
		assertEquals("A)apEHgC#`", intervention0.getIdIntervention());
		assertEquals("/1!S&", intervention0.getIntitule());
		assertEquals(0, intervention0.getOrdures());
		assertNull(string0);
		assertEquals(0, intervention0.getEntretienPc());
		assertEquals("", intervention0.getNumFacture());
	}

	@Test(timeout = 4000)
	public void test08() throws Throwable {
		Float float0 = new Float(617.0F);
		Intervention intervention0 = new Intervention(";aBs=Q/9!%u|V", "sVcSTFV12%5M@Y{n*", (LocalDate) null,
				";aBs=Q/9!%u|V", (LocalDate) null, float0, (LocalDate) null, float0, "sVcSTFV12%5M@Y{n*", float0,
				float0, float0, ";aBs=Q/9!%u|V", "sVcSTFV12%5M@Y{n*", 0, 0);
		String string0 = intervention0.getNumDevis();
		assertEquals(";aBs=Q/9!%u|V", intervention0.getNumFacture());
		assertEquals("sVcSTFV12%5M@Y{n*", string0);
		assertEquals("sVcSTFV12%5M@Y{n*", intervention0.getIntitule());
		assertEquals(0, intervention0.getOrdures());
		assertEquals(";aBs=Q/9!%u|V", intervention0.getIdIntervention());
		assertEquals(0, intervention0.getEntretienPc());
		assertEquals(";aBs=Q/9!%u|V", intervention0.getIdOrganisme());
		assertEquals("sVcSTFV12%5M@Y{n*", intervention0.getIdBatiment());
	}

	@Test(timeout = 4000)
	public void test09() throws Throwable {
		LocalDate localDate0 = MockLocalDate.ofEpochDay(1508L);
		Float float0 = new Float((double) 1508L);
		Intervention intervention0 = new Intervention("tw", "tw", localDate0, "A)apEHgC#`", localDate0, float0,
				localDate0, float0, "tw", float0, float0, float0, "A)apEHgC#`", "", 0, 0);
		Float float1 = new Float(0.0F);
		intervention0.setMontantNonDeductible(float1);
		intervention0.getMontantNonDeductible();
		assertEquals(0, intervention0.getOrdures());
		assertEquals("tw", intervention0.getIdIntervention());
		assertEquals("A)apEHgC#`", intervention0.getNumFacture());
		assertEquals("", intervention0.getIdBatiment());
		assertEquals("A)apEHgC#`", intervention0.getIdOrganisme());
		assertEquals(0, intervention0.getEntretienPc());
		assertEquals("tw", intervention0.getNumDevis());
		assertEquals("tw", intervention0.getIntitule());
	}

	@Test(timeout = 4000)
	public void test10() throws Throwable {
		LocalDate localDate0 = MockLocalDate.ofYearDay(1, 1);
		Float float0 = new Float((float) 1);
		Intervention intervention0 = new Intervention("", ", dateAcompte=", localDate0, "", localDate0, float0,
				localDate0, float0, "", float0, float0, float0, "", "-x^<kUS", 1, 1);
		intervention0.getMontantNonDeductible();
		assertEquals("-x^<kUS", intervention0.getIdBatiment());
		assertEquals(1, intervention0.getEntretienPc());
		assertEquals("", intervention0.getNumDevis());
		assertEquals(", dateAcompte=", intervention0.getIntitule());
		assertEquals("", intervention0.getNumFacture());
		assertEquals(1, intervention0.getOrdures());
		assertEquals("", intervention0.getIdOrganisme());
		assertEquals("", intervention0.getIdIntervention());
	}

	@Test(timeout = 4000)
	public void test11() throws Throwable {
		Float float0 = new Float(0.0F);
		Intervention intervention0 = new Intervention(";aBs&b=Q/u9!%u|V", "SGbu?Qd)u<(", (LocalDate) null, "",
				(LocalDate) null, (Float) null, (LocalDate) null, float0, ";aBs&b=Q/u9!%u|V", (Float) null,
				(Float) null, float0, "]", "SGbu?Qd)u<(", 0, 0);
		Float float1 = intervention0.getMontantNonDeductible();
		assertEquals("]", intervention0.getIdOrganisme());
		assertEquals(0, intervention0.getOrdures());
		assertEquals("SGbu?Qd)u<(", intervention0.getIdBatiment());
		assertEquals(";aBs&b=Q/u9!%u|V", intervention0.getNumDevis());
		assertEquals("", intervention0.getNumFacture());
		assertEquals("SGbu?Qd)u<(", intervention0.getIntitule());
		assertNull(float1);
		assertEquals(0, intervention0.getEntretienPc());
		assertEquals(";aBs&b=Q/u9!%u|V", intervention0.getIdIntervention());
	}

	@Test(timeout = 4000)
	public void test12() throws Throwable {
		Float float0 = new Float(617.0F);
		LocalDate localDate0 = MockLocalDate.ofEpochDay(0);
		Float float1 = new Float(0.0);
		Intervention intervention0 = new Intervention("9{po", "]+x4mI|U!P!v5/k^+", localDate0, "S$/S[x#", localDate0,
				float1, localDate0, float0, ";aBs&b=Q/u9!%u|V", float0, float1, float0, ", intitul\u00E9=",
				"j<?fVKK0/C<", 0, 1202);
		Float float2 = intervention0.getMontantFacture();
		assertEquals(617.0F, intervention0.getReduction(), 0.01F);
		assertEquals(0, intervention0.getEntretienPc());
		assertEquals("9{po", intervention0.getIdIntervention());
		assertEquals(617.0F, intervention0.getAcompteFacture(), 0.01F);
		assertEquals("j<?fVKK0/C<", intervention0.getIdBatiment());
		assertEquals(1202, intervention0.getOrdures());
		assertEquals(617.0F, intervention0.getMontantDevis(), 0.01F);
		assertEquals(0.0F, intervention0.getMontantNonDeductible(), 0.01F);
		assertEquals("]+x4mI|U!P!v5/k^+", intervention0.getIntitule());
		assertEquals(0.0F, (float) float2, 0.01F);
		assertEquals("S$/S[x#", intervention0.getNumFacture());
		assertEquals(";aBs&b=Q/u9!%u|V", intervention0.getNumDevis());
		assertEquals(", intitul\u00E9=", intervention0.getIdOrganisme());
	}

	@Test(timeout = 4000)
	public void test13() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Float float0 = new Float(0.0);
		Intervention intervention0 = new Intervention("", "", localDate0, "", localDate0, float0, localDate0, float0,
				"", float0, float0, float0, "", "", 0, 0);
		intervention0.setMontantFacture((Float) null);
		intervention0.getMontantFacture();
		assertEquals(0, intervention0.getEntretienPc());
		assertEquals(0, intervention0.getOrdures());
	}

	@Test(timeout = 4000)
	public void test14() throws Throwable {
		Float float0 = new Float(617.0F);
		Intervention intervention0 = new Intervention(";aBs&b=Q/u9!%u|V", "sVcSTFV12%5M@Y{n*", (LocalDate) null,
				";aBs&b=Q/u9!%u|V", (LocalDate) null, float0, (LocalDate) null, float0, ";aBs&b=Q/u9!%u|V", float0,
				float0, float0, ";aBs&b=Q/u9!%u|V", ";aBs&b=Q/u9!%u|V", 0, 0);
		Float float1 = new Float((-1.0F));
		intervention0.setMontantFacture(float1);
		intervention0.getMontantFacture();
		assertEquals(0, intervention0.getEntretienPc());
		assertEquals("sVcSTFV12%5M@Y{n*", intervention0.getIntitule());
		assertEquals(";aBs&b=Q/u9!%u|V", intervention0.getNumDevis());
		assertEquals(0, intervention0.getOrdures());
		assertEquals(";aBs&b=Q/u9!%u|V", intervention0.getIdBatiment());
		assertEquals(";aBs&b=Q/u9!%u|V", intervention0.getNumFacture());
		assertEquals(";aBs&b=Q/u9!%u|V", intervention0.getIdIntervention());
		assertEquals(";aBs&b=Q/u9!%u|V", intervention0.getIdOrganisme());
	}

	@Test(timeout = 4000)
	public void test15() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Float float0 = new Float(0.0);
		Intervention intervention0 = new Intervention("", "", localDate0, "", localDate0, float0, localDate0, float0,
				"", float0, float0, float0, "", "", 0, 0);
		intervention0.getMontantDevis();
		assertEquals(0, intervention0.getEntretienPc());
		assertEquals(0, intervention0.getOrdures());
	}

	@Test(timeout = 4000)
	public void test16() throws Throwable {
		LocalDate localDate0 = MockLocalDate.ofYearDay(1, 1);
		Float float0 = new Float((float) 1);
		Intervention intervention0 = new Intervention("", ", dateAcompte=", localDate0, "", localDate0, float0,
				localDate0, float0, "", float0, float0, float0, "", "-x^<kUS", 1, 1);
		intervention0.getMontantDevis();
		assertEquals(1, intervention0.getEntretienPc());
		assertEquals(", dateAcompte=", intervention0.getIntitule());
		assertEquals("", intervention0.getIdIntervention());
		assertEquals("", intervention0.getNumDevis());
		assertEquals(1, intervention0.getOrdures());
		assertEquals("", intervention0.getNumFacture());
		assertEquals("", intervention0.getIdOrganisme());
		assertEquals("-x^<kUS", intervention0.getIdBatiment());
	}

	@Test(timeout = 4000)
	public void test17() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Float float0 = new Float((-1.0F));
		Intervention intervention0 = new Intervention("", "", localDate0, "", localDate0, (Float) null, localDate0,
				(Float) null, "", (Float) null, float0, (Float) null, "", ", montantFacture=", 3992, 1);
		Float float1 = intervention0.getMontantDevis();
		assertEquals(1, intervention0.getOrdures());
		assertEquals("", intervention0.getIdOrganisme());
		assertEquals("", intervention0.getNumFacture());
		assertEquals(3992, intervention0.getEntretienPc());
		assertEquals("", intervention0.getNumDevis());
		assertEquals("", intervention0.getIntitule());
		assertEquals("", intervention0.getIdIntervention());
		assertEquals(", montantFacture=", intervention0.getIdBatiment());
		assertNull(float1);
	}

	@Test(timeout = 4000)
	public void test18() throws Throwable {
		LocalDate localDate0 = MockLocalDate.ofEpochDay((-473L));
		Float float0 = new Float((-2850.0F));
		Intervention intervention0 = new Intervention((String) null, (String) null, localDate0, (String) null,
				localDate0, (Float) null, localDate0, float0, (String) null, (Float) null, float0, float0,
				(String) null, (String) null, (-1), 2056);
		intervention0.getIntitule();
		assertEquals(2056, intervention0.getOrdures());
		assertEquals((-1), intervention0.getEntretienPc());
	}

	@Test(timeout = 4000)
	public void test19() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Float float0 = new Float(0.0);
		Intervention intervention0 = new Intervention("", "", localDate0, "", localDate0, float0, localDate0, float0,
				"", float0, float0, float0, "", "", 0, 0);
		intervention0.getIntitule();
		assertEquals(0, intervention0.getOrdures());
		assertEquals(0, intervention0.getEntretienPc());
	}

	@Test(timeout = 4000)
	public void test20() throws Throwable {
		Float float0 = new Float(617.0F);
		LocalDate localDate0 = MockLocalDate.ofEpochDay((-4550L));
		Intervention intervention0 = new Intervention("4m5 $Xn", ";aBs&b=Q/u9!%u|V", (LocalDate) null,
				";aBs&b=Q/u9!%u|V", localDate0, float0, (LocalDate) null, float0, "r&i OX", float0, float0,
				(Float) null, (String) null, "sVcSTFV12%5M@Y{n*", 0, 1806);
		String string0 = intervention0.getIdOrganisme();
		assertEquals("sVcSTFV12%5M@Y{n*", intervention0.getIdBatiment());
		assertNull(string0);
		assertEquals(0, intervention0.getEntretienPc());
		assertEquals("4m5 $Xn", intervention0.getIdIntervention());
		assertEquals(";aBs&b=Q/u9!%u|V", intervention0.getNumFacture());
		assertEquals(";aBs&b=Q/u9!%u|V", intervention0.getIntitule());
		assertEquals("r&i OX", intervention0.getNumDevis());
		assertEquals(1806, intervention0.getOrdures());
	}

	@Test(timeout = 4000)
	public void test21() throws Throwable {
		Float float0 = new Float(1.0);
		Intervention intervention0 = new Intervention(", idBatiment=", "S.^2,k", (LocalDate) null, ", idBatiment=",
				(LocalDate) null, float0, (LocalDate) null, float0, "", float0, float0, (Float) null, "", "S.^2,k", 0,
				1);
		String string0 = intervention0.getIdOrganisme();
		assertEquals(", idBatiment=", intervention0.getIdIntervention());
		assertEquals(1, intervention0.getOrdures());
		assertEquals("S.^2,k", intervention0.getIntitule());
		assertEquals("S.^2,k", intervention0.getIdBatiment());
		assertEquals("", string0);
		assertEquals("", intervention0.getNumDevis());
		assertEquals(0, intervention0.getEntretienPc());
		assertEquals(", idBatiment=", intervention0.getNumFacture());
	}

	@Test(timeout = 4000)
	public void test22() throws Throwable {
		LocalDate localDate0 = MockLocalDate.ofEpochDay((-473L));
		Float float0 = new Float((-2850.0F));
		Intervention intervention0 = new Intervention((String) null, (String) null, localDate0, (String) null,
				localDate0, (Float) null, localDate0, float0, (String) null, (Float) null, float0, float0,
				(String) null, (String) null, (-1), 2056);
		intervention0.getIdIntervention();
		assertEquals((-1), intervention0.getEntretienPc());
		assertEquals(2056, intervention0.getOrdures());
	}

	@Test(timeout = 4000)
	public void test23() throws Throwable {
		Float float0 = new Float(926.4F);
		Intervention intervention0 = new Intervention("", (String) null, (LocalDate) null, "", (LocalDate) null, float0,
				(LocalDate) null, float0, "", float0, float0, float0, "", "", 0, 0);
		intervention0.setIdIntervention("7#waQu2");
		intervention0.getIdIntervention();
		assertEquals(0, intervention0.getOrdures());
		assertEquals(0, intervention0.getEntretienPc());
	}

	@Test(timeout = 4000)
	public void test24() throws Throwable {
		LocalDate localDate0 = MockLocalDate.ofEpochDay((-473L));
		Float float0 = new Float((-2850.0F));
		Intervention intervention0 = new Intervention((String) null, (String) null, localDate0, (String) null,
				localDate0, (Float) null, localDate0, float0, (String) null, (Float) null, float0, float0,
				(String) null, (String) null, (-1), 2056);
		intervention0.getIdBatiment();
		assertEquals((-1), intervention0.getEntretienPc());
		assertEquals(2056, intervention0.getOrdures());
	}

	@Test(timeout = 4000)
	public void test25() throws Throwable {
		Float float0 = new Float(617.0F);
		Intervention intervention0 = new Intervention(";aBs=Q/9!%u|V", "sVcSTFV12%5M@Y{n*", (LocalDate) null,
				";aBs=Q/9!%u|V", (LocalDate) null, float0, (LocalDate) null, float0, "sVcSTFV12%5M@Y{n*", float0,
				float0, float0, ";aBs=Q/9!%u|V", "sVcSTFV12%5M@Y{n*", 0, 0);
		String string0 = intervention0.getIdBatiment();
		assertEquals("sVcSTFV12%5M@Y{n*", intervention0.getNumDevis());
		assertEquals("sVcSTFV12%5M@Y{n*", string0);
		assertEquals(";aBs=Q/9!%u|V", intervention0.getIdIntervention());
		assertEquals("sVcSTFV12%5M@Y{n*", intervention0.getIntitule());
		assertEquals(0, intervention0.getOrdures());
		assertEquals(";aBs=Q/9!%u|V", intervention0.getNumFacture());
		assertEquals(";aBs=Q/9!%u|V", intervention0.getIdOrganisme());
		assertEquals(0, intervention0.getEntretienPc());
	}

	@Test(timeout = 4000)
	public void test26() throws Throwable {
		Float float0 = new Float((-3763.73541292852));
		Intervention intervention0 = new Intervention("<EKk7Ui933ja ", "3mH\"+>nt", (LocalDate) null, "<EKk7Ui933ja ",
				(LocalDate) null, float0, (LocalDate) null, float0, "gP?2", float0, float0, float0, "", "3mH\"+>nt",
				250, 250);
		int int0 = intervention0.getEntretienPc();
		assertEquals("", intervention0.getIdOrganisme());
		assertEquals("3mH\"+>nt", intervention0.getIdBatiment());
		assertEquals("gP?2", intervention0.getNumDevis());
		assertEquals("3mH\"+>nt", intervention0.getIntitule());
		assertEquals(250, intervention0.getOrdures());
		assertEquals(250, int0);
		assertEquals("<EKk7Ui933ja ", intervention0.getIdIntervention());
		assertEquals("<EKk7Ui933ja ", intervention0.getNumFacture());
	}

	@Test(timeout = 4000)
	public void test27() throws Throwable {
		Float float0 = new Float(1.0);
		Month month0 = Month.DECEMBER;
		LocalDate localDate0 = MockLocalDate.of((-1), month0, 1);
		Intervention intervention0 = new Intervention("", (String) null, localDate0, "", localDate0, float0, localDate0,
				float0, "", float0, float0, float0, "", "", (-1695), (-1));
		int int0 = intervention0.getEntretienPc();
		assertEquals((-1695), int0);
		assertEquals((-1), intervention0.getOrdures());
	}

	@Test(timeout = 4000)
	public void test28() throws Throwable {
		Float float0 = new Float(617.0F);
		Intervention intervention0 = new Intervention(";aBs&b=Q/u9!%u|V", "sVcSTFV12%5M@Y{n*", (LocalDate) null,
				";aBs&b=Q/u9!%u|V", (LocalDate) null, float0, (LocalDate) null, float0, "7pCf>U", float0, float0,
				float0, ";aBs&b=Q/u9!%u|V", "7pCf>U", 0, 0);
		intervention0.getDateIntervention();
		assertEquals("7pCf>U", intervention0.getIdBatiment());
		assertEquals(";aBs&b=Q/u9!%u|V", intervention0.getNumFacture());
		assertEquals(0, intervention0.getEntretienPc());
		assertEquals("7pCf>U", intervention0.getNumDevis());
		assertEquals(";aBs&b=Q/u9!%u|V", intervention0.getIdOrganisme());
		assertEquals(";aBs&b=Q/u9!%u|V", intervention0.getIdIntervention());
		assertEquals("sVcSTFV12%5M@Y{n*", intervention0.getIntitule());
		assertEquals(0, intervention0.getOrdures());
	}

	@Test(timeout = 4000)
	public void test29() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Float float0 = new Float((-1.0F));
		Intervention intervention0 = new Intervention("", "", localDate0, "", localDate0, (Float) null, localDate0,
				(Float) null, "", (Float) null, float0, (Float) null, "", ", montantFacture=", 3992, 1);
		intervention0.getDateFacture();
		assertEquals("", intervention0.getIdIntervention());
		assertEquals("", intervention0.getNumDevis());
		assertEquals("", intervention0.getIntitule());
		assertEquals(3992, intervention0.getEntretienPc());
		assertEquals("", intervention0.getIdOrganisme());
		assertEquals(1, intervention0.getOrdures());
		assertEquals("", intervention0.getNumFacture());
		assertEquals(", montantFacture=", intervention0.getIdBatiment());
	}

	@Test(timeout = 4000)
	public void test30() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Float float0 = new Float(0.0);
		Intervention intervention0 = new Intervention("", "", localDate0, "", localDate0, float0, localDate0, float0,
				"", float0, float0, float0, "", "", 0, 0);
		intervention0.getDateAcompte();
		assertEquals(0, intervention0.getOrdures());
		assertEquals(0, intervention0.getEntretienPc());
	}

	@Test(timeout = 4000)
	public void test31() throws Throwable {
		Float float0 = new Float(616.8F);
		Intervention intervention0 = new Intervention(";aBs&b+Q/u{!%u|V", ";aBs&b+Q/u{!%u|V", (LocalDate) null,
				";aBs&b+Q/u{!%u|V", (LocalDate) null, float0, (LocalDate) null, float0, ";aBs&b+Q/u{!%u|V", float0,
				float0, float0, ";aBs&b+Q/u{!%u|V", ";aBs&b+Q/u{!%u|V", 0, 0);
		Float float1 = new Float((float) 0);
		intervention0.setAcompteFacture(float1);
		intervention0.getAcompteFacture();
		assertEquals(0, intervention0.getOrdures());
		assertEquals(0, intervention0.getEntretienPc());
	}

	@Test(timeout = 4000)
	public void test32() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Float float0 = new Float((-1.0F));
		Intervention intervention0 = new Intervention("", "", localDate0, "", localDate0, (Float) null, localDate0,
				(Float) null, "", (Float) null, float0, (Float) null, "", ", montantFacture=", 3992, 1);
		Float float1 = intervention0.getAcompteFacture();
		assertEquals("", intervention0.getIdOrganisme());
		assertEquals(3992, intervention0.getEntretienPc());
		assertEquals("", intervention0.getNumDevis());
		assertEquals("", intervention0.getIntitule());
		assertEquals(", montantFacture=", intervention0.getIdBatiment());
		assertEquals(1, intervention0.getOrdures());
		assertNull(float1);
		assertEquals("", intervention0.getIdIntervention());
		assertEquals("", intervention0.getNumFacture());
	}

	@Test(timeout = 4000)
	public void test33() throws Throwable {
		Float float0 = new Float((-3763.73541292852));
		Intervention intervention0 = new Intervention("PEKk7,FM33ja ", "", (LocalDate) null, "", (LocalDate) null,
				float0, (LocalDate) null, float0, "", float0, float0, float0, "", ", dateIntervention=", 0, 0);
		intervention0.getAcompteFacture();
		assertEquals(0, intervention0.getOrdures());
		assertEquals("", intervention0.getNumDevis());
		assertEquals("", intervention0.getIntitule());
		assertEquals(0, intervention0.getEntretienPc());
		assertEquals("", intervention0.getIdOrganisme());
		assertEquals("PEKk7,FM33ja ", intervention0.getIdIntervention());
		assertEquals(", dateIntervention=", intervention0.getIdBatiment());
		assertEquals("", intervention0.getNumFacture());
	}

	@Test(timeout = 4000)
	public void test34() throws Throwable {
		Float float0 = new Float(673.1913F);
		Intervention intervention0 = new Intervention("B]G", "B]G", (LocalDate) null, "B]G", (LocalDate) null, float0,
				(LocalDate) null, float0, "B]G", float0, float0, float0, "B]G", "B]G", 22, 22);
		Intervention intervention1 = new Intervention("B]G", "B]G", (LocalDate) null, "B]G", (LocalDate) null, float0,
				(LocalDate) null, float0, "B]G", float0, float0, float0, "B]G", "B]G", 22, 758);
		intervention0.equals(intervention1);
		assertEquals(758, intervention1.getOrdures());
		assertEquals(22, intervention1.getEntretienPc());
		assertEquals(22, intervention0.getEntretienPc());
	}

	@Test(timeout = 4000)
	public void test35() throws Throwable {
		Float float0 = new Float(617.7317F);
		Intervention intervention0 = new Intervention(", r\u00E9duction=", ", r\u00E9duction=", (LocalDate) null,
				", r\u00E9duction=", (LocalDate) null, float0, (LocalDate) null, float0, ", r\u00E9duction=", float0,
				float0, float0, ", r\u00E9duction=", ", r\u00E9duction=", (-2), (-2));
		boolean boolean0 = intervention0.equals((Object) null);
		assertEquals((-2), intervention0.getEntretienPc());
		assertFalse(boolean0);
		assertEquals((-2), intervention0.getOrdures());
	}

	@Test(timeout = 4000)
	public void test36() throws Throwable {
		Float float0 = new Float((-3763.73541292852));
		Intervention intervention0 = new Intervention("PEKk7,FM33ja ", "3mH\"+>nt", (LocalDate) null, "PEKk7,FM33ja ",
				(LocalDate) null, float0, (LocalDate) null, float0, "gP?2", float0, float0, float0, "", "3mH\"+>nt",
				250, 250);
		boolean boolean0 = intervention0.equals(intervention0);
		assertEquals("", intervention0.getIdOrganisme());
		assertEquals("PEKk7,FM33ja ", intervention0.getIdIntervention());
		assertTrue(boolean0);
		assertEquals("gP?2", intervention0.getNumDevis());
		assertEquals(250, intervention0.getOrdures());
		assertEquals("3mH\"+>nt", intervention0.getIntitule());
		assertEquals("PEKk7,FM33ja ", intervention0.getNumFacture());
		assertEquals(250, intervention0.getEntretienPc());
		assertEquals("3mH\"+>nt", intervention0.getIdBatiment());
	}

	@Test(timeout = 4000)
	public void test37() throws Throwable {
		LocalDate localDate0 = MockLocalDate.ofEpochDay(1508L);
		Float float0 = new Float((double) 1508L);
		Intervention intervention0 = new Intervention("", "", localDate0, "A)apEHgC#`", localDate0, float0, localDate0,
				float0, "", float0, float0, float0, "A)apEHgC#`", "", 0, 0);
		boolean boolean0 = intervention0.equals("");
		assertEquals("", intervention0.getIdBatiment());
		assertEquals("", intervention0.getIntitule());
		assertEquals("A)apEHgC#`", intervention0.getIdOrganisme());
		assertEquals("A)apEHgC#`", intervention0.getNumFacture());
		assertEquals("", intervention0.getNumDevis());
		assertEquals(0, intervention0.getOrdures());
		assertEquals(0, intervention0.getEntretienPc());
		assertFalse(boolean0);
		assertEquals("", intervention0.getIdIntervention());
	}

	@Test(timeout = 4000)
	public void test38() throws Throwable {
		Float float0 = new Float(616.8F);
		Intervention intervention0 = new Intervention(";aBs&b=Q/u9!%u|V", ";aBs&b=Q/u9!%u|V", (LocalDate) null,
				";aBs&b=Q/u9!%u|V", (LocalDate) null, float0, (LocalDate) null, float0, ";aBs&b=Q/u9!%u|V", float0,
				float0, float0, ";aBs&b=Q/u9!%u|V", ";aBs&b=Q/u9!%u|V", 0, 0);
		intervention0.setDateIntervention((LocalDate) null);
		assertEquals(0, intervention0.getOrdures());
		assertEquals(0, intervention0.getEntretienPc());
	}

	@Test(timeout = 4000)
	public void test39() throws Throwable {
		Period period0 = Period.of((-1), (-1), (-1));
		IsoChronology isoChronology0 = period0.getChronology();
		LocalDate localDate0 = MockIsoChronology.dateNow(isoChronology0);
		Float float0 = new Float((float) (-1322L));
		Intervention intervention0 = new Intervention((String) null, (String) null, localDate0, (String) null,
				localDate0, float0, localDate0, (Float) null, ", numFacture=", float0, (Float) null, (Float) null, "",
				", numFacture=", (-1), (-1));
		assertEquals("", intervention0.getIdOrganisme());

		intervention0.setOrganisme("dz.,ZCcEO{BCE2>");
		assertEquals((-1), intervention0.getOrdures());
	}

	@Test(timeout = 4000)
	public void test40() throws Throwable {
		LocalDate localDate0 = MockLocalDate.ofEpochDay(1508L);
		Float float0 = new Float((double) 1508L);
		Intervention intervention0 = new Intervention("", "", localDate0, "A)apEHgC#`", localDate0, float0, localDate0,
				float0, "", float0, float0, float0, "A)apEHgC#`", "", 0, 0);
		intervention0.getDateIntervention();
		assertEquals(0, intervention0.getOrdures());
		assertEquals("A)apEHgC#`", intervention0.getNumFacture());
		assertEquals("A)apEHgC#`", intervention0.getIdOrganisme());
		assertEquals("", intervention0.getIdBatiment());
		assertEquals("", intervention0.getIdIntervention());
		assertEquals(0, intervention0.getEntretienPc());
		assertEquals("", intervention0.getNumDevis());
		assertEquals("", intervention0.getIntitule());
	}

	@Test(timeout = 4000)
	public void test41() throws Throwable {
		Float float0 = new Float(616.3069F);
		Intervention intervention0 = new Intervention(", r\u00E9duction=", ", r\u00E9duction=", (LocalDate) null,
				", r\u00E9duction=", (LocalDate) null, float0, (LocalDate) null, float0, ", r\u00E9duction=", float0,
				float0, float0, ", r\u00E9duction=", ", r\u00E9duction=", 0, 0);
		intervention0.setMontantDevis(float0);
		assertEquals(0, intervention0.getOrdures());
		assertEquals(0, intervention0.getEntretienPc());
	}

	@Test(timeout = 4000)
	public void test42() throws Throwable {
		Float float0 = new Float(1.0);
		Intervention intervention0 = new Intervention(", idBatiment=", "S.^2,k", (LocalDate) null, ", idBatiment=",
				(LocalDate) null, float0, (LocalDate) null, float0, "", float0, float0, (Float) null, "", "S.^2,k", 0,
				1);
		intervention0.setDateFacture((LocalDate) null);
		assertEquals("", intervention0.getNumDevis());
		assertEquals("", intervention0.getIdOrganisme());
		assertEquals(", idBatiment=", intervention0.getNumFacture());
		assertEquals(0, intervention0.getEntretienPc());
		assertEquals(", idBatiment=", intervention0.getIdIntervention());
		assertEquals("S.^2,k", intervention0.getIntitule());
		assertEquals(1, intervention0.getOrdures());
		assertEquals("S.^2,k", intervention0.getIdBatiment());
	}

	@Test(timeout = 4000)
	public void test43() throws Throwable {
		Float float0 = new Float(616.8F);
		Intervention intervention0 = new Intervention(", r\u00E9duction=", ", r\u00E9duction=", (LocalDate) null,
				", r\u00E9duction=", (LocalDate) null, float0, (LocalDate) null, float0, ", r\u00E9duction=", float0,
				float0, float0, ", r\u00E9duction=", ", r\u00E9duction=", 0, 0);
		intervention0.setNumFacture(", r\u00E9duction=");
		assertEquals(0, intervention0.getOrdures());
		assertEquals(0, intervention0.getEntretienPc());
	}

	@Test(timeout = 4000)
	public void test44() throws Throwable {
		LocalDate localDate0 = MockLocalDate.ofEpochDay(1508L);
		Float float0 = new Float((double) 1508L);
		Intervention intervention0 = new Intervention("", "", localDate0, "A)apEHgC#`", localDate0, float0, localDate0,
				float0, "", float0, float0, float0, "A)apEHgC#`", "", 0, 0);
		String string0 = intervention0.getNumDevis();
		assertEquals("", string0);
		assertEquals("", intervention0.getIdBatiment());
		assertEquals(0, intervention0.getOrdures());
		assertEquals("", intervention0.getIdIntervention());
		assertEquals(0, intervention0.getEntretienPc());
		assertEquals("", intervention0.getIntitule());
		assertEquals("A)apEHgC#`", intervention0.getNumFacture());
		assertEquals("A)apEHgC#`", intervention0.getIdOrganisme());
	}

	@Test(timeout = 4000)
	public void test45() throws Throwable {
		LocalDate localDate0 = MockLocalDate.ofEpochDay(1508L);
		Float float0 = new Float((double) 1508L);
		Intervention intervention0 = new Intervention("", "", localDate0, "A)apEHgC#`", localDate0, float0, localDate0,
				float0, "", float0, float0, float0, "A)apEHgC#`", "", 0, 0);
		String string0 = intervention0.getIdBatiment();
		assertEquals(0, intervention0.getEntretienPc());
		assertEquals("", intervention0.getIntitule());
		assertEquals("", intervention0.getIdIntervention());
		assertEquals("", string0);
		assertEquals("", intervention0.getNumDevis());
		assertEquals("A)apEHgC#`", intervention0.getIdOrganisme());
		assertEquals("A)apEHgC#`", intervention0.getNumFacture());
		assertEquals(0, intervention0.getOrdures());
	}

	@Test(timeout = 4000)
	public void test46() throws Throwable {
		LocalDate localDate0 = MockLocalDate.ofEpochDay(1508L);
		Float float0 = new Float((double) 1508L);
		Intervention intervention0 = new Intervention("", "", localDate0, "A)apEHgC#`", localDate0, float0, localDate0,
				float0, "", float0, float0, float0, "A)apEHgC#`", "", 0, 0);
		String string0 = intervention0.toString();
		assertEquals(0, intervention0.getEntretienPc());
		assertEquals(
				"Intervention [idIntervention=, intitul\u00E9=, dateIntervention=1974-02-17, numFacture=A)apEHgC#`, dateFacture=1974-02-17, montantFacture=1508.0, dateAcompte=1974-02-17, acompteFacture=1508.0, numDevis=, montantDevis=1508.0, montantNonD\u00E9ductible=1508.0, r\u00E9duction=1508.0, numSiret=A)apEHgC#`, idBatiment=]",
				string0);
		assertEquals(0, intervention0.getOrdures());
	}

	@Test(timeout = 4000)
	public void test47() throws Throwable {
		Float float0 = new Float(616.06415F);
		Intervention intervention0 = new Intervention("", "", (LocalDate) null, "", (LocalDate) null, float0,
				(LocalDate) null, float0, "", float0, float0, float0, "", "", 0, 0);
		intervention0.setDateAcompte((LocalDate) null);
		assertEquals(0, intervention0.getOrdures());
		assertEquals(0, intervention0.getEntretienPc());
	}

	@Test(timeout = 4000)
	public void test48() throws Throwable {
		LocalDate localDate0 = MockLocalDate.ofEpochDay(1508L);
		Float float0 = new Float((double) 1508L);
		Intervention intervention0 = new Intervention("", "", localDate0, "A)apEHgC#`", localDate0, float0, localDate0,
				float0, "", float0, float0, float0, "A)apEHgC#`", "", 0, 0);
		int int0 = intervention0.getOrdures();
		assertEquals("", intervention0.getIntitule());
		assertEquals(0, int0);
		assertEquals("", intervention0.getIdIntervention());
		assertEquals(0, intervention0.getEntretienPc());
		assertEquals("A)apEHgC#`", intervention0.getIdOrganisme());
		assertEquals("", intervention0.getIdBatiment());
		assertEquals("", intervention0.getNumDevis());
		assertEquals("A)apEHgC#`", intervention0.getNumFacture());
	}

	@Test(timeout = 4000)
	public void test49() throws Throwable {
		Float float0 = new Float((-382.0F));
		Intervention intervention0 = new Intervention(";aBs&b=Q/u9!%u|V", ";aBs&b=Q/u9!%u|V", (LocalDate) null,
				";aBs&b=Q/u9!%u|V", (LocalDate) null, float0, (LocalDate) null, float0, ";aBs&b=Q/u9!%u|V", float0,
				float0, float0, ";aBs&b=Q/u9!%u|V", ";aBs&b=Q/u9!%u|V", 0, 0);
		intervention0.getMontantDevis();
		assertEquals(0, intervention0.getOrdures());
		assertEquals(0, intervention0.getEntretienPc());
	}

	@Test(timeout = 4000)
	public void test50() throws Throwable {
		Period period0 = Period.of((-1), (-1), (-1));
		IsoChronology isoChronology0 = period0.getChronology();
		LocalDate localDate0 = MockIsoChronology.dateNow(isoChronology0);
		Float float0 = new Float((float) (-1322L));
		Intervention intervention0 = new Intervention((String) null, (String) null, localDate0, (String) null,
				localDate0, float0, localDate0, (Float) null, ", numFacture=", float0, (Float) null, (Float) null, "",
				", numFacture=", (-1), (-1));
		String string0 = intervention0.getNumFacture();
		assertNull(string0);
		assertEquals((-1), intervention0.getEntretienPc());
		assertEquals("", intervention0.getIdOrganisme());
		assertEquals(", numFacture=", intervention0.getNumDevis());
		assertEquals(", numFacture=", intervention0.getIdBatiment());
		assertEquals((-1), intervention0.getOrdures());
	}

	@Test(timeout = 4000)
	public void test51() throws Throwable {
		Float float0 = new Float(630.2638F);
		Intervention intervention0 = new Intervention(", r\u00E9duction=", ", r\u00E9duction=", (LocalDate) null,
				", r\u00E9duction=", (LocalDate) null, float0, (LocalDate) null, float0, ", r\u00E9duction=", float0,
				float0, float0, ", r\u00E9duction=", ", r\u00E9duction=", 0, 0);
		intervention0.hashCode();
		assertEquals(0, intervention0.getEntretienPc());
		assertEquals(0, intervention0.getOrdures());
	}

	@Test(timeout = 4000)
	public void test52() throws Throwable {
		Float float0 = new Float(617.0F);
		Intervention intervention0 = new Intervention(";aBs&b=Q/u9!%u|V", ";aBs&b=Q/u9!%u|V", (LocalDate) null,
				";aBs&b=Q/u9!%u|V", (LocalDate) null, float0, (LocalDate) null, float0, "7pCf>U", float0, float0,
				float0, ";aBs&b=Q/u9!%u|V", "7pCf>U", 0, 0);
		intervention0.getDateFacture();
		assertEquals("7pCf>U", intervention0.getNumDevis());
		assertEquals(0, intervention0.getOrdures());
		assertEquals(";aBs&b=Q/u9!%u|V", intervention0.getIntitule());
		assertEquals(0, intervention0.getEntretienPc());
		assertEquals("7pCf>U", intervention0.getIdBatiment());
		assertEquals(";aBs&b=Q/u9!%u|V", intervention0.getNumFacture());
		assertEquals(";aBs&b=Q/u9!%u|V", intervention0.getIdOrganisme());
		assertEquals(";aBs&b=Q/u9!%u|V", intervention0.getIdIntervention());
	}

	@Test(timeout = 4000)
	public void test53() throws Throwable {
		Float float0 = new Float(617.0F);
		Intervention intervention0 = new Intervention("", "*", (LocalDate) null, "", (LocalDate) null, (Float) null,
				(LocalDate) null, float0, "", float0, float0, float0, "sVcSTFV12%5M@Y{n*", "^q'^Syq-*V\"T5T)*", (-2551),
				(-2551));
		String string0 = intervention0.getIdIntervention();
		assertEquals("^q'^Syq-*V\"T5T)*", intervention0.getIdBatiment());
		assertEquals((-2551), intervention0.getOrdures());
		assertEquals("", intervention0.getNumDevis());
		assertEquals((-2551), intervention0.getEntretienPc());
		assertEquals("", intervention0.getNumFacture());
		assertEquals("", string0);
		assertEquals("*", intervention0.getIntitule());
		assertEquals("sVcSTFV12%5M@Y{n*", intervention0.getIdOrganisme());
	}

	@Test(timeout = 4000)
	public void test54() throws Throwable {
		Float float0 = new Float(1.0);
		Intervention intervention0 = new Intervention(", idBatiment=", "S.^2,k", (LocalDate) null, ", idBatiment=",
				(LocalDate) null, float0, (LocalDate) null, float0, "", float0, float0, (Float) null, "", "S.^2,k", 0,
				1);
		Float float1 = intervention0.getReduction();
		assertNull(float1);
		assertEquals(", idBatiment=", intervention0.getNumFacture());
		assertEquals("", intervention0.getNumDevis());
		assertEquals("S.^2,k", intervention0.getIdBatiment());
		assertEquals(0, intervention0.getEntretienPc());
		assertEquals(", idBatiment=", intervention0.getIdIntervention());
		assertEquals("S.^2,k", intervention0.getIntitule());
		assertEquals("", intervention0.getIdOrganisme());
		assertEquals(1, intervention0.getOrdures());
	}

	@Test(timeout = 4000)
	public void test55() throws Throwable {
		Float float0 = new Float((-382.0F));
		Intervention intervention0 = new Intervention(";aBs&b=Q/u9!%u|V", ";aBs&b=Q/u9!%u|V", (LocalDate) null,
				";aBs&b=Q/u9!%u|V", (LocalDate) null, float0, (LocalDate) null, float0, ";aBs&b=Q/u9!%u|V", float0,
				float0, float0, ";aBs&b=Q/u9!%u|V", ";aBs&b=Q/u9!%u|V", 0, 0);
		intervention0.setIntitule(";aBs&b=Q/u9!%u|V");
		assertEquals(0, intervention0.getEntretienPc());
		assertEquals(0, intervention0.getOrdures());
	}

	@Test(timeout = 4000)
	public void test56() throws Throwable {
		Float float0 = new Float(630.2638F);
		Intervention intervention0 = new Intervention(", r\u00E9duction=", ", r\u00E9duction=", (LocalDate) null,
				", r\u00E9duction=", (LocalDate) null, float0, (LocalDate) null, float0, ", r\u00E9duction=", float0,
				float0, float0, ", r\u00E9duction=", ", r\u00E9duction=", 0, 0);
		intervention0.setEntretienPc(0);
		assertEquals(0, intervention0.getOrdures());
		assertEquals(0, intervention0.getEntretienPc());
	}

	@Test(timeout = 4000)
	public void test57() throws Throwable {
		Float float0 = new Float(617.0F);
		Intervention intervention0 = new Intervention(";aBs&b=Q/u9!%u|V", "sVcSTFV12%5M@Y{n*", (LocalDate) null,
				";aBs&b=Q/u9!%u|V", (LocalDate) null, float0, (LocalDate) null, float0, "_9{po", float0, float0, float0,
				";aBs&b=Q/u9!%u|V", "_9{po", 0, 0);
		intervention0.getDateAcompte();
		assertEquals(";aBs&b=Q/u9!%u|V", intervention0.getIdOrganisme());
		assertEquals(0, intervention0.getOrdures());
		assertEquals("_9{po", intervention0.getNumDevis());
		assertEquals("_9{po", intervention0.getIdBatiment());
		assertEquals("sVcSTFV12%5M@Y{n*", intervention0.getIntitule());
		assertEquals(";aBs&b=Q/u9!%u|V", intervention0.getNumFacture());
		assertEquals(0, intervention0.getEntretienPc());
		assertEquals(";aBs&b=Q/u9!%u|V", intervention0.getIdIntervention());
	}

	@Test(timeout = 4000)
	public void test58() throws Throwable {
		Float float0 = new Float((-382.0F));
		Intervention intervention0 = new Intervention(";aBs&b=Q/u9!%u|V", ";aBs&b=Q/u9!%u|V", (LocalDate) null,
				";aBs&b=Q/u9!%u|V", (LocalDate) null, float0, (LocalDate) null, float0, ";aBs&b=Q/u9!%u|V", float0,
				float0, float0, ";aBs&b=Q/u9!%u|V", ";aBs&b=Q/u9!%u|V", 0, 0);
		intervention0.getMontantNonDeductible();
		assertEquals(0, intervention0.getOrdures());
		assertEquals(0, intervention0.getEntretienPc());
	}

	@Test(timeout = 4000)
	public void test59() throws Throwable {
		Float float0 = new Float(616.8F);
		Intervention intervention0 = new Intervention(";aBs&b+Q/u{!%u|V", ";aBs&b+Q/u{!%u|V", (LocalDate) null,
				";aBs&b+Q/u{!%u|V", (LocalDate) null, float0, (LocalDate) null, float0, ";aBs&b+Q/u{!%u|V", float0,
				float0, float0, ";aBs&b+Q/u{!%u|V", ";aBs&b+Q/u{!%u|V", 0, 0);
		intervention0.getAcompteFacture();
		assertEquals(0, intervention0.getOrdures());
		assertEquals(0, intervention0.getEntretienPc());
	}

	@Test(timeout = 4000)
	public void test60() throws Throwable {
		Float float0 = new Float(617.0F);
		Intervention intervention0 = new Intervention("", "*", (LocalDate) null, "", (LocalDate) null, (Float) null,
				(LocalDate) null, float0, "", float0, float0, float0, "sVcSTFV12%5M@Y{n*", "^q'^Syq-*V\"T5T)*", (-2551),
				(-2551));
		String string0 = intervention0.getIntitule();
		assertEquals((-2551), intervention0.getEntretienPc());
		assertEquals("", intervention0.getNumFacture());
		assertEquals("sVcSTFV12%5M@Y{n*", intervention0.getIdOrganisme());
		assertEquals("", intervention0.getIdIntervention());
		assertEquals("^q'^Syq-*V\"T5T)*", intervention0.getIdBatiment());
		assertEquals("*", string0);
		assertEquals((-2551), intervention0.getOrdures());
		assertEquals("", intervention0.getNumDevis());
	}

	@Test(timeout = 4000)
	public void test61() throws Throwable {
		Float float0 = new Float(616.8F);
		Intervention intervention0 = new Intervention(";aBs&b=Q/u9!%u|V", ";aBs&b=Q/u9!%u|V", (LocalDate) null,
				";aBs&b=Q/u9!%u|V", (LocalDate) null, float0, (LocalDate) null, float0, ";aBs&b=Q/u9!%u|V", float0,
				float0, float0, ";aBs&b=Q/u9!%u|V", ";aBs&b=Q/u9!%u|V", 0, 0);
		intervention0.setBatiment(";aBs&b=Q/u9!%u|V");
		assertEquals(0, intervention0.getEntretienPc());
		assertEquals(0, intervention0.getOrdures());
	}

	@Test(timeout = 4000)
	public void test62() throws Throwable {
		Float float0 = new Float(616.8F);
		Intervention intervention0 = new Intervention(", r\u00E9duction=", ", r\u00E9duction=", (LocalDate) null,
				", r\u00E9duction=", (LocalDate) null, float0, (LocalDate) null, float0, ", r\u00E9duction=", float0,
				float0, float0, ", r\u00E9duction=", ", r\u00E9duction=", 0, 0);
		intervention0.getIdOrganisme();
		assertEquals(0, intervention0.getOrdures());
		assertEquals(0, intervention0.getEntretienPc());
	}

	@Test(timeout = 4000)
	public void test63() throws Throwable {
		Float float0 = new Float((-382.0F));
		Intervention intervention0 = new Intervention(";aBs&b=Q/u9!%u|V", ";aBs&b=Q/u9!%u|V", (LocalDate) null,
				";aBs&b=Q/u9!%u|V", (LocalDate) null, float0, (LocalDate) null, float0, ";aBs&b=Q/u9!%u|V", float0,
				float0, float0, ";aBs&b=Q/u9!%u|V", ";aBs&b=Q/u9!%u|V", 0, 0);
		int int0 = intervention0.getEntretienPc();
		assertEquals(0, intervention0.getOrdures());
		assertEquals(0, int0);
	}

	@Test(timeout = 4000)
	public void test64() throws Throwable {
		Float float0 = new Float(616.8F);
		Intervention intervention0 = new Intervention(", \u00E9ductio=", ", \u00E9ductio=", (LocalDate) null,
				", \u00E9ductio=", (LocalDate) null, float0, (LocalDate) null, float0, ", \u00E9ductio=", float0,
				float0, float0, ", \u00E9ductio=", ", \u00E9ductio=", (-4), (-4));
		intervention0.setReduction(float0);
		assertEquals((-4), intervention0.getEntretienPc());
		assertEquals((-4), intervention0.getOrdures());
	}

	@Test(timeout = 4000)
	public void test65() throws Throwable {
		Float float0 = new Float(617.0F);
		Intervention intervention0 = new Intervention(";aBs&b=Q/u9!%u|V", "sVcSTFV12%5M@Y{n*", (LocalDate) null,
				";aBs&b=Q/u9!%u|V", (LocalDate) null, float0, (LocalDate) null, float0, ";aBs&b=Q/u9!%u|V", float0,
				float0, float0, ";aBs&b=Q/u9!%u|V", ";aBs&b=Q/u9!%u|V", 0, 0);
		intervention0.getMontantFacture();
		assertEquals(";aBs&b=Q/u9!%u|V", intervention0.getIdIntervention());
		assertEquals("sVcSTFV12%5M@Y{n*", intervention0.getIntitule());
		assertEquals(0, intervention0.getOrdures());
		assertEquals(";aBs&b=Q/u9!%u|V", intervention0.getNumDevis());
		assertEquals(0, intervention0.getEntretienPc());
		assertEquals(";aBs&b=Q/u9!%u|V", intervention0.getIdBatiment());
		assertEquals(";aBs&b=Q/u9!%u|V", intervention0.getIdOrganisme());
		assertEquals(";aBs&b=Q/u9!%u|V", intervention0.getNumFacture());
	}

	@Test(timeout = 4000)
	public void test66() throws Throwable {
		Float float0 = new Float(616.8F);
		Intervention intervention0 = new Intervention(", r\u00E9duction=", ", r\u00E9duction=", (LocalDate) null,
				", r\u00E9duction=", (LocalDate) null, float0, (LocalDate) null, float0, ", r\u00E9duction=", float0,
				float0, float0, ", r\u00E9duction=", ", r\u00E9duction=", 0, 0);
		intervention0.setOrdures(0);
		assertEquals(0, intervention0.getEntretienPc());
		assertEquals(0, intervention0.getOrdures());
	}

	@Test(timeout = 4000)
	public void test67() throws Throwable {
		Float float0 = new Float(616.8F);
		Intervention intervention0 = new Intervention(";aBs&b=Q/u9!%u|V", ";aBs&b=Q/u9!%u|V", (LocalDate) null,
				";aBs&b=Q/u9!%u|V", (LocalDate) null, float0, (LocalDate) null, float0, ";aBs&b=Q/u9!%u|V", float0,
				float0, float0, ";aBs&b=Q/u9!%u|V", ";aBs&b=Q/u9!%u|V", 0, 0);
		intervention0.setNumDevis(";aBs&b=Q/u9!%u|V");
		assertEquals(0, intervention0.getEntretienPc());
		assertEquals(0, intervention0.getOrdures());
	}
}
