/*
 * This file was automatically generated by EvoSuite
 * Fri Jan 16 14:03:17 GMT 2026
 */

package test.modele;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertTrue;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;

import modele.IRL;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class IRL_ESTest extends IRL_ESTest_scaffolding {

	@Test(timeout = 4000)
	public void test00() throws Throwable {
		IRL iRL0 = new IRL((-201), (-201), 0.0);
		iRL0.setAnnee(0);
		iRL0.setTrimestre(1036);
		IRL iRL1 = new IRL(0, 0, 0.0);
		boolean boolean0 = iRL0.equals(iRL1);
		assertEquals(0, iRL0.getAnnee());
		assertFalse(boolean0);
	}

	@Test(timeout = 4000)
	public void test01() throws Throwable {
		IRL iRL0 = new IRL(0, 0, 0);
		iRL0.setAnnee(1739);
		IRL iRL1 = new IRL(0, (-1657), 0);
		boolean boolean0 = iRL0.equals(iRL1);
		assertEquals(1739, iRL0.getAnnee());
		assertFalse(boolean0);
	}

	@Test(timeout = 4000)
	public void test02() throws Throwable {
		IRL iRL0 = new IRL(2, (-1), (-1));
		iRL0.setValeur(2);
		double double0 = iRL0.getValeur();
		assertEquals(2.0, double0, 0.01);
	}

	@Test(timeout = 4000)
	public void test03() throws Throwable {
		IRL iRL0 = new IRL((-1), (-1), (-1));
		double double0 = iRL0.getValeur();
		assertEquals((-1), iRL0.getAnnee());
		assertEquals((-1), iRL0.getTrimestre());
		assertEquals((-1.0), double0, 0.01);
	}

	@Test(timeout = 4000)
	public void test04() throws Throwable {
		IRL iRL0 = new IRL(1223, 0, 0);
		int int0 = iRL0.getTrimestre();
		assertEquals(0.0, iRL0.getValeur(), 0.01);
		assertEquals(1223, iRL0.getAnnee());
		assertEquals(0, int0);
	}

	@Test(timeout = 4000)
	public void test05() throws Throwable {
		IRL iRL0 = new IRL(2, (-1), (-1));
		int int0 = iRL0.getTrimestre();
		assertEquals((-1), int0);
		assertEquals((-1.0), iRL0.getValeur(), 0.01);
		assertEquals(2, iRL0.getAnnee());
	}

	@Test(timeout = 4000)
	public void test06() throws Throwable {
		IRL iRL0 = new IRL(0, 0, 0);
		int int0 = iRL0.getAnnee();
		assertEquals(0, iRL0.getTrimestre());
		assertEquals(0.0, iRL0.getValeur(), 0.01);
		assertEquals(0, int0);
	}

	@Test(timeout = 4000)
	public void test07() throws Throwable {
		IRL iRL0 = new IRL((-293), 2, (-2605.46019749));
		assertEquals((-293), iRL0.getAnnee());

		iRL0.setAnnee(2);
		int int0 = iRL0.getAnnee();
		assertEquals(2, int0);
	}

	@Test(timeout = 4000)
	public void test08() throws Throwable {
		IRL iRL0 = new IRL(1, 1, 1);
		IRL iRL1 = new IRL(1, 1, 1);
		boolean boolean0 = iRL0.equals(iRL1);
		assertEquals(1, iRL1.getTrimestre());
		assertEquals(1.0, iRL1.getValeur(), 0.01);
		assertTrue(boolean0);
		assertEquals(1, iRL1.getAnnee());
	}

	@Test(timeout = 4000)
	public void test09() throws Throwable {
		IRL iRL0 = new IRL((-201), (-201), 0.0);
		iRL0.setAnnee(0);
		IRL iRL1 = new IRL(0, 0, 0.0);
		boolean boolean0 = iRL0.equals(iRL1);
		assertEquals(0, iRL0.getAnnee());
		assertFalse(boolean0);
	}

	@Test(timeout = 4000)
	public void test10() throws Throwable {
		IRL iRL0 = new IRL((-201), (-201), 0.0);
		IRL iRL1 = new IRL(0, 0, 0.0);
		boolean boolean0 = iRL0.equals(iRL1);
		assertEquals((-201), iRL0.getTrimestre());
		assertEquals((-201), iRL0.getAnnee());
		assertEquals(0.0, iRL1.getValeur(), 0.01);
		assertFalse(boolean0);
	}

	@Test(timeout = 4000)
	public void test11() throws Throwable {
		IRL iRL0 = new IRL((-24), (-24), (-24));
		boolean boolean0 = iRL0.equals((Object) null);
		assertFalse(boolean0);
		assertEquals((-24), iRL0.getAnnee());
		assertEquals((-24.0), iRL0.getValeur(), 0.01);
		assertEquals((-24), iRL0.getTrimestre());
	}

	@Test(timeout = 4000)
	public void test12() throws Throwable {
		IRL iRL0 = new IRL(1, 1, 1);
		boolean boolean0 = iRL0.equals(iRL0);
		assertTrue(boolean0);
		assertEquals(1, iRL0.getTrimestre());
		assertEquals(1.0, iRL0.getValeur(), 0.01);
		assertEquals(1, iRL0.getAnnee());
	}

	@Test(timeout = 4000)
	public void test13() throws Throwable {
		IRL iRL0 = new IRL((-201), (-201), 0.0);
		Object object0 = new Object();
		boolean boolean0 = iRL0.equals(object0);
		assertFalse(boolean0);
		assertEquals((-201), iRL0.getTrimestre());
		assertEquals(0.0, iRL0.getValeur(), 0.01);
		assertEquals((-201), iRL0.getAnnee());
	}

	@Test(timeout = 4000)
	public void test14() throws Throwable {
		IRL iRL0 = new IRL((-201), (-201), 0.0);
		double double0 = iRL0.getValeur();
		assertEquals((-201), iRL0.getAnnee());
		assertEquals(0.0, double0, 0.01);
		assertEquals((-201), iRL0.getTrimestre());
	}

	@Test(timeout = 4000)
	public void test15() throws Throwable {
		IRL iRL0 = new IRL((-201), (-201), 0.0);
		String string0 = iRL0.toString();
		assertEquals("IRL [ann\u00E9e=-201, trimestre=-201, valeur=0.0]", string0);
	}

	@Test(timeout = 4000)
	public void test16() throws Throwable {
		IRL iRL0 = new IRL(1, 1, 1);
		iRL0.hashCode();
		assertEquals(1, iRL0.getTrimestre());
		assertEquals(1.0, iRL0.getValeur(), 0.01);
		assertEquals(1, iRL0.getAnnee());
	}

	@Test(timeout = 4000)
	public void test17() throws Throwable {
		IRL iRL0 = new IRL(1, 1, 1);
		int int0 = iRL0.getTrimestre();
		assertEquals(1, iRL0.getAnnee());
		assertEquals(1, int0);
		assertEquals(1.0, iRL0.getValeur(), 0.01);
	}

	@Test(timeout = 4000)
	public void test18() throws Throwable {
		IRL iRL0 = new IRL((-3331), (-3331), (-3331));
		int int0 = iRL0.getAnnee();
		assertEquals((-3331.0), iRL0.getValeur(), 0.01);
		assertEquals((-3331), iRL0.getTrimestre());
		assertEquals((-3331), int0);
	}
}
