/*
 * This file was automatically generated by EvoSuite
 * Fri Jan 16 14:05:42 GMT 2026
 */

package test.modele;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertNull;
import static org.junit.Assert.assertTrue;

import java.time.Clock;
import java.time.LocalDate;
import java.time.Period;
import java.time.ZoneOffset;
import java.time.chrono.IsoChronology;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.time.MockClock;
import org.evosuite.runtime.mock.java.time.MockLocalDate;
import org.evosuite.runtime.mock.java.time.chrono.MockIsoChronology;
import org.junit.Test;
import org.junit.runner.RunWith;

import modele.Locataire;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class Locataire_ESTest extends Locataire_ESTest_scaffolding {

	@Test(timeout = 4000)
	public void test00() throws Throwable {
		Period period0 = Period.ZERO;
		IsoChronology isoChronology0 = period0.getChronology();
		LocalDate localDate0 = MockIsoChronology.dateNow(isoChronology0);
		Locataire locataire0 = new Locataire("IX-lU5'N`A;#$>", "IX-lU5'N`A;#$>", "IX-lU5'N`A;#$>", "IX-lU5'N`A;#$>",
				"P_S", localDate0, "g$!2", "IX-lU5'N`A;#$>", "P_S", "IX-lU5'N`A;#$>");
		String string0 = locataire0.getVilleNaissance();
		assertEquals("P_S", locataire0.getMail());
		assertEquals("IX-lU5'N`A;#$>", locataire0.getPrenom());
		assertEquals("IX-lU5'N`A;#$>", locataire0.getNumTelephone());
		assertEquals("P_S", locataire0.getCodePostal());
		assertEquals("IX-lU5'N`A;#$>", locataire0.getIdLocataire());
		assertEquals("IX-lU5'N`A;#$>", locataire0.getNom());
		assertEquals("IX-lU5'N`A;#$>", locataire0.getVille());
		assertEquals("IX-lU5'N`A;#$>", locataire0.getAdresse());
		assertEquals("g$!2", string0);
	}

	@Test(timeout = 4000)
	public void test01() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Locataire locataire0 = new Locataire((String) null, (String) null, (String) null, (String) null, "", localDate0,
				(String) null, ":D", ":D", "");
		locataire0.setVilleNaissance("");
		locataire0.getVilleNaissance();
		assertEquals(":D", locataire0.getAdresse());
		assertEquals("", locataire0.getMail());
		assertEquals("", locataire0.getVille());
		assertEquals(":D", locataire0.getCodePostal());
	}

	@Test(timeout = 4000)
	public void test02() throws Throwable {
		LocalDate localDate0 = MockLocalDate.ofEpochDay(0L);
		Locataire locataire0 = new Locataire("&[", "iE=5BaO-ki.Io0H", "Ha0YuR+bhqZ,", "", (String) null, localDate0,
				"&[", "", (String) null, (String) null);
		String string0 = locataire0.getVille();
		assertEquals("", locataire0.getNumTelephone());
		assertEquals("&[", locataire0.getVilleNaissance());
		assertEquals("Ha0YuR+bhqZ,", locataire0.getPrenom());
		assertNull(string0);
		assertEquals("iE=5BaO-ki.Io0H", locataire0.getNom());
		assertEquals("", locataire0.getAdresse());
		assertEquals("&[", locataire0.getIdLocataire());
	}

	@Test(timeout = 4000)
	public void test03() throws Throwable {
		LocalDate localDate0 = MockLocalDate.ofEpochDay(0L);
		Locataire locataire0 = new Locataire("J&0ha/&76C!", "", "J&0ha/&76C!", "J&0ha/&76C!", "", localDate0, "$[t-c_0",
				", villeNaissance=", (String) null, "");
		String string0 = locataire0.getVille();
		assertEquals("", locataire0.getMail());
		assertEquals("", locataire0.getNom());
		assertEquals("J&0ha/&76C!", locataire0.getIdLocataire());
		assertEquals("$[t-c_0", locataire0.getVilleNaissance());
		assertEquals(", villeNaissance=", locataire0.getAdresse());
		assertNotNull(string0);
		assertEquals("J&0ha/&76C!", locataire0.getNumTelephone());
		assertEquals("J&0ha/&76C!", locataire0.getPrenom());
		assertEquals("", string0);
	}

	@Test(timeout = 4000)
	public void test04() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Locataire locataire0 = new Locataire("'", (String) null, (String) null, "'", "", localDate0, ">y", "=qk",
				"l0kj~IuZUg(f]T(G", "PTk#");
		String string0 = locataire0.getPrenom();
		assertEquals("", locataire0.getMail());
		assertEquals("PTk#", locataire0.getVille());
		assertEquals("'", locataire0.getNumTelephone());
		assertEquals(">y", locataire0.getVilleNaissance());
		assertEquals("l0kj~IuZUg(f]T(G", locataire0.getCodePostal());
		assertEquals("'", locataire0.getIdLocataire());
		assertEquals("=qk", locataire0.getAdresse());
		assertNull(string0);
	}

	@Test(timeout = 4000)
	public void test05() throws Throwable {
		LocalDate localDate0 = MockLocalDate.ofEpochDay(0L);
		Locataire locataire0 = new Locataire("G\"-^6?", "", "", "", "G\"-^6?", localDate0, "", "mj!VyLhf]fz8Z$x2 ",
				"mj!VyLhf]fz8Z$x2 ", (String) null);
		String string0 = locataire0.getPrenom();
		assertEquals("mj!VyLhf]fz8Z$x2 ", locataire0.getAdresse());
		assertEquals("G\"-^6?", locataire0.getMail());
		assertEquals("", locataire0.getNumTelephone());
		assertEquals("", locataire0.getVilleNaissance());
		assertEquals("mj!VyLhf]fz8Z$x2 ", locataire0.getCodePostal());
		assertEquals("", string0);
		assertEquals("", locataire0.getNom());
		assertNotNull(string0);
		assertEquals("G\"-^6?", locataire0.getIdLocataire());
	}

	@Test(timeout = 4000)
	public void test06() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Locataire locataire0 = new Locataire((String) null, (String) null, (String) null, (String) null, (String) null,
				localDate0, (String) null, ":D", ":D", (String) null);
		String string0 = locataire0.getNumTelephone();
		assertNull(string0);
	}

	@Test(timeout = 4000)
	public void test07() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Locataire locataire0 = new Locataire("MSv+~gqRGu)PM", "MSv+~gqRGu)PM", "MSv+~gqRGu)PM", "MSv+~gqRGu)PM",
				"MSv+~gqRGu)PM", localDate0, "MSv+~gqRGu)PM", "MSv+~gqRGu)PM", "MSv+~gqRGu)PM", "MSv+~gqRGu)PM");
		String string0 = locataire0.getNumTelephone();
		assertEquals("MSv+~gqRGu)PM", string0);
	}

	@Test(timeout = 4000)
	public void test08() throws Throwable {
		ZoneOffset zoneOffset0 = ZoneOffset.MIN;
		Clock clock0 = MockClock.system(zoneOffset0);
		LocalDate localDate0 = MockLocalDate.now(clock0);
		Locataire locataire0 = new Locataire("*F_X8aH6X#cD?", "*F_X8aH6X#cD?", "*F_X8aH6X#cD?", "59/", "*F_X8aH6X#cD?",
				localDate0, "", ", numTelephone=", "", ", numTelephone=");
		String string0 = locataire0.getNom();
		assertEquals("", locataire0.getCodePostal());
		assertEquals("*F_X8aH6X#cD?", locataire0.getPrenom());
		assertEquals("59/", locataire0.getNumTelephone());
		assertEquals(", numTelephone=", locataire0.getAdresse());
		assertEquals("*F_X8aH6X#cD?", locataire0.getIdLocataire());
		assertEquals("*F_X8aH6X#cD?", string0);
		assertEquals("", locataire0.getVilleNaissance());
		assertEquals("*F_X8aH6X#cD?", locataire0.getMail());
		assertEquals(", numTelephone=", locataire0.getVille());
	}

	@Test(timeout = 4000)
	public void test09() throws Throwable {
		LocalDate localDate0 = MockLocalDate.ofEpochDay(0L);
		Locataire locataire0 = new Locataire("G\"-^6?", "", "", "", "G\"-^6?", localDate0, "", "mj!VyLhf]fz8Z$x2 ",
				"mj!VyLhf]fz8Z$x2 ", (String) null);
		String string0 = locataire0.getNom();
		assertEquals("", string0);
		assertEquals("", locataire0.getVilleNaissance());
		assertEquals("mj!VyLhf]fz8Z$x2 ", locataire0.getCodePostal());
		assertEquals("mj!VyLhf]fz8Z$x2 ", locataire0.getAdresse());
		assertEquals("G\"-^6?", locataire0.getMail());
		assertEquals("", locataire0.getPrenom());
		assertEquals("G\"-^6?", locataire0.getIdLocataire());
		assertNotNull(string0);
		assertEquals("", locataire0.getNumTelephone());
	}

	@Test(timeout = 4000)
	public void test10() throws Throwable {
		LocalDate localDate0 = MockLocalDate.ofEpochDay(0L);
		Locataire locataire0 = new Locataire("&[", "iE=5BaO-ki.Io0H", "Ha0YuR+bhqZ,", "", (String) null, localDate0,
				"&[", "", (String) null, (String) null);
		String string0 = locataire0.getMail();
		assertEquals("Ha0YuR+bhqZ,", locataire0.getPrenom());
		assertEquals("&[", locataire0.getVilleNaissance());
		assertEquals("iE=5BaO-ki.Io0H", locataire0.getNom());
		assertEquals("", locataire0.getAdresse());
		assertNull(string0);
		assertEquals("", locataire0.getNumTelephone());
		assertEquals("&[", locataire0.getIdLocataire());
	}

	@Test(timeout = 4000)
	public void test11() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Locataire locataire0 = new Locataire((String) null, (String) null, (String) null, (String) null, "", localDate0,
				(String) null, ":D", ":D", "");
		String string0 = locataire0.getMail();
		assertNotNull(string0);
		assertEquals(":D", locataire0.getAdresse());
		assertEquals("", string0);
		assertEquals(":D", locataire0.getCodePostal());
		assertEquals("", locataire0.getVille());
	}

	@Test(timeout = 4000)
	public void test12() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Locataire locataire0 = new Locataire((String) null, (String) null, (String) null, (String) null, "", localDate0,
				(String) null, ":D", ":D", "");
		String string0 = locataire0.getIdLocataire();
		assertNull(string0);
		assertEquals(":D", locataire0.getCodePostal());
		assertEquals("", locataire0.getMail());
		assertEquals(":D", locataire0.getAdresse());
		assertEquals("", locataire0.getVille());
	}

	@Test(timeout = 4000)
	public void test13() throws Throwable {
		LocalDate localDate0 = MockLocalDate.ofEpochDay(0L);
		Locataire locataire0 = new Locataire("J&0ha/&76C!", "", "J&0ha/&76C!", "J&0ha/&76C!", "", localDate0, "$[t-c_0",
				", villeNaissance=", (String) null, "");
		assertEquals("J&0ha/&76C!", locataire0.getIdLocataire());

		locataire0.setIdLocataire("");
		locataire0.getIdLocataire();
		assertEquals("", locataire0.getVille());
	}

	@Test(timeout = 4000)
	public void test14() throws Throwable {
		LocalDate localDate0 = MockLocalDate.ofEpochDay(0L);
		Locataire locataire0 = new Locataire("J&0ha/&76C!", "", "J&0ha/&76C!", "J&0ha/&76C!", "", localDate0, "$[t-c_0",
				", villeNaissance=", (String) null, "");
		locataire0.getDateNaissance();
		assertEquals("", locataire0.getVille());
		assertEquals("J&0ha/&76C!", locataire0.getPrenom());
		assertEquals("J&0ha/&76C!", locataire0.getNumTelephone());
		assertEquals("$[t-c_0", locataire0.getVilleNaissance());
		assertEquals(", villeNaissance=", locataire0.getAdresse());
		assertEquals("J&0ha/&76C!", locataire0.getIdLocataire());
		assertEquals("", locataire0.getMail());
		assertEquals("", locataire0.getNom());
	}

	@Test(timeout = 4000)
	public void test15() throws Throwable {
		LocalDate localDate0 = MockLocalDate.ofEpochDay(0L);
		Locataire locataire0 = new Locataire("J&0ha/&76C!", "", "J&0ha/&76C!", "J&0ha/&76C!", "", localDate0, "$[t-c_0",
				", villeNaissance=", (String) null, "");
		locataire0.setCodePostal("J&0ha/&76C!");
		locataire0.getCodePostal();
		assertEquals(", villeNaissance=", locataire0.getAdresse());
		assertEquals("", locataire0.getMail());
		assertEquals("", locataire0.getNom());
		assertEquals("J&0ha/&76C!", locataire0.getNumTelephone());
		assertEquals("", locataire0.getVille());
		assertEquals("J&0ha/&76C!", locataire0.getPrenom());
		assertEquals("J&0ha/&76C!", locataire0.getIdLocataire());
		assertEquals("$[t-c_0", locataire0.getVilleNaissance());
	}

	@Test(timeout = 4000)
	public void test16() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Locataire locataire0 = new Locataire("+Sv+~gqRGu)|Mt", (String) null, (String) null, "[::d:34",
				"+Sv+~gqRGu)|Mt", localDate0, "", "[::d:34", "", "@&@9{kg{rM+hQ)WhB");
		String string0 = locataire0.getCodePostal();
		assertEquals("[::d:34", locataire0.getNumTelephone());
		assertEquals("+Sv+~gqRGu)|Mt", locataire0.getIdLocataire());
		assertEquals("", locataire0.getVilleNaissance());
		assertNotNull(string0);
		assertEquals("[::d:34", locataire0.getAdresse());
		assertEquals("@&@9{kg{rM+hQ)WhB", locataire0.getVille());
		assertEquals("+Sv+~gqRGu)|Mt", locataire0.getMail());
		assertEquals("", string0);
	}

	@Test(timeout = 4000)
	public void test17() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Locataire locataire0 = new Locataire((String) null, (String) null, "/t9&", "", (String) null, localDate0,
				"/t9&", (String) null, (String) null, "");
		String string0 = locataire0.getAdresse();
		assertEquals("", locataire0.getNumTelephone());
		assertEquals("/t9&", locataire0.getPrenom());
		assertEquals("", locataire0.getVille());
		assertNull(string0);
		assertEquals("/t9&", locataire0.getVilleNaissance());
	}

	@Test(timeout = 4000)
	public void test18() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Locataire locataire0 = new Locataire("+Sv+~gqRGu)|Mt", "+Sv+~gqRGu)|Mt", "", "", "", localDate0, "J%G7:", "",
				"", "");
		String string0 = locataire0.getAdresse();
		assertEquals("", locataire0.getVille());
		assertEquals("+Sv+~gqRGu)|Mt", locataire0.getIdLocataire());
		assertEquals("", locataire0.getCodePostal());
		assertEquals("", locataire0.getPrenom());
		assertEquals("", string0);
		assertEquals("", locataire0.getNumTelephone());
		assertEquals("J%G7:", locataire0.getVilleNaissance());
		assertEquals("+Sv+~gqRGu)|Mt", locataire0.getNom());
		assertEquals("", locataire0.getMail());
	}

	@Test(timeout = 4000)
	public void test19() throws Throwable {
		LocalDate localDate0 = MockLocalDate.ofEpochDay(0L);
		Locataire locataire0 = new Locataire("J&0ha/&76C!", "", "J&0ha/&76C!", "J&0ha/&76C!", "", localDate0, "$[t-c_0",
				", villeNaissance=", (String) null, "");
		Locataire locataire1 = new Locataire("&[", "iE=5BaO-ki.Io0H", "Ha0YuR+bhqZ,", "", (String) null, localDate0,
				"&[", "", (String) null, (String) null);
		boolean boolean0 = locataire0.equals(locataire1);
		assertEquals("J&0ha/&76C!", locataire0.getIdLocataire());
		assertEquals("Ha0YuR+bhqZ,", locataire1.getPrenom());
		assertEquals("J&0ha/&76C!", locataire0.getNumTelephone());
		assertEquals("iE=5BaO-ki.Io0H", locataire1.getNom());
		assertEquals("", locataire0.getMail());
		assertFalse(boolean0);
		assertEquals("", locataire0.getVille());
		assertEquals("J&0ha/&76C!", locataire0.getPrenom());
		assertEquals(", villeNaissance=", locataire0.getAdresse());
		assertEquals("", locataire1.getNumTelephone());
		assertEquals("&[", locataire1.getIdLocataire());
		assertEquals("$[t-c_0", locataire0.getVilleNaissance());
	}

	@Test(timeout = 4000)
	public void test20() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Locataire locataire0 = new Locataire("p3&6u?-59n}6F=<W", "p3&6u?-59n}6F=<W", "p3&6u?-59n}6F=<W",
				"p3&6u?-59n}6F=<W", "p3&6u?-59n}6F=<W", localDate0, "p3&6u?-59n}6F=<W", "p3&6u?-59n}6F=<W",
				"p3&6u?-59n}6F=<W", "p3&6u?-59n}6F=<W");
		boolean boolean0 = locataire0.equals((Object) null);
		assertFalse(boolean0);
	}

	@Test(timeout = 4000)
	public void test21() throws Throwable {
		LocalDate localDate0 = MockLocalDate.ofEpochDay(0L);
		Locataire locataire0 = new Locataire("J&0ha/&76C!", "", "J&0ha/&76C!", "J&0ha/&76C!", "", localDate0, "$[t-c_0",
				", villeNaissance=", (String) null, "");
		boolean boolean0 = locataire0.equals(locataire0);
		assertEquals("", locataire0.getNom());
		assertEquals(", villeNaissance=", locataire0.getAdresse());
		assertEquals("J&0ha/&76C!", locataire0.getNumTelephone());
		assertEquals("$[t-c_0", locataire0.getVilleNaissance());
		assertEquals("J&0ha/&76C!", locataire0.getPrenom());
		assertEquals("J&0ha/&76C!", locataire0.getIdLocataire());
		assertEquals("", locataire0.getVille());
		assertEquals("", locataire0.getMail());
		assertTrue(boolean0);
	}

	@Test(timeout = 4000)
	public void test22() throws Throwable {
		LocalDate localDate0 = MockLocalDate.ofEpochDay(0L);
		Locataire locataire0 = new Locataire("J&0ha/&76C!", "", "J&0ha/&76C!", "J&0ha/&76C!", "", localDate0, "$[t-c_0",
				", villeNaissance=", (String) null, "");
		boolean boolean0 = locataire0.equals("");
		assertEquals("J&0ha/&76C!", locataire0.getIdLocataire());
		assertEquals("J&0ha/&76C!", locataire0.getNumTelephone());
		assertFalse(boolean0);
		assertEquals("", locataire0.getNom());
		assertEquals("J&0ha/&76C!", locataire0.getPrenom());
		assertEquals(", villeNaissance=", locataire0.getAdresse());
		assertEquals("$[t-c_0", locataire0.getVilleNaissance());
		assertEquals("", locataire0.getMail());
		assertEquals("", locataire0.getVille());
	}

	@Test(timeout = 4000)
	public void test23() throws Throwable {
		LocalDate localDate0 = MockLocalDate.ofEpochDay(0L);
		Locataire locataire0 = new Locataire("J&0ha/&76C!", "", "J&0ha/&76C!", "J&0ha/&76C!", "", localDate0, "$[t-c_0",
				", villeNaissance=", (String) null, "");
		assertEquals("J&0ha/&76C!", locataire0.getPrenom());

		locataire0.setPrenom("");
		assertEquals("$[t-c_0", locataire0.getVilleNaissance());
	}

	@Test(timeout = 4000)
	public void test24() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Locataire locataire0 = new Locataire((String) null, (String) null, (String) null, (String) null, (String) null,
				localDate0, (String) null, ":D", ":D", (String) null);
		locataire0.hashCode();
	}

	@Test(timeout = 4000)
	public void test25() throws Throwable {
		Locataire locataire0 = new Locataire("", "", ", numTelephone=", "", "", (LocalDate) null, "(m/ds0IiQ", "", "",
				"(m/ds0IiQ");
		String string0 = locataire0.getNumTelephone();
		assertEquals("", string0);
		assertEquals(", numTelephone=", locataire0.getPrenom());
		assertEquals("(m/ds0IiQ", locataire0.getVille());
		assertEquals("", locataire0.getNom());
		assertEquals("", locataire0.getMail());
		assertEquals("(m/ds0IiQ", locataire0.getVilleNaissance());
		assertEquals("", locataire0.getCodePostal());
		assertEquals("", locataire0.getIdLocataire());
		assertEquals("", locataire0.getAdresse());
	}

	@Test(timeout = 4000)
	public void test26() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Locataire locataire0 = new Locataire((String) null, (String) null, (String) null, (String) null, (String) null,
				localDate0, (String) null, (String) null, "", (String) null);
		String string0 = locataire0.getNom();
		assertNull(string0);
	}

	@Test(timeout = 4000)
	public void test27() throws Throwable {
		Locataire locataire0 = new Locataire("", "", ", numTelephone=", "", "", (LocalDate) null, "(m/ds0IiQ", "", "",
				"(m/ds0IiQ");
		assertEquals("", locataire0.getMail());

		locataire0.setMail(", numTelephone=");
		assertEquals("(m/ds0IiQ", locataire0.getVille());
	}

	@Test(timeout = 4000)
	public void test28() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Locataire locataire0 = new Locataire("", "", "", "", "", localDate0, "", "", "", "");
		locataire0.setNom("");
		assertEquals("", locataire0.getVilleNaissance());
	}

	@Test(timeout = 4000)
	public void test29() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Locataire locataire0 = new Locataire("MS-\"}v+~gqRGu)PM", "MS-\"}v+~gqRGu)PM", "MS-\"}v+~gqRGu)PM",
				"MS-\"}v+~gqRGu)PM", "MS-\"}v+~gqRGu)PM", localDate0, "MS-\"}v+~gqRGu)PM", "MS-\"}v+~gqRGu)PM",
				"MS-\"}v+~gqRGu)PM", "MS-\"}v+~gqRGu)PM");
		String string0 = locataire0.getAdresse();
		assertEquals("MS-\"}v+~gqRGu)PM", string0);
	}

	@Test(timeout = 4000)
	public void test30() throws Throwable {
		LocalDate localDate0 = MockLocalDate.ofEpochDay(0L);
		Locataire locataire0 = new Locataire("J&0ha/&76C!", "", "J&0ha/&76C!", "J&0ha/&76C!", "", localDate0, "$[t-c_0",
				", villeNaissance=", (String) null, "");
		assertEquals("", locataire0.getVille());

		locataire0.setVille((String) null);
		assertEquals("", locataire0.getMail());
		assertEquals(", villeNaissance=", locataire0.getAdresse());
		assertEquals("J&0ha/&76C!", locataire0.getIdLocataire());
		assertEquals("J&0ha/&76C!", locataire0.getPrenom());
		assertEquals("J&0ha/&76C!", locataire0.getNumTelephone());
		assertEquals("$[t-c_0", locataire0.getVilleNaissance());
		assertEquals("", locataire0.getNom());
	}

	@Test(timeout = 4000)
	public void test31() throws Throwable {
		LocalDate localDate0 = MockLocalDate.ofEpochDay(0L);
		Locataire locataire0 = new Locataire("J&0ha/&76C!", "", "J&0ha/&76C!", "J&0ha/&76C!", "", localDate0, "$[t-c_0",
				", villeNaissance=", (String) null, "");
		String string0 = locataire0.getCodePostal();
		assertEquals("$[t-c_0", locataire0.getVilleNaissance());
		assertNull(string0);
		assertEquals("J&0ha/&76C!", locataire0.getNumTelephone());
		assertEquals("J&0ha/&76C!", locataire0.getIdLocataire());
		assertEquals("", locataire0.getNom());
		assertEquals("", locataire0.getMail());
		assertEquals("", locataire0.getVille());
		assertEquals("J&0ha/&76C!", locataire0.getPrenom());
		assertEquals(", villeNaissance=", locataire0.getAdresse());
	}

	@Test(timeout = 4000)
	public void test32() throws Throwable {
		LocalDate localDate0 = MockLocalDate.ofEpochDay(0L);
		Locataire locataire0 = new Locataire("J&0ha/&76C!", "", "J&0ha/&76C!", "J&0ha/&76C!", "", localDate0, "$[t-c_0",
				", villeNaissance=", (String) null, "");
		String string0 = locataire0.getIdLocataire();
		assertEquals("$[t-c_0", locataire0.getVilleNaissance());
		assertEquals("J&0ha/&76C!", string0);
		assertEquals("J&0ha/&76C!", locataire0.getNumTelephone());
		assertEquals("", locataire0.getNom());
		assertEquals("", locataire0.getVille());
		assertEquals("", locataire0.getMail());
		assertNotNull(string0);
		assertEquals("J&0ha/&76C!", locataire0.getPrenom());
		assertEquals(", villeNaissance=", locataire0.getAdresse());
	}

	@Test(timeout = 4000)
	public void test33() throws Throwable {
		Locataire locataire0 = new Locataire("", "", ", numTelephone=", "", "", (LocalDate) null, "(m/ds0IiQ", "", "",
				"(m/ds0IiQ");
		assertEquals("", locataire0.getNumTelephone());

		locataire0.setNumTelephone("");
		assertEquals("", locataire0.getNom());
		assertEquals("", locataire0.getMail());
		assertEquals("", locataire0.getCodePostal());
		assertEquals("(m/ds0IiQ", locataire0.getVille());
		assertEquals("", locataire0.getAdresse());
		assertEquals(", numTelephone=", locataire0.getPrenom());
		assertEquals("", locataire0.getIdLocataire());
		assertEquals("(m/ds0IiQ", locataire0.getVilleNaissance());
	}

	@Test(timeout = 4000)
	public void test34() throws Throwable {
		Locataire locataire0 = new Locataire("", "", ", numTelephone=", "", "", (LocalDate) null, "(m/ds0IiQ", "", "",
				"(m/ds0IiQ");
		assertEquals("", locataire0.getAdresse());

		locataire0.setAdresse("Locataire [idLocataire=");
		assertEquals("", locataire0.getIdLocataire());
	}

	@Test(timeout = 4000)
	public void test35() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Locataire locataire0 = new Locataire((String) null, (String) null, (String) null, (String) null, (String) null,
				localDate0, (String) null, ":D", ":D", (String) null);
		String string0 = locataire0.getVilleNaissance();
		assertNull(string0);
	}

	@Test(timeout = 4000)
	public void test36() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Locataire locataire0 = new Locataire("+Sv+~gqRGu)|Mt", "+Sv+~gqRGu)|Mt", "+Sv+~gqRGu)|Mt", "+Sv+~gqRGu)|Mt",
				"+Sv+~gqRGu)|Mt", localDate0, "+Sv+~gqRGu)|Mt", "+Sv+~gqRGu)|Mt", "+Sv+~gqRGu)|Mt", "+Sv+~gqRGu)|Mt");
		String string0 = locataire0.getPrenom();
		assertEquals("+Sv+~gqRGu)|Mt", string0);
	}

	@Test(timeout = 4000)
	public void test37() throws Throwable {
		Locataire locataire0 = new Locataire("", "", ", numTelephone=", "", "", (LocalDate) null, "(m/ds0IiQ", "", "",
				"(m/ds0IiQ");
		locataire0.getDateNaissance();
		assertEquals("", locataire0.getCodePostal());
		assertEquals("", locataire0.getAdresse());
		assertEquals("(m/ds0IiQ", locataire0.getVilleNaissance());
		assertEquals("", locataire0.getNom());
		assertEquals(", numTelephone=", locataire0.getPrenom());
		assertEquals("", locataire0.getMail());
		assertEquals("(m/ds0IiQ", locataire0.getVille());
		assertEquals("", locataire0.getIdLocataire());
		assertEquals("", locataire0.getNumTelephone());
	}

	@Test(timeout = 4000)
	public void test38() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Locataire locataire0 = new Locataire((String) null, (String) null, "\"j^aSZ$4AWU", (String) null, "",
				localDate0, "\"j^aSZ$4AWU", ", dateNaissance=", "", (String) null);
		String string0 = locataire0.toString();
		assertEquals(
				"Locataire [idLocataire=null, nom=null, pr\u00E9nom=\"j^aSZ$4AWU, numTelephone=null, mail=, dateNaissance=2014-02-14, villeNaissance=\"j^aSZ$4AWU, adresse=, dateNaissance=, codePostal=, ville=null]",
				string0);
	}

	@Test(timeout = 4000)
	public void test39() throws Throwable {
		Locataire locataire0 = new Locataire("", "", ", numTelephone=", "", "", (LocalDate) null, "(m/ds0IiQ", "", "",
				"(m/ds0IiQ");
		locataire0.setDateNaissance((LocalDate) null);
		assertEquals("", locataire0.getNumTelephone());
		assertEquals("", locataire0.getCodePostal());
		assertEquals("", locataire0.getMail());
		assertEquals("(m/ds0IiQ", locataire0.getVille());
		assertEquals("", locataire0.getAdresse());
		assertEquals("", locataire0.getNom());
		assertEquals("(m/ds0IiQ", locataire0.getVilleNaissance());
		assertEquals("", locataire0.getIdLocataire());
		assertEquals(", numTelephone=", locataire0.getPrenom());
	}

	@Test(timeout = 4000)
	public void test40() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Locataire locataire0 = new Locataire("+Sv+~@qRGu)|Mt", "+Sv+~@qRGu)|Mt", "+Sv+~@qRGu)|Mt", "+Sv+~@qRGu)|Mt",
				"+Sv+~@qRGu)|Mt", localDate0, "+Sv+~@qRGu)|Mt", "+Sv+~@qRGu)|Mt", "+Sv+~@qRGu)|Mt", "+Sv+~@qRGu)|Mt");
		String string0 = locataire0.getVille();
		assertEquals("+Sv+~@qRGu)|Mt", string0);
	}

	@Test(timeout = 4000)
	public void test41() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Locataire locataire0 = new Locataire("+Sv+~gqRGu)|Mt", "+Sv+~gqRGu)|Mt", "+Sv+~gqRGu)|Mt", "+Sv+~gqRGu)|Mt",
				"+Sv+~gqRGu)|Mt", localDate0, "+Sv+~gqRGu)|Mt", "+Sv+~gqRGu)|Mt", "+Sv+~gqRGu)|Mt", "+Sv+~gqRGu)|Mt");
		String string0 = locataire0.getMail();
		assertEquals("+Sv+~gqRGu)|Mt", string0);
	}
}
