/*
 * This file was automatically generated by EvoSuite
 * Fri Jan 16 14:08:32 GMT 2026
 */

package test.modele;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertNull;
import static org.junit.Assert.assertTrue;

import java.time.LocalDate;
import java.time.Period;
import java.time.ZoneId;
import java.time.ZoneOffset;
import java.time.chrono.IsoChronology;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.time.MockLocalDate;
import org.evosuite.runtime.mock.java.time.chrono.MockIsoChronology;
import org.junit.Test;
import org.junit.runner.RunWith;

import modele.Louer;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class Louer_ESTest extends Louer_ESTest_scaffolding {

	@Test(timeout = 4000)
	public void test00() throws Throwable {
		ZoneOffset zoneOffset0 = ZoneOffset.ofTotalSeconds(3874);
		LocalDate localDate0 = MockLocalDate.now((ZoneId) zoneOffset0);
		Float float0 = new Float((-626.2075F));
		Period period0 = Period.of(2265, (-392), (-2624));
		IsoChronology isoChronology0 = period0.getChronology();
		LocalDate localDate1 = MockIsoChronology.dateNow(isoChronology0, (ZoneId) zoneOffset0);
		Louer louer0 = new Louer(localDate1, localDate1, (-2419), localDate0, localDate1, "Louer [dateD\u00E9but=",
				"#@wi\"OaC7Fp?=_A.", ";PLj_", (String) null, "]", localDate1, float0, localDate1, ",~JG7uB\"0OVF", 0,
				localDate0);
		assertEquals((-2419.0F), louer0.getDepotDeGarantie(), 0.01F);
		assertEquals(";PLj_", louer0.getIdLocataire());
		assertEquals("]", louer0.getIdGarant());
		assertEquals(0, louer0.getRevolue());
		assertEquals(",~JG7uB\"0OVF", louer0.getIdLogementAssocie());
		assertEquals("Louer [dateD\u00E9but=", louer0.getDetailsEtatDesLieuxEntree());
		assertEquals("#@wi\"OaC7Fp?=_A.", louer0.getDetailsEtatDesLieuxSortie());
	}

	@Test(timeout = 4000)
	public void test01() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Float float0 = new Float((-1495.9097F));
		LocalDate localDate1 = MockLocalDate.now();
		Louer louer0 = new Louer(localDate1, localDate0, 1.0F, localDate1, localDate0, "MNFpP)w^fAZ", "ivM-FP_Yl3Z^3pc",
				"", "sVs[K@}<=km6h", "sVs[K@}<=km6h", localDate1, float0, localDate1, "modele.Louer", (-2419),
				localDate1);
		assertEquals(1.0F, louer0.getDepotDeGarantie(), 0.01F);
		assertEquals("MNFpP)w^fAZ", louer0.getDetailsEtatDesLieuxEntree());
		assertEquals("sVs[K@}<=km6h", louer0.getIdBienLouable());
		assertEquals("", louer0.getIdLocataire());
		assertEquals("ivM-FP_Yl3Z^3pc", louer0.getDetailsEtatDesLieuxSortie());
		assertEquals("sVs[K@}<=km6h", louer0.getIdGarant());
		assertEquals("modele.Louer", louer0.getIdLogementAssocie());
		assertEquals((-2419), louer0.getRevolue());
	}

	@Test(timeout = 4000)
	public void test02() throws Throwable {
		ZoneOffset zoneOffset0 = ZoneOffset.ofTotalSeconds(3874);
		LocalDate localDate0 = MockLocalDate.now((ZoneId) zoneOffset0);
		Float float0 = new Float((-626.2075F));
		Period period0 = Period.of(2265, (-392), (-2624));
		IsoChronology isoChronology0 = period0.getChronology();
		LocalDate localDate1 = MockIsoChronology.dateNow(isoChronology0, (ZoneId) zoneOffset0);
		Louer louer0 = new Louer(localDate1, localDate1, 3874, localDate0, localDate0, "", "#@wi\"OaC7Fp?=_A.",
				(String) null, "]", "0NpUGW-{n", localDate0, float0, localDate0, (String) null, 0, localDate0);
		assertEquals("", louer0.getDetailsEtatDesLieuxEntree());
		assertEquals(0, louer0.getRevolue());
		assertEquals(3874.0F, louer0.getDepotDeGarantie(), 0.01F);
		assertEquals("0NpUGW-{n", louer0.getIdGarant());
		assertEquals("]", louer0.getIdBienLouable());
		assertEquals("#@wi\"OaC7Fp?=_A.", louer0.getDetailsEtatDesLieuxSortie());
	}

	@Test(timeout = 4000)
	public void test03() throws Throwable {
		Float float0 = new Float((double) 519.3333F);
		Louer louer0 = new Louer((LocalDate) null, (LocalDate) null, 519.3333F, (LocalDate) null, (LocalDate) null,
				", dateEtatDesLieuxSortie=", "yAL?D", "", "n#c%;tVjzZ", "", (LocalDate) null, float0, (LocalDate) null,
				"", 0, (LocalDate) null);
		int int0 = louer0.getRevolue();
		assertEquals("yAL?D", louer0.getDetailsEtatDesLieuxSortie());
		assertEquals(", dateEtatDesLieuxSortie=", louer0.getDetailsEtatDesLieuxEntree());
		assertEquals("", louer0.getIdLocataire());
		assertEquals("n#c%;tVjzZ", louer0.getIdBienLouable());
		assertEquals("", louer0.getIdGarant());
		assertEquals(0, int0);
		assertEquals("", louer0.getIdLogementAssocie());
		assertEquals(519.3333F, louer0.getDepotDeGarantie(), 0.01F);
	}

	@Test(timeout = 4000)
	public void test04() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Float float0 = new Float((-3243.087F));
		Louer louer0 = new Louer(localDate0, localDate0, (-3243.087F), localDate0, localDate0, (String) null,
				(String) null, (String) null, (String) null, (String) null, localDate0, float0, localDate0,
				(String) null, 2677, localDate0);
		int int0 = louer0.getRevolue();
		assertEquals((-3243.087F), louer0.getDepotDeGarantie(), 0.01F);
		assertEquals(2677, int0);
	}

	@Test(timeout = 4000)
	public void test05() throws Throwable {
		Float float0 = new Float((double) 1374.1001F);
		Louer louer0 = new Louer((LocalDate) null, (LocalDate) null, 1374.1001F, (LocalDate) null, (LocalDate) null, "",
				"", "QV*eYLlo|!r@L4", "ex7JJ)~h<1xKx0I", "", (LocalDate) null, float0, (LocalDate) null, ", dateFin=",
				185, (LocalDate) null);
		louer0.getMoisFinAjustement();
		assertEquals("", louer0.getDetailsEtatDesLieuxEntree());
		assertEquals("", louer0.getIdGarant());
		assertEquals(1374.1001F, louer0.getDepotDeGarantie(), 0.01F);
		assertEquals(", dateFin=", louer0.getIdLogementAssocie());
		assertEquals("", louer0.getDetailsEtatDesLieuxSortie());
		assertEquals("ex7JJ)~h<1xKx0I", louer0.getIdBienLouable());
		assertEquals("QV*eYLlo|!r@L4", louer0.getIdLocataire());
		assertEquals(185, louer0.getRevolue());
	}

	@Test(timeout = 4000)
	public void test06() throws Throwable {
		Period period0 = Period.ZERO;
		IsoChronology isoChronology0 = period0.getChronology();
		LocalDate localDate0 = MockIsoChronology.dateNow(isoChronology0);
		Float float0 = new Float((-1482.2593F));
		Louer louer0 = new Louer(localDate0, localDate0, 0.0F, localDate0, localDate0, (String) null, (String) null,
				(String) null, (String) null, (String) null, localDate0, float0, localDate0,
				", dateEtatDesLieuxEntr\u00E9e=", 1, localDate0);
		louer0.getMoisDebutAjustement();
		assertEquals(0.0F, louer0.getDepotDeGarantie(), 0.01F);
		assertEquals(1, louer0.getRevolue());
	}

	@Test(timeout = 4000)
	public void test07() throws Throwable {
		Float float0 = new Float((double) 1374.1001F);
		Louer louer0 = new Louer((LocalDate) null, (LocalDate) null, 1374.1001F, (LocalDate) null, (LocalDate) null, "",
				"", "QV*eYLlo|!r@L4", "ex7JJ)~h<1xKx0I", "", (LocalDate) null, float0, (LocalDate) null, ", dateFin=",
				185, (LocalDate) null);
		String string0 = louer0.getIdLogementAssocie();
		assertEquals("", louer0.getDetailsEtatDesLieuxEntree());
		assertEquals(1374.1001F, louer0.getDepotDeGarantie(), 0.01F);
		assertEquals("", louer0.getDetailsEtatDesLieuxSortie());
		assertEquals("ex7JJ)~h<1xKx0I", louer0.getIdBienLouable());
		assertEquals("", louer0.getIdGarant());
		assertEquals(", dateFin=", string0);
		assertEquals(185, louer0.getRevolue());
		assertEquals("QV*eYLlo|!r@L4", louer0.getIdLocataire());
	}

	@Test(timeout = 4000)
	public void test08() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Float float0 = new Float(0.0F);
		Louer louer0 = new Louer(localDate0, localDate0, 0.0F, localDate0, localDate0, "Dlx-?X}^'=>8,f)6V",
				"Dlx-?X}^'=>8,f)6V", "", "Dlx-?X}^'=>8,f)6V", "Dlx-?X}^'=>8,f)6V", localDate0, float0, localDate0, "",
				(-2591), localDate0);
		String string0 = louer0.getIdLogementAssocie();
		assertEquals("", louer0.getIdLocataire());
		assertEquals("Dlx-?X}^'=>8,f)6V", louer0.getDetailsEtatDesLieuxEntree());
		assertEquals("", string0);
		assertEquals("Dlx-?X}^'=>8,f)6V", louer0.getIdBienLouable());
		assertEquals(0.0F, louer0.getDepotDeGarantie(), 0.01F);
		assertEquals((-2591), louer0.getRevolue());
		assertEquals("Dlx-?X}^'=>8,f)6V", louer0.getDetailsEtatDesLieuxSortie());
		assertEquals("Dlx-?X}^'=>8,f)6V", louer0.getIdGarant());
	}

	@Test(timeout = 4000)
	public void test09() throws Throwable {
		Period period0 = Period.ZERO;
		IsoChronology isoChronology0 = period0.getChronology();
		LocalDate localDate0 = MockIsoChronology.dateNow(isoChronology0);
		Float float0 = new Float((-1482.2593F));
		Louer louer0 = new Louer(localDate0, localDate0, 0.0F, localDate0, localDate0, (String) null, (String) null,
				(String) null, (String) null, (String) null, localDate0, float0, localDate0,
				", dateEtatDesLieuxEntr\u00E9e=", 1, localDate0);
		String string0 = louer0.getIdLocataire();
		assertEquals(1, louer0.getRevolue());
		assertEquals(0.0F, louer0.getDepotDeGarantie(), 0.01F);
		assertNull(string0);
	}

	@Test(timeout = 4000)
	public void test10() throws Throwable {
		Float float0 = new Float(0.0);
		Louer louer0 = new Louer((LocalDate) null, (LocalDate) null, (-1362.1342F), (LocalDate) null, (LocalDate) null,
				"7>ohHf^&CF<X", "[8f3qnKK/C~=", "[8f3qnKK/C~=", ",J", "4<vJ", (LocalDate) null, float0,
				(LocalDate) null, "*~x+;OA'x[p", 2, (LocalDate) null);
		String string0 = louer0.getIdLocataire();
		assertEquals("[8f3qnKK/C~=", louer0.getDetailsEtatDesLieuxSortie());
		assertEquals(2, louer0.getRevolue());
		assertEquals("7>ohHf^&CF<X", louer0.getDetailsEtatDesLieuxEntree());
		assertEquals("[8f3qnKK/C~=", string0);
		assertEquals((-1362.1342F), louer0.getDepotDeGarantie(), 0.01F);
		assertEquals("*~x+;OA'x[p", louer0.getIdLogementAssocie());
		assertEquals("4<vJ", louer0.getIdGarant());
		assertEquals(",J", louer0.getIdBienLouable());
	}

	@Test(timeout = 4000)
	public void test11() throws Throwable {
		ZoneOffset zoneOffset0 = ZoneOffset.ofTotalSeconds(3874);
		LocalDate localDate0 = MockLocalDate.now((ZoneId) zoneOffset0);
		Float float0 = new Float(0.0F);
		Louer louer0 = new Louer(localDate0, localDate0, (-1.0F), localDate0, localDate0, "*Wn|#%9", "*Wn|#%9", "y",
				"]", "y", localDate0, float0, localDate0, "y", (-2419), localDate0);
		String string0 = louer0.getIdGarant();
		assertEquals("*Wn|#%9", louer0.getDetailsEtatDesLieuxSortie());
		assertEquals("]", louer0.getIdBienLouable());
		assertEquals("y", string0);
		assertEquals("y", louer0.getIdLocataire());
		assertEquals("*Wn|#%9", louer0.getDetailsEtatDesLieuxEntree());
		assertEquals((-1.0F), louer0.getDepotDeGarantie(), 0.01F);
		assertEquals("y", louer0.getIdLogementAssocie());
		assertEquals((-2419), louer0.getRevolue());
	}

	@Test(timeout = 4000)
	public void test12() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Float float0 = new Float(2529.0657F);
		Louer louer0 = new Louer(localDate0, localDate0, 2529.0657F, localDate0, localDate0, "", "", "", "", "",
				localDate0, float0, localDate0, "", (-2205), localDate0);
		louer0.getIdGarant();
		assertEquals((-2205), louer0.getRevolue());
		assertEquals(2529.0657F, louer0.getDepotDeGarantie(), 0.01F);
	}

	@Test(timeout = 4000)
	public void test13() throws Throwable {
		ZoneOffset zoneOffset0 = ZoneOffset.ofTotalSeconds(3874);
		LocalDate localDate0 = MockLocalDate.now((ZoneId) zoneOffset0);
		Float float0 = new Float((float) 3874);
		Louer louer0 = new Louer(localDate0, localDate0, 3874, localDate0, localDate0, ",~JG7uB\"0OVF",
				",~JG7uB\"0OVF", ",~JG7uB\"0OVF", "]", ",~JG7uB\"0OVF", localDate0, float0, localDate0, "]", (-2419),
				localDate0);
		String string0 = louer0.getIdBienLouable();
		assertEquals(3874.0F, louer0.getDepotDeGarantie(), 0.01F);
		assertEquals(",~JG7uB\"0OVF", louer0.getIdLocataire());
		assertEquals(",~JG7uB\"0OVF", louer0.getIdGarant());
		assertEquals("]", string0);
		assertEquals((-2419), louer0.getRevolue());
		assertEquals("]", louer0.getIdLogementAssocie());
		assertEquals(",~JG7uB\"0OVF", louer0.getDetailsEtatDesLieuxEntree());
		assertEquals(",~JG7uB\"0OVF", louer0.getDetailsEtatDesLieuxSortie());
	}

	@Test(timeout = 4000)
	public void test14() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Float float0 = new Float(2529.0657F);
		Louer louer0 = new Louer(localDate0, localDate0, 2529.0657F, localDate0, localDate0, "", "", "", "", "",
				localDate0, float0, localDate0, "", (-2205), localDate0);
		louer0.getIdBienLouable();
		assertEquals((-2205), louer0.getRevolue());
		assertEquals(2529.0657F, louer0.getDepotDeGarantie(), 0.01F);
	}

	@Test(timeout = 4000)
	public void test15() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Float float0 = new Float((-3243.087F));
		Louer louer0 = new Louer(localDate0, localDate0, (-3243.087F), localDate0, localDate0, (String) null,
				(String) null, (String) null, (String) null, (String) null, localDate0, float0, localDate0,
				(String) null, 2677, localDate0);
		louer0.getDetailsEtatDesLieuxSortie();
		assertEquals((-3243.087F), louer0.getDepotDeGarantie(), 0.01F);
		assertEquals(2677, louer0.getRevolue());
	}

	@Test(timeout = 4000)
	public void test16() throws Throwable {
		Float float0 = Float.valueOf((-730.93115F));
		Louer louer0 = new Louer((LocalDate) null, (LocalDate) null, (-730.93115F), (LocalDate) null, (LocalDate) null,
				"sR8h'", "c01=QBONC[9n\"FL", "", "", "o^1zm/bpf04yh!rS", (LocalDate) null, float0, (LocalDate) null,
				"modele.Louer", 3335, (LocalDate) null);
		String string0 = louer0.getDetailsEtatDesLieuxSortie();
		assertEquals("", louer0.getIdLocataire());
		assertEquals("modele.Louer", louer0.getIdLogementAssocie());
		assertEquals("o^1zm/bpf04yh!rS", louer0.getIdGarant());
		assertEquals("c01=QBONC[9n\"FL", string0);
		assertEquals("sR8h'", louer0.getDetailsEtatDesLieuxEntree());
		assertEquals("", louer0.getIdBienLouable());
		assertEquals(3335, louer0.getRevolue());
		assertEquals((-730.93115F), louer0.getDepotDeGarantie(), 0.01F);
	}

	@Test(timeout = 4000)
	public void test17() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Float float0 = new Float((-3243.087F));
		Louer louer0 = new Louer(localDate0, localDate0, (-3243.087F), localDate0, localDate0, (String) null,
				(String) null, (String) null, (String) null, (String) null, localDate0, float0, localDate0,
				(String) null, 2677, localDate0);
		louer0.getDetailsEtatDesLieuxEntree();
		assertEquals(2677, louer0.getRevolue());
		assertEquals((-3243.087F), louer0.getDepotDeGarantie(), 0.01F);
	}

	@Test(timeout = 4000)
	public void test18() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Float float0 = new Float((-1.0F));
		Louer louer0 = new Louer(localDate0, localDate0, (-2787.009F), localDate0, localDate0, "{#c2a^ug", "", "", "",
				"", localDate0, float0, localDate0, "{#c2a^ug", 2, localDate0);
		String string0 = louer0.getDetailsEtatDesLieuxEntree();
		assertEquals("{#c2a^ug", louer0.getIdLogementAssocie());
		assertEquals("", louer0.getDetailsEtatDesLieuxSortie());
		assertEquals("{#c2a^ug", string0);
		assertEquals((-2787.009F), louer0.getDepotDeGarantie(), 0.01F);
		assertEquals("", louer0.getIdBienLouable());
		assertEquals(2, louer0.getRevolue());
		assertEquals("", louer0.getIdLocataire());
		assertEquals("", louer0.getIdGarant());
	}

	@Test(timeout = 4000)
	public void test19() throws Throwable {
		Period period0 = Period.ZERO;
		IsoChronology isoChronology0 = period0.getChronology();
		LocalDate localDate0 = MockIsoChronology.dateNow(isoChronology0);
		Float float0 = new Float((-1482.2593F));
		Louer louer0 = new Louer(localDate0, localDate0, 0.0F, localDate0, localDate0, (String) null, (String) null,
				(String) null, (String) null, (String) null, localDate0, float0, localDate0,
				", dateEtatDesLieuxEntr\u00E9e=", 1, localDate0);
		float float1 = louer0.getDepotDeGarantie();
		assertEquals(1, louer0.getRevolue());
		assertEquals(0.0F, float1, 0.01F);
	}

	@Test(timeout = 4000)
	public void test20() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Float float0 = new Float(2529.0657F);
		Louer louer0 = new Louer(localDate0, localDate0, 2529.0657F, localDate0, localDate0, "", "", "", "", "",
				localDate0, float0, localDate0, "", (-2205), localDate0);
		float float1 = louer0.getDepotDeGarantie();
		assertEquals(2529.0657F, float1, 0.01F);
		assertEquals((-2205), louer0.getRevolue());
	}

	@Test(timeout = 4000)
	public void test21() throws Throwable {
		Float float0 = new Float(0.0);
		Louer louer0 = new Louer((LocalDate) null, (LocalDate) null, (-1362.1342F), (LocalDate) null, (LocalDate) null,
				"7>ohHf^&CF<X", "[8f3qnKK/C~=", "[8f3qnKK/C~=", ",J", "4<vJ", (LocalDate) null, float0,
				(LocalDate) null, "*~x+;OA'x[p", 2, (LocalDate) null);
		louer0.getDateFin();
		assertEquals((-1362.1342F), louer0.getDepotDeGarantie(), 0.01F);
		assertEquals("7>ohHf^&CF<X", louer0.getDetailsEtatDesLieuxEntree());
		assertEquals("4<vJ", louer0.getIdGarant());
		assertEquals("*~x+;OA'x[p", louer0.getIdLogementAssocie());
		assertEquals(",J", louer0.getIdBienLouable());
		assertEquals(2, louer0.getRevolue());
		assertEquals("[8f3qnKK/C~=", louer0.getDetailsEtatDesLieuxSortie());
		assertEquals("[8f3qnKK/C~=", louer0.getIdLocataire());
	}

	@Test(timeout = 4000)
	public void test22() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Float float0 = new Float((-3243.087F));
		Louer louer0 = new Louer(localDate0, localDate0, (-3243.087F), localDate0, localDate0, (String) null,
				(String) null, (String) null, (String) null, (String) null, localDate0, float0, localDate0,
				(String) null, 2677, localDate0);
		louer0.getDateEtatDesLieuxSortie();
		assertEquals((-3243.087F), louer0.getDepotDeGarantie(), 0.01F);
		assertEquals(2677, louer0.getRevolue());
	}

	@Test(timeout = 4000)
	public void test23() throws Throwable {
		Float float0 = new Float((double) 1374.1001F);
		Louer louer0 = new Louer((LocalDate) null, (LocalDate) null, 1374.1001F, (LocalDate) null, (LocalDate) null, "",
				"", "QV*eYLlo|!r@L4", "ex7JJ)~h<1xKx0I", "", (LocalDate) null, float0, (LocalDate) null, ", dateFin=",
				185, (LocalDate) null);
		louer0.getDateEtatDesLieuxEntree();
		assertEquals(185, louer0.getRevolue());
		assertEquals("QV*eYLlo|!r@L4", louer0.getIdLocataire());
		assertEquals("ex7JJ)~h<1xKx0I", louer0.getIdBienLouable());
		assertEquals(", dateFin=", louer0.getIdLogementAssocie());
		assertEquals("", louer0.getDetailsEtatDesLieuxEntree());
		assertEquals("", louer0.getDetailsEtatDesLieuxSortie());
		assertEquals(1374.1001F, louer0.getDepotDeGarantie(), 0.01F);
		assertEquals("", louer0.getIdGarant());
	}

	@Test(timeout = 4000)
	public void test24() throws Throwable {
		Float float0 = new Float((double) 1374.1001F);
		Louer louer0 = new Louer((LocalDate) null, (LocalDate) null, 1374.1001F, (LocalDate) null, (LocalDate) null, "",
				"", "QV*eYLlo|!r@L4", "ex7JJ)~h<1xKx0I", "", (LocalDate) null, float0, (LocalDate) null, ", dateFin=",
				185, (LocalDate) null);
		louer0.getDateDerniereRegul();
		assertEquals(", dateFin=", louer0.getIdLogementAssocie());
		assertEquals("QV*eYLlo|!r@L4", louer0.getIdLocataire());
		assertEquals("", louer0.getIdGarant());
		assertEquals("ex7JJ)~h<1xKx0I", louer0.getIdBienLouable());
		assertEquals("", louer0.getDetailsEtatDesLieuxEntree());
		assertEquals("", louer0.getDetailsEtatDesLieuxSortie());
		assertEquals(1374.1001F, louer0.getDepotDeGarantie(), 0.01F);
		assertEquals(185, louer0.getRevolue());
	}

	@Test(timeout = 4000)
	public void test25() throws Throwable {
		Float float0 = new Float((double) 1.0F);
		Louer louer0 = new Louer((LocalDate) null, (LocalDate) null, 1.0F, (LocalDate) null, (LocalDate) null, "",
				"io-Z^%WR{TF!H", "io-Z^%WR{TF!H", "io-Z^%WR{TF!H", "io-Z^%WR{TF!H", (LocalDate) null, float0,
				(LocalDate) null, "io-Z^%WR{TF!H", (-3355), (LocalDate) null);
		louer0.getDateDebut();
		assertEquals("io-Z^%WR{TF!H", louer0.getIdLocataire());
		assertEquals("io-Z^%WR{TF!H", louer0.getIdBienLouable());
		assertEquals(1.0F, louer0.getDepotDeGarantie(), 0.01F);
		assertEquals("io-Z^%WR{TF!H", louer0.getIdLogementAssocie());
		assertEquals("io-Z^%WR{TF!H", louer0.getIdGarant());
		assertEquals("", louer0.getDetailsEtatDesLieuxEntree());
		assertEquals((-3355), louer0.getRevolue());
		assertEquals("io-Z^%WR{TF!H", louer0.getDetailsEtatDesLieuxSortie());
	}

	@Test(timeout = 4000)
	public void test26() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Float float0 = new Float(0.0F);
		Louer louer0 = new Louer(localDate0, localDate0, 0.0F, localDate0, localDate0, "Dlx-?X}^'=>8,f)6V", "", "", "",
				"", localDate0, float0, localDate0, "", (-2591), localDate0);
		louer0.getAjustementLoyer();
		assertEquals("", louer0.getIdLogementAssocie());
		assertEquals("", louer0.getIdGarant());
		assertEquals(0.0F, louer0.getDepotDeGarantie(), 0.01F);
		assertEquals((-2591), louer0.getRevolue());
		assertEquals("Dlx-?X}^'=>8,f)6V", louer0.getDetailsEtatDesLieuxEntree());
		assertEquals("", louer0.getIdBienLouable());
		assertEquals("", louer0.getIdLocataire());
		assertEquals("", louer0.getDetailsEtatDesLieuxSortie());
	}

	@Test(timeout = 4000)
	public void test27() throws Throwable {
		ZoneOffset zoneOffset0 = ZoneOffset.ofTotalSeconds(3874);
		LocalDate localDate0 = MockLocalDate.now((ZoneId) zoneOffset0);
		Float float0 = new Float((float) 3874);
		Louer louer0 = new Louer(localDate0, localDate0, 3874, localDate0, localDate0, ",~JG7uB\"0OVF",
				",~JG7uB\"0OVF", ",~JG7uB\"0OVF", "]", ",~JG7uB\"0OVF", localDate0, float0, localDate0, "]", (-2419),
				localDate0);
		louer0.getAjustementLoyer();
		assertEquals(3874.0F, louer0.getDepotDeGarantie(), 0.01F);
		assertEquals(",~JG7uB\"0OVF", louer0.getIdLocataire());
		assertEquals(",~JG7uB\"0OVF", louer0.getIdGarant());
		assertEquals((-2419), louer0.getRevolue());
		assertEquals("]", louer0.getIdLogementAssocie());
		assertEquals(",~JG7uB\"0OVF", louer0.getDetailsEtatDesLieuxEntree());
		assertEquals(",~JG7uB\"0OVF", louer0.getDetailsEtatDesLieuxSortie());
		assertEquals("]", louer0.getIdBienLouable());
	}

	@Test(timeout = 4000)
	public void test28() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Float float0 = new Float((-3243.087F));
		Louer louer0 = new Louer(localDate0, localDate0, (-3243.087F), localDate0, localDate0, (String) null,
				(String) null, (String) null, (String) null, (String) null, localDate0, float0, localDate0,
				(String) null, 2677, localDate0);
		louer0.getAjustementLoyer();
		assertEquals(2677, louer0.getRevolue());
		assertEquals((-3243.087F), louer0.getDepotDeGarantie(), 0.01F);
	}

	@Test(timeout = 4000)
	public void test29() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Float float0 = new Float(19.96244F);
		Louer louer0 = new Louer(localDate0, localDate0, 19.96244F, localDate0, localDate0, (String) null,
				(String) null, (String) null, (String) null, (String) null, localDate0, float0, localDate0,
				(String) null, (-768), localDate0);
		Louer louer1 = new Louer(localDate0, localDate0, 0.0F, localDate0, localDate0, (String) null, (String) null,
				(String) null, "Gd1gzDDR2y]2H.*$|Y", "jhj+O'@%srR8", localDate0, float0, localDate0, (String) null,
				(-768), localDate0);
		boolean boolean0 = louer0.equals(louer1);
		assertEquals(0.0F, louer1.getDepotDeGarantie(), 0.01F);
		assertTrue(boolean0);
		assertEquals("jhj+O'@%srR8", louer1.getIdGarant());
		assertEquals("Gd1gzDDR2y]2H.*$|Y", louer1.getIdBienLouable());
		assertEquals((-768), louer1.getRevolue());
	}

	@Test(timeout = 4000)
	public void test30() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Float float0 = new Float((-2701.41F));
		Louer louer0 = new Louer(localDate0, localDate0, (-2195), localDate0, localDate0, (String) null,
				"ZT[v08vAg{5iDQUX", "hU", "", (String) null, localDate0, float0, (LocalDate) null, "hU", (-2195),
				(LocalDate) null);
		Louer louer1 = new Louer((LocalDate) null, (LocalDate) null, (-2195), localDate0, (LocalDate) null, "hU",
				(String) null, "", "", "", localDate0, float0, localDate0, "ZT[v08vAg{5iDQUX", 1, localDate0);
		boolean boolean0 = louer0.equals(louer1);
		assertEquals((-2195.0F), louer1.getDepotDeGarantie(), 0.01F);
		assertEquals("hU", louer1.getDetailsEtatDesLieuxEntree());
		assertEquals("", louer0.getIdBienLouable());
		assertEquals(1, louer1.getRevolue());
		assertFalse(boolean0);
		assertEquals("", louer1.getIdBienLouable());
		assertEquals("ZT[v08vAg{5iDQUX", louer0.getDetailsEtatDesLieuxSortie());
		assertEquals("ZT[v08vAg{5iDQUX", louer1.getIdLogementAssocie());
		assertEquals("", louer1.getIdLocataire());
		assertEquals("", louer1.getIdGarant());
		assertEquals("hU", louer0.getIdLogementAssocie());
		assertEquals("hU", louer0.getIdLocataire());
	}

	@Test(timeout = 4000)
	public void test31() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Float float0 = new Float((-2708.3867F));
		Louer louer0 = new Louer(localDate0, localDate0, (-2708.3867F), localDate0, localDate0, (String) null,
				(String) null, (String) null, (String) null, (String) null, localDate0, float0, localDate0,
				(String) null, 2657, localDate0);
		Louer louer1 = new Louer(localDate0, localDate0, 2657, localDate0, localDate0, "", (String) null, "Ot", "", "",
				localDate0, float0, localDate0, "", 2657, localDate0);
		boolean boolean0 = louer0.equals(louer1);
		assertEquals("", louer1.getIdLogementAssocie());
		assertEquals("", louer1.getIdGarant());
		assertEquals("Ot", louer1.getIdLocataire());
		assertEquals(2657, louer1.getRevolue());
		assertFalse(boolean0);
		assertEquals("", louer1.getIdBienLouable());
		assertEquals(2657.0F, louer1.getDepotDeGarantie(), 0.01F);
		assertEquals("", louer1.getDetailsEtatDesLieuxEntree());
	}

	@Test(timeout = 4000)
	public void test32() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Float float0 = new Float((float) (-718));
		Louer louer0 = new Louer(localDate0, localDate0, (-718), localDate0, localDate0, (String) null, (String) null,
				(String) null, (String) null, (String) null, localDate0, float0, localDate0, (String) null, (-718),
				localDate0);
		boolean boolean0 = louer0.equals((Object) null);
		assertEquals((-718), louer0.getRevolue());
		assertFalse(boolean0);
		assertEquals((-718.0F), louer0.getDepotDeGarantie(), 0.01F);
	}

	@Test(timeout = 4000)
	public void test33() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Float float0 = new Float((-1495.9097F));
		Louer louer0 = new Louer(localDate0, localDate0, (-2419), localDate0, localDate0, "]", "]", "", "",
				", dateEtatDesLieuxSortie=", localDate0, float0, localDate0, "", (-504), localDate0);
		boolean boolean0 = louer0.equals(louer0);
		assertEquals("]", louer0.getDetailsEtatDesLieuxEntree());
		assertEquals("]", louer0.getDetailsEtatDesLieuxSortie());
		assertEquals("", louer0.getIdLogementAssocie());
		assertEquals(", dateEtatDesLieuxSortie=", louer0.getIdGarant());
		assertTrue(boolean0);
		assertEquals((-504), louer0.getRevolue());
		assertEquals("", louer0.getIdBienLouable());
		assertEquals("", louer0.getIdLocataire());
		assertEquals((-2419.0F), louer0.getDepotDeGarantie(), 0.01F);
	}

	@Test(timeout = 4000)
	public void test34() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Float float0 = new Float((float) (-3));
		Louer louer0 = new Louer(localDate0, localDate0, (-3), localDate0, localDate0, (String) null, (String) null,
				(String) null, (String) null, (String) null, localDate0, float0, localDate0, (String) null, (-3),
				localDate0);
		boolean boolean0 = louer0.equals(localDate0);
		assertEquals((-3), louer0.getRevolue());
		assertEquals((-3.0F), louer0.getDepotDeGarantie(), 0.01F);
		assertFalse(boolean0);
	}

	@Test(timeout = 4000)
	public void test35() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Float float0 = new Float((-3243.087F));
		Louer louer0 = new Louer(localDate0, localDate0, (-3243.087F), localDate0, localDate0, (String) null,
				(String) null, (String) null, (String) null, (String) null, localDate0, float0, localDate0,
				(String) null, 2677, localDate0);
		louer0.getIdGarant();
		assertEquals((-3243.087F), louer0.getDepotDeGarantie(), 0.01F);
		assertEquals(2677, louer0.getRevolue());
	}

	@Test(timeout = 4000)
	public void test36() throws Throwable {
		Period period0 = Period.ZERO;
		IsoChronology isoChronology0 = period0.getChronology();
		LocalDate localDate0 = MockIsoChronology.dateNow(isoChronology0);
		Float float0 = new Float((-1482.2593F));
		Louer louer0 = new Louer(localDate0, localDate0, 0.0F, localDate0, localDate0, (String) null, (String) null,
				(String) null, (String) null, (String) null, localDate0, float0, localDate0,
				", dateEtatDesLieuxEntr\u00E9e=", 1, localDate0);
		louer0.getMoisFinAjustement();
		assertEquals(1, louer0.getRevolue());
		assertEquals(0.0F, louer0.getDepotDeGarantie(), 0.01F);
	}

	@Test(timeout = 4000)
	public void test37() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Float float0 = new Float(2529.0657F);
		Louer louer0 = new Louer(localDate0, localDate0, 2529.0657F, localDate0, localDate0, "", "", "", "", "",
				localDate0, float0, localDate0, "", (-2205), localDate0);
		int int0 = louer0.getRevolue();
		assertEquals((-2205), int0);
		assertEquals(2529.0657F, louer0.getDepotDeGarantie(), 0.01F);
	}

	@Test(timeout = 4000)
	public void test38() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Louer louer0 = new Louer(localDate0, localDate0, 2386.7283F, localDate0, localDate0, "]",
				", d\u00E9potDeGarantie=", "]", "", ", d\u00E9potDeGarantie=", localDate0, (Float) null, localDate0,
				"Uz]FM3+5G`|1:", (-2198), localDate0);
		louer0.getAjustementLoyer();
		assertEquals("]", louer0.getDetailsEtatDesLieuxEntree());
		assertEquals(", d\u00E9potDeGarantie=", louer0.getDetailsEtatDesLieuxSortie());
		assertEquals("]", louer0.getIdLocataire());
		assertEquals("", louer0.getIdBienLouable());
		assertEquals("Uz]FM3+5G`|1:", louer0.getIdLogementAssocie());
		assertEquals(2386.7283F, louer0.getDepotDeGarantie(), 0.01F);
		assertEquals(", d\u00E9potDeGarantie=", louer0.getIdGarant());
		assertEquals((-2198), louer0.getRevolue());
	}

	@Test(timeout = 4000)
	public void test39() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Float float0 = new Float((-2701.41F));
		Louer louer0 = new Louer(localDate0, localDate0, (-2701.41F), localDate0, localDate0, (String) null,
				(String) null, (String) null, (String) null, (String) null, localDate0, float0, localDate0,
				(String) null, (-2195), localDate0);
		String string0 = louer0.toString();
		assertEquals((-2195), louer0.getRevolue());
		assertEquals(
				"Louer [dateD\u00E9but=2014-02-14, dateFin=2014-02-14, d\u00E9potDeGarantie=-2701.41, dateEtatDesLieuxEntr\u00E9e=2014-02-14, dateEtatDesLieuxSortie=2014-02-14, d\u00E9tailsEtatDesLieuxEntr\u00E9e=null, d\u00E9tailsEtatDesLieuxSortie=null, idLocataire=null]",
				string0);
	}

	@Test(timeout = 4000)
	public void test40() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Float float0 = new Float(2529.0657F);
		Louer louer0 = new Louer(localDate0, localDate0, 2529.0657F, localDate0, localDate0, "", "", "", "", "",
				localDate0, float0, localDate0, "", (-2205), localDate0);
		louer0.getDetailsEtatDesLieuxEntree();
		assertEquals(2529.0657F, louer0.getDepotDeGarantie(), 0.01F);
		assertEquals((-2205), louer0.getRevolue());
	}

	@Test(timeout = 4000)
	public void test41() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Float float0 = new Float((float) (-746));
		Louer louer0 = new Louer(localDate0, localDate0, (-746), localDate0, localDate0, (String) null, (String) null,
				(String) null, (String) null, (String) null, localDate0, float0, localDate0, (String) null, (-746),
				localDate0);
		louer0.setRevolue((-746));
		assertEquals((-746), louer0.getRevolue());
		assertEquals((-746.0F), louer0.getDepotDeGarantie(), 0.01F);
	}

	@Test(timeout = 4000)
	public void test42() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Float float0 = new Float(2529.0657F);
		Louer louer0 = new Louer(localDate0, localDate0, 2529.0657F, localDate0, localDate0, "", "", "", "", "",
				localDate0, float0, localDate0, "", (-2205), localDate0);
		louer0.getDetailsEtatDesLieuxSortie();
		assertEquals(2529.0657F, louer0.getDepotDeGarantie(), 0.01F);
		assertEquals((-2205), louer0.getRevolue());
	}

	@Test(timeout = 4000)
	public void test43() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Float float0 = new Float((float) (-741));
		Louer louer0 = new Louer(localDate0, localDate0, (-741), localDate0, localDate0, (String) null, (String) null,
				(String) null, (String) null, (String) null, localDate0, float0, localDate0, (String) null, (-741),
				localDate0);
		louer0.setMoisDebutAjustement(localDate0);
		assertEquals((-741.0F), louer0.getDepotDeGarantie(), 0.01F);
		assertEquals((-741), louer0.getRevolue());
	}

	@Test(timeout = 4000)
	public void test44() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Float float0 = new Float((float) (-697));
		Louer louer0 = new Louer(localDate0, localDate0, (-697), localDate0, localDate0, (String) null, (String) null,
				(String) null, (String) null, (String) null, localDate0, float0, localDate0, (String) null, (-697),
				localDate0);
		louer0.setIdLocataire((String) null);
		assertEquals((-697), louer0.getRevolue());
		assertEquals((-697.0F), louer0.getDepotDeGarantie(), 0.01F);
	}

	@Test(timeout = 4000)
	public void test45() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Float float0 = new Float((float) (-697));
		Louer louer0 = new Louer(localDate0, localDate0, (-697), localDate0, localDate0, (String) null, (String) null,
				(String) null, (String) null, (String) null, localDate0, float0, localDate0, (String) null, (-697),
				localDate0);
		louer0.setDateEtatDesLieuxEntree(localDate0);
		assertEquals((-697), louer0.getRevolue());
		assertEquals((-697.0F), louer0.getDepotDeGarantie(), 0.01F);
	}

	@Test(timeout = 4000)
	public void test46() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Float float0 = new Float((float) (-762));
		Louer louer0 = new Louer(localDate0, localDate0, (-762), localDate0, localDate0, (String) null, (String) null,
				(String) null, (String) null, (String) null, localDate0, float0, localDate0, (String) null, (-762),
				localDate0);
		louer0.setDetailsEtatDesLieuxEntree((String) null);
		assertEquals((-762), louer0.getRevolue());
		assertEquals((-762.0F), louer0.getDepotDeGarantie(), 0.01F);
	}

	@Test(timeout = 4000)
	public void test47() throws Throwable {
		Float float0 = new Float((double) 1374.1001F);
		Louer louer0 = new Louer((LocalDate) null, (LocalDate) null, 1374.1001F, (LocalDate) null, (LocalDate) null, "",
				"", "QV*eYLlo|!r@L4", "ex7JJ)~h<1xKx0I", "", (LocalDate) null, float0, (LocalDate) null, ", dateFin=",
				185, (LocalDate) null);
		louer0.getMoisDebutAjustement();
		assertEquals("QV*eYLlo|!r@L4", louer0.getIdLocataire());
		assertEquals("ex7JJ)~h<1xKx0I", louer0.getIdBienLouable());
		assertEquals("", louer0.getIdGarant());
		assertEquals(185, louer0.getRevolue());
		assertEquals(", dateFin=", louer0.getIdLogementAssocie());
		assertEquals("", louer0.getDetailsEtatDesLieuxSortie());
		assertEquals("", louer0.getDetailsEtatDesLieuxEntree());
		assertEquals(1374.1001F, louer0.getDepotDeGarantie(), 0.01F);
	}

	@Test(timeout = 4000)
	public void test48() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Float float0 = new Float((-1.0F));
		Louer louer0 = new Louer(localDate0, localDate0, (-2787.009F), localDate0, localDate0, "{#c2a^ug", "", "", "",
				"", localDate0, float0, localDate0, "{#c2a^ug", 2, localDate0);
		louer0.getDateFin();
		assertEquals("", louer0.getIdBienLouable());
		assertEquals("", louer0.getIdLocataire());
		assertEquals("{#c2a^ug", louer0.getDetailsEtatDesLieuxEntree());
		assertEquals("", louer0.getIdGarant());
		assertEquals("{#c2a^ug", louer0.getIdLogementAssocie());
		assertEquals(2, louer0.getRevolue());
		assertEquals("", louer0.getDetailsEtatDesLieuxSortie());
		assertEquals((-2787.009F), louer0.getDepotDeGarantie(), 0.01F);
	}

	@Test(timeout = 4000)
	public void test49() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Float float0 = new Float((float) (-713));
		Louer louer0 = new Louer(localDate0, localDate0, (-713), localDate0, localDate0, (String) null, (String) null,
				(String) null, (String) null, (String) null, localDate0, float0, localDate0, (String) null, (-713),
				localDate0);
		louer0.setIdBienLouable((String) null);
		assertEquals((-713), louer0.getRevolue());
		assertEquals((-713.0F), louer0.getDepotDeGarantie(), 0.01F);
	}

	@Test(timeout = 4000)
	public void test50() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Float float0 = new Float((float) (-742));
		Louer louer0 = new Louer(localDate0, localDate0, (-742), localDate0, localDate0, (String) null, (String) null,
				(String) null, (String) null, (String) null, localDate0, float0, localDate0, (String) null, (-742),
				localDate0);
		louer0.setDetailsEtatDesLieuxSortie((String) null);
		assertEquals((-742.0F), louer0.getDepotDeGarantie(), 0.01F);
		assertEquals((-742), louer0.getRevolue());
	}

	@Test(timeout = 4000)
	public void test51() throws Throwable {
		ZoneOffset zoneOffset0 = ZoneOffset.ofTotalSeconds(3874);
		LocalDate localDate0 = MockLocalDate.now((ZoneId) zoneOffset0);
		Float float0 = new Float((float) 3874);
		Louer louer0 = new Louer(localDate0, localDate0, 0.0F, localDate0, localDate0, (String) null, (String) null,
				(String) null, ",~JG7uB\"0OVF", "#!n0N7[Btox\"*eM[o", localDate0, float0, localDate0, (String) null,
				(-2419), localDate0);
		String string0 = louer0.getIdLogementAssocie();
		assertEquals(0.0F, louer0.getDepotDeGarantie(), 0.01F);
		assertEquals("#!n0N7[Btox\"*eM[o", louer0.getIdGarant());
		assertEquals((-2419), louer0.getRevolue());
		assertNull(string0);
		assertEquals(",~JG7uB\"0OVF", louer0.getIdBienLouable());
	}

	@Test(timeout = 4000)
	public void test52() throws Throwable {
		Float float0 = new Float((-2701.41F));
		Louer louer0 = new Louer((LocalDate) null, (LocalDate) null, 2677, (LocalDate) null, (LocalDate) null, "",
				(String) null, (String) null, "!", (String) null, (LocalDate) null, float0, (LocalDate) null,
				(String) null, 2677, (LocalDate) null);
		louer0.getDateEtatDesLieuxSortie();
		assertEquals("!", louer0.getIdBienLouable());
		assertEquals(2677.0F, louer0.getDepotDeGarantie(), 0.01F);
		assertEquals("", louer0.getDetailsEtatDesLieuxEntree());
		assertEquals(2677, louer0.getRevolue());
	}

	@Test(timeout = 4000)
	public void test53() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Float float0 = new Float((-3243.087F));
		Louer louer0 = new Louer(localDate0, localDate0, (-3243.087F), localDate0, localDate0, (String) null,
				(String) null, (String) null, (String) null, (String) null, localDate0, float0, localDate0,
				(String) null, 2677, localDate0);
		louer0.getDateDebut();
		assertEquals(2677, louer0.getRevolue());
		assertEquals((-3243.087F), louer0.getDepotDeGarantie(), 0.01F);
	}

	@Test(timeout = 4000)
	public void test54() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Float float0 = new Float((-2701.41F));
		Louer louer0 = new Louer(localDate0, localDate0, (-2701.41F), localDate0, localDate0, (String) null,
				(String) null, (String) null, (String) null, (String) null, localDate0, float0, localDate0,
				(String) null, 2677, localDate0);
		louer0.setDateEtatDesLieuxSortie(localDate0);
		assertEquals(2677, louer0.getRevolue());
		assertEquals((-2701.41F), louer0.getDepotDeGarantie(), 0.01F);
	}

	@Test(timeout = 4000)
	public void test55() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Float float0 = new Float((-2701.41F));
		Louer louer0 = new Louer(localDate0, localDate0, (-2701.41F), localDate0, localDate0, (String) null,
				(String) null, (String) null, (String) null, (String) null, localDate0, float0, localDate0,
				(String) null, 2, localDate0);
		louer0.setDepotDeGarantie((-2701.41F));
		assertEquals(2, louer0.getRevolue());
		assertEquals((-2701.41F), louer0.getDepotDeGarantie(), 0.01F);
	}

	@Test(timeout = 4000)
	public void test56() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Float float0 = new Float((float) (-697));
		Louer louer0 = new Louer(localDate0, localDate0, (-697), localDate0, localDate0, (String) null, (String) null,
				(String) null, (String) null, (String) null, localDate0, float0, localDate0, (String) null, (-697),
				localDate0);
		louer0.setMoisFinAjustement(localDate0);
		assertEquals((-697.0F), louer0.getDepotDeGarantie(), 0.01F);
		assertEquals((-697), louer0.getRevolue());
	}

	@Test(timeout = 4000)
	public void test57() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Float float0 = new Float((float) (-741));
		Louer louer0 = new Louer(localDate0, localDate0, (-741), localDate0, localDate0, (String) null, (String) null,
				(String) null, (String) null, (String) null, localDate0, float0, localDate0, (String) null, (-741),
				localDate0);
		louer0.setDateFin(localDate0);
		assertEquals((-741.0F), louer0.getDepotDeGarantie(), 0.01F);
		assertEquals((-741), louer0.getRevolue());
	}

	@Test(timeout = 4000)
	public void test58() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Float float0 = new Float(0.0F);
		Louer louer0 = new Louer(localDate0, localDate0, 0.0F, localDate0, localDate0, "Dlx-?X}^'=>8,f)6V", "", "", "",
				"", localDate0, float0, localDate0, "", (-2591), localDate0);
		String string0 = louer0.getIdLocataire();
		assertEquals("Dlx-?X}^'=>8,f)6V", louer0.getDetailsEtatDesLieuxEntree());
		assertEquals("", louer0.getIdLogementAssocie());
		assertEquals((-2591), louer0.getRevolue());
		assertEquals("", louer0.getIdGarant());
		assertEquals(0.0F, louer0.getDepotDeGarantie(), 0.01F);
		assertEquals("", louer0.getDetailsEtatDesLieuxSortie());
		assertEquals("", string0);
		assertEquals("", louer0.getIdBienLouable());
	}

	@Test(timeout = 4000)
	public void test59() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Float float0 = new Float((float) (-697));
		Louer louer0 = new Louer(localDate0, localDate0, (-697), localDate0, localDate0, (String) null, (String) null,
				(String) null, (String) null, (String) null, localDate0, float0, localDate0, (String) null, (-697),
				localDate0);
		louer0.hashCode();
		assertEquals((-697), louer0.getRevolue());
		assertEquals((-697.0F), louer0.getDepotDeGarantie(), 0.01F);
	}

	@Test(timeout = 4000)
	public void test60() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Float float0 = new Float((float) (-732));
		Louer louer0 = new Louer(localDate0, localDate0, (-732), localDate0, localDate0, (String) null, (String) null,
				(String) null, (String) null, (String) null, localDate0, float0, localDate0, (String) null, (-732),
				localDate0);
		louer0.setDateDerniereRegul(localDate0);
		assertEquals((-732), louer0.getRevolue());
		assertEquals((-732.0F), louer0.getDepotDeGarantie(), 0.01F);
	}

	@Test(timeout = 4000)
	public void test61() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Float float0 = new Float((float) (-697));
		Louer louer0 = new Louer(localDate0, localDate0, (-697), localDate0, localDate0, (String) null, (String) null,
				(String) null, (String) null, (String) null, localDate0, float0, localDate0, (String) null, (-697),
				localDate0);
		louer0.setAjustementLoyer(float0);
		assertEquals((-697), louer0.getRevolue());
		assertEquals((-697.0F), louer0.getDepotDeGarantie(), 0.01F);
	}

	@Test(timeout = 4000)
	public void test62() throws Throwable {
		Float float0 = Float.valueOf((-730.93115F));
		Louer louer0 = new Louer((LocalDate) null, (LocalDate) null, (-730.93115F), (LocalDate) null, (LocalDate) null,
				"sR8h'", "c01=QBONC[9n\"FL", "", "", "o^1zm/bpf04yh!rS", (LocalDate) null, float0, (LocalDate) null,
				"modele.Louer", 3335, (LocalDate) null);
		float float1 = louer0.getDepotDeGarantie();
		assertEquals("", louer0.getIdBienLouable());
		assertEquals("sR8h'", louer0.getDetailsEtatDesLieuxEntree());
		assertEquals("o^1zm/bpf04yh!rS", louer0.getIdGarant());
		assertEquals("modele.Louer", louer0.getIdLogementAssocie());
		assertEquals("c01=QBONC[9n\"FL", louer0.getDetailsEtatDesLieuxSortie());
		assertEquals((-730.93115F), float1, 0.01F);
		assertEquals("", louer0.getIdLocataire());
		assertEquals(3335, louer0.getRevolue());
	}

	@Test(timeout = 4000)
	public void test63() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Float float0 = new Float(0.0F);
		Louer louer0 = new Louer(localDate0, localDate0, 0.0F, localDate0, localDate0, "Dlx-?X}^'=>8,f)6V", "", "", "",
				"", localDate0, float0, localDate0, "", (-2591), localDate0);
		louer0.getDateDerniereRegul();
		assertEquals("Dlx-?X}^'=>8,f)6V", louer0.getDetailsEtatDesLieuxEntree());
		assertEquals("", louer0.getIdBienLouable());
		assertEquals(0.0F, louer0.getDepotDeGarantie(), 0.01F);
		assertEquals((-2591), louer0.getRevolue());
		assertEquals("", louer0.getIdGarant());
		assertEquals("", louer0.getIdLocataire());
		assertEquals("", louer0.getIdLogementAssocie());
		assertEquals("", louer0.getDetailsEtatDesLieuxSortie());
	}

	@Test(timeout = 4000)
	public void test64() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Float float0 = new Float((float) (-732));
		Louer louer0 = new Louer(localDate0, localDate0, (-732), localDate0, localDate0, (String) null, (String) null,
				(String) null, (String) null, (String) null, localDate0, float0, localDate0, (String) null, (-732),
				localDate0);
		louer0.setIdGarant((String) null);
		assertEquals((-732), louer0.getRevolue());
		assertEquals((-732.0F), louer0.getDepotDeGarantie(), 0.01F);
	}

	@Test(timeout = 4000)
	public void test65() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Float float0 = new Float((float) (-732));
		Louer louer0 = new Louer(localDate0, localDate0, (-732), localDate0, localDate0, (String) null, (String) null,
				(String) null, (String) null, (String) null, localDate0, float0, localDate0, (String) null, (-732),
				localDate0);
		louer0.setDateDebut(localDate0);
		assertEquals((-732.0F), louer0.getDepotDeGarantie(), 0.01F);
		assertEquals((-732), louer0.getRevolue());
	}

	@Test(timeout = 4000)
	public void test66() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Float float0 = new Float((-2701.41F));
		Louer louer0 = new Louer(localDate0, localDate0, (-2701.41F), localDate0, localDate0, (String) null,
				(String) null, (String) null, (String) null, (String) null, localDate0, float0, localDate0,
				(String) null, (-2195), localDate0);
		louer0.setIdLogementAssocie((String) null);
		assertEquals((-2701.41F), louer0.getDepotDeGarantie(), 0.01F);
		assertEquals((-2195), louer0.getRevolue());
	}

	@Test(timeout = 4000)
	public void test67() throws Throwable {
		ZoneOffset zoneOffset0 = ZoneOffset.ofTotalSeconds(3874);
		LocalDate localDate0 = MockLocalDate.now((ZoneId) zoneOffset0);
		Float float0 = new Float((-626.2075F));
		Louer louer0 = new Louer(localDate0, localDate0, (-2419), localDate0, localDate0, "Louer [dateD\u00E9but=",
				"#@wi\"OaC7Fp?=_A.", ";PLj_", (String) null, "]", localDate0, float0, localDate0, ",~JG7uB\"0OVF", 0,
				localDate0);
		String string0 = louer0.getIdBienLouable();
		assertEquals("]", louer0.getIdGarant());
		assertEquals(";PLj_", louer0.getIdLocataire());
		assertEquals(0, louer0.getRevolue());
		assertEquals((-2419.0F), louer0.getDepotDeGarantie(), 0.01F);
		assertEquals("Louer [dateD\u00E9but=", louer0.getDetailsEtatDesLieuxEntree());
		assertEquals("#@wi\"OaC7Fp?=_A.", louer0.getDetailsEtatDesLieuxSortie());
		assertEquals(",~JG7uB\"0OVF", louer0.getIdLogementAssocie());
		assertNull(string0);
	}

	@Test(timeout = 4000)
	public void test68() throws Throwable {
		ZoneOffset zoneOffset0 = ZoneOffset.ofTotalSeconds(3874);
		LocalDate localDate0 = MockLocalDate.now((ZoneId) zoneOffset0);
		Float float0 = new Float((float) 3874);
		Louer louer0 = new Louer(localDate0, localDate0, 3874, localDate0, localDate0, "", "[?Q>>D#-X.e3fM2k", "", "",
				"@a{eFzZ!<", localDate0, float0, localDate0, "aAF!nnmN'", (-1011), localDate0);
		louer0.getDateEtatDesLieuxEntree();
		assertEquals("@a{eFzZ!<", louer0.getIdGarant());
		assertEquals("aAF!nnmN'", louer0.getIdLogementAssocie());
		assertEquals("", louer0.getIdLocataire());
		assertEquals("", louer0.getDetailsEtatDesLieuxEntree());
		assertEquals("", louer0.getIdBienLouable());
		assertEquals("[?Q>>D#-X.e3fM2k", louer0.getDetailsEtatDesLieuxSortie());
		assertEquals((-1011), louer0.getRevolue());
		assertEquals(3874.0F, louer0.getDepotDeGarantie(), 0.01F);
	}
}
