/*
 * This file was automatically generated by EvoSuite
 * Fri Jan 16 14:09:52 GMT 2026
 */

package test.modele;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertNull;
import static org.junit.Assert.assertTrue;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;

import modele.Necessiter;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class Necessiter_ESTest extends Necessiter_ESTest_scaffolding {

	@Test(timeout = 4000)
	public void test00() throws Throwable {
		Necessiter necessiter0 = new Necessiter((String) null, (String) null);
		String string0 = necessiter0.getIdIntervention();
		assertNull(string0);
	}

	@Test(timeout = 4000)
	public void test01() throws Throwable {
		Necessiter necessiter0 = new Necessiter("]i|iC#%gHk4i+", "");
		assertEquals("", necessiter0.getIdIntervention());

		necessiter0.setIdIntervention("G");
		necessiter0.getIdIntervention();
		assertEquals("]i|iC#%gHk4i+", necessiter0.getIdBien());
	}

	@Test(timeout = 4000)
	public void test02() throws Throwable {
		Necessiter necessiter0 = new Necessiter((String) null, (String) null);
		String string0 = necessiter0.getIdBien();
		assertNull(string0);
	}

	@Test(timeout = 4000)
	public void test03() throws Throwable {
		Necessiter necessiter0 = new Necessiter("", "");
		necessiter0.setIdBien("#O");
		String string0 = necessiter0.getIdBien();
		assertEquals("#O", string0);
	}

	@Test(timeout = 4000)
	public void test04() throws Throwable {
		Necessiter necessiter0 = new Necessiter("]i|iC#%gHk4i+", "");
		Necessiter necessiter1 = new Necessiter("]i|iC#%gHk4i+", "]i|iC#%gHk4i+");
		boolean boolean0 = necessiter0.equals(necessiter1);
		assertFalse(boolean0);
		assertEquals("]i|iC#%gHk4i+", necessiter0.getIdBien());
	}

	@Test(timeout = 4000)
	public void test05() throws Throwable {
		Necessiter necessiter0 = new Necessiter(",r]w\"", "Cn]");
		Necessiter necessiter1 = new Necessiter((String) null, (String) null);
		boolean boolean0 = necessiter0.equals(necessiter1);
		assertEquals("Cn]", necessiter0.getIdIntervention());
		assertEquals(",r]w\"", necessiter0.getIdBien());
		assertFalse(boolean0);
	}

	@Test(timeout = 4000)
	public void test06() throws Throwable {
		Necessiter necessiter0 = new Necessiter("", "");
		boolean boolean0 = necessiter0.equals("");
		assertFalse(boolean0);
	}

	@Test(timeout = 4000)
	public void test07() throws Throwable {
		Necessiter necessiter0 = new Necessiter((String) null, (String) null);
		boolean boolean0 = necessiter0.equals((Object) null);
		assertFalse(boolean0);
	}

	@Test(timeout = 4000)
	public void test08() throws Throwable {
		Necessiter necessiter0 = new Necessiter((String) null, (String) null);
		boolean boolean0 = necessiter0.equals(necessiter0);
		assertTrue(boolean0);
	}

	@Test(timeout = 4000)
	public void test09() throws Throwable {
		Necessiter necessiter0 = new Necessiter("", "");
		Necessiter necessiter1 = new Necessiter("", "");
		boolean boolean0 = necessiter0.equals(necessiter1);
		assertTrue(boolean0);
	}

	@Test(timeout = 4000)
	public void test10() throws Throwable {
		Necessiter necessiter0 = new Necessiter("", "");
		necessiter0.hashCode();
	}

	@Test(timeout = 4000)
	public void test11() throws Throwable {
		Necessiter necessiter0 = new Necessiter("", "");
		String string0 = necessiter0.getIdBien();
		assertEquals("", string0);
	}

	@Test(timeout = 4000)
	public void test12() throws Throwable {
		Necessiter necessiter0 = new Necessiter("", "");
		String string0 = necessiter0.getIdIntervention();
		assertEquals("", string0);
	}
}
