/*
 * This file was automatically generated by EvoSuite
 * Fri Jan 16 14:12:43 GMT 2026
 */

package test.modele;

import static org.evosuite.runtime.EvoAssertions.verifyException;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertNull;
import static org.junit.Assert.assertTrue;
import static org.junit.Assert.fail;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;

import modele.Organisme;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class Organisme_ESTest extends Organisme_ESTest_scaffolding {

	@Test(timeout = 4000)
	public void test00() throws Throwable {
		Organisme organisme0 = new Organisme("", "", "", "", "fi`8b", ")PK]{1|*]La(BXJIx m", "", ">7Y#-G{+0-D=LC0^");
		// Undeclared exception!
		try {
			organisme0.setNumTel("");
			fail("Expecting exception: IllegalArgumentException");

		} catch (IllegalArgumentException e) {
			//
			// Le num\u00E9ro de t\u00E9l\u00E9phone n'est pas conforme !
			//
			verifyException("modele.Organisme", e);
		}
	}

	@Test(timeout = 4000)
	public void test01() throws Throwable {
		Organisme organisme0 = new Organisme("G\"KQ", "]", "]", (String) null, "", "", (String) null,
				"CN9pv[.P<N]o}&l");
		try {
			organisme0.setNumSIRET("CN9pv[.P<N]o}&l");
			fail("Expecting exception: IllegalArgumentException");

		} catch (IllegalArgumentException e) {
			//
			// Le num\u00E9ro de SIRET n'est pas conforme !
			//
			verifyException("modele.Organisme", e);
		}
	}

	@Test(timeout = 4000)
	public void test02() throws Throwable {
		Organisme organisme0 = new Organisme("", (String) null, "", (String) null, "2+cqg@BEjaY", (String) null, "",
				"ehS{w");
		String string0 = organisme0.getVille();
		assertEquals("2+cqg@BEjaY", organisme0.getCodePostal());
		assertEquals("ehS{w", organisme0.getSpecialite());
		assertEquals("", organisme0.getNumTel());
		assertEquals("", organisme0.getNumSIRET());
		assertNull(string0);
		assertEquals("", organisme0.getAdresse());
	}

	@Test(timeout = 4000)
	public void test03() throws Throwable {
		Organisme organisme0 = new Organisme("", "", "Le num\u00E9ro de t\u00E9l\u00E9phone n'est pas conforme !",
				"IaUj:", "", "", "", "Le num\u00E9ro de t\u00E9l\u00E9phone n'est pas conforme !");
		String string0 = organisme0.getVille();
		assertEquals("", organisme0.getMail());
		assertEquals("Le num\u00E9ro de t\u00E9l\u00E9phone n'est pas conforme !", organisme0.getAdresse());
		assertEquals("IaUj:", string0);
		assertEquals("", organisme0.getNumSIRET());
		assertEquals("Le num\u00E9ro de t\u00E9l\u00E9phone n'est pas conforme !", organisme0.getSpecialite());
		assertEquals("", organisme0.getCodePostal());
		assertEquals("", organisme0.getNumTel());
		assertEquals("", organisme0.getNom());
	}

	@Test(timeout = 4000)
	public void test04() throws Throwable {
		Organisme organisme0 = new Organisme(".K$P'rB", ".K$P'rB", ".K$P'rB", ".K$P'rB", ".K$P'rB", ".K$P'rB",
				".K$P'rB", ".K$P'rB");
		String string0 = organisme0.getSpecialite();
		assertEquals(".K$P'rB", string0);
	}

	@Test(timeout = 4000)
	public void test05() throws Throwable {
		Organisme organisme0 = new Organisme((String) null, "K^$ m\"@8bQ[9OMQ'2^t", "", "Q4dJ:[Q[oKK#", (String) null,
				"K^$ m\"@8bQ[9OMQ'2^t", ")q$Aj~Ku{BW%LrJ4D", "");
		String string0 = organisme0.getSpecialite();
		assertEquals("K^$ m\"@8bQ[9OMQ'2^t", organisme0.getNom());
		assertEquals("", string0);
		assertEquals(")q$Aj~Ku{BW%LrJ4D", organisme0.getNumTel());
		assertNotNull(string0);
		assertEquals("Q4dJ:[Q[oKK#", organisme0.getVille());
		assertEquals("K^$ m\"@8bQ[9OMQ'2^t", organisme0.getMail());
		assertEquals("", organisme0.getAdresse());
	}

	@Test(timeout = 4000)
	public void test06() throws Throwable {
		Organisme organisme0 = new Organisme("utoWfX:6", "", "Le num\u00E9ro de SIET n'est pas conforme !",
				"Le num\u00E9ro de SIET n'est pas conforme !", "S", "S", (String) null, ", adresse=");
		String string0 = organisme0.getNumTel();
		assertNull(string0);
		assertEquals("Le num\u00E9ro de SIET n'est pas conforme !", organisme0.getAdresse());
		assertEquals(", adresse=", organisme0.getSpecialite());
		assertEquals("Le num\u00E9ro de SIET n'est pas conforme !", organisme0.getVille());
		assertEquals("S", organisme0.getCodePostal());
		assertEquals("", organisme0.getNom());
		assertEquals("S", organisme0.getMail());
		assertEquals("utoWfX:6", organisme0.getNumSIRET());
	}

	@Test(timeout = 4000)
	public void test07() throws Throwable {
		Organisme organisme0 = new Organisme("", (String) null, "", (String) null, "2+cqg@BEjaY", (String) null, "",
				"ehS{w");
		String string0 = organisme0.getNumTel();
		assertEquals("2+cqg@BEjaY", organisme0.getCodePostal());
		assertEquals("ehS{w", organisme0.getSpecialite());
		assertEquals("", organisme0.getNumSIRET());
		assertEquals("", string0);
		assertEquals("", organisme0.getAdresse());
		assertNotNull(string0);
	}

	@Test(timeout = 4000)
	public void test08() throws Throwable {
		Organisme organisme0 = new Organisme((String) null, "0", (String) null, "RD%t=_/C/*2s~!t+pW(", (String) null,
				(String) null, (String) null, (String) null);
		String string0 = organisme0.getNumSIRET();
		assertNull(string0);
		assertEquals("0", organisme0.getNom());
		assertEquals("RD%t=_/C/*2s~!t+pW(", organisme0.getVille());
	}

	@Test(timeout = 4000)
	public void test09() throws Throwable {
		Organisme organisme0 = new Organisme("Le mail n'est donc pas valable", "Le mail n'est donc pas valable",
				"Le mail n'est donc pas valable", ", adresse=", ", adresse=", ", adresse=", "-!'J8r#{ np/8u",
				", adresse=");
		String string0 = organisme0.getNumSIRET();
		assertEquals("Le mail n'est donc pas valable", string0);
		assertEquals(", adresse=", organisme0.getCodePostal());
		assertEquals("Le mail n'est donc pas valable", organisme0.getAdresse());
		assertEquals("Le mail n'est donc pas valable", organisme0.getNom());
		assertEquals(", adresse=", organisme0.getMail());
		assertEquals("-!'J8r#{ np/8u", organisme0.getNumTel());
		assertEquals(", adresse=", organisme0.getVille());
		assertEquals(", adresse=", organisme0.getSpecialite());
	}

	@Test(timeout = 4000)
	public void test10() throws Throwable {
		Organisme organisme0 = new Organisme("", (String) null, "", (String) null, "2+cqg@BEjaY", (String) null, "",
				"ehS{w");
		String string0 = organisme0.getNom();
		assertNull(string0);
		assertEquals("2+cqg@BEjaY", organisme0.getCodePostal());
		assertEquals("ehS{w", organisme0.getSpecialite());
		assertEquals("", organisme0.getNumTel());
		assertEquals("", organisme0.getAdresse());
		assertEquals("", organisme0.getNumSIRET());
	}

	@Test(timeout = 4000)
	public void test11() throws Throwable {
		Organisme organisme0 = new Organisme("", "", "", "RY#F", "", ":Bs!9={z<s\"EGNY", "", "");
		String string0 = organisme0.getNom();
		assertEquals("RY#F", organisme0.getVille());
		assertEquals("", string0);
		assertEquals("", organisme0.getSpecialite());
		assertEquals("", organisme0.getNumSIRET());
		assertEquals("", organisme0.getAdresse());
		assertEquals("", organisme0.getNumTel());
		assertEquals(":Bs!9={z<s\"EGNY", organisme0.getMail());
		assertEquals("", organisme0.getCodePostal());
	}

	@Test(timeout = 4000)
	public void test12() throws Throwable {
		Organisme organisme0 = new Organisme("", (String) null, "", (String) null, "2+cqg@BEjaY", (String) null, "",
				"ehS{w");
		String string0 = organisme0.getMail();
		assertEquals("", organisme0.getNumSIRET());
		assertEquals("2+cqg@BEjaY", organisme0.getCodePostal());
		assertEquals("", organisme0.getAdresse());
		assertEquals("ehS{w", organisme0.getSpecialite());
		assertEquals("", organisme0.getNumTel());
		assertNull(string0);
	}

	@Test(timeout = 4000)
	public void test13() throws Throwable {
		Organisme organisme0 = new Organisme("7v#q?[(^", "7v#q?[(^",
				"Le num\u00E9ro de t\u00E9l\u00E9phone n'est pas conforme !", "7v#q?[(^", "", "", "", "/*AI{P&~117s");
		String string0 = organisme0.getMail();
		assertEquals("7v#q?[(^", organisme0.getNom());
		assertEquals("Le num\u00E9ro de t\u00E9l\u00E9phone n'est pas conforme !", organisme0.getAdresse());
		assertEquals("", organisme0.getCodePostal());
		assertEquals("7v#q?[(^", organisme0.getVille());
		assertEquals("", organisme0.getNumTel());
		assertEquals("/*AI{P&~117s", organisme0.getSpecialite());
		assertEquals("", string0);
		assertEquals("7v#q?[(^", organisme0.getNumSIRET());
	}

	@Test(timeout = 4000)
	public void test14() throws Throwable {
		Organisme organisme0 = new Organisme("", "[}chWa5|i8M}2s1Qj", "", "?M81cuF.:R?p", (String) null, "6D+|<8;d^3",
				"(3v&:D4Ir?`l_XI]P/", "qNV");
		String string0 = organisme0.getCodePostal();
		assertEquals("", organisme0.getNumSIRET());
		assertEquals("6D+|<8;d^3", organisme0.getMail());
		assertEquals("?M81cuF.:R?p", organisme0.getVille());
		assertEquals("[}chWa5|i8M}2s1Qj", organisme0.getNom());
		assertNull(string0);
		assertEquals("(3v&:D4Ir?`l_XI]P/", organisme0.getNumTel());
		assertEquals("", organisme0.getAdresse());
		assertEquals("qNV", organisme0.getSpecialite());
	}

	@Test(timeout = 4000)
	public void test15() throws Throwable {
		Organisme organisme0 = new Organisme("=@%bVg", "r}lQrH-!:o#EA6;knR",
				"Le num\u00E9ro de SIRET n'est pas conforme !", "Le num\u00E9ro de SIRET n'est pas conforme !",
				"Le num\u00E9ro de SIRET n'est pas conforme !", "", "0T", "");
		String string0 = organisme0.getCodePostal();
		assertEquals("r}lQrH-!:o#EA6;knR", organisme0.getNom());
		assertEquals("Le num\u00E9ro de SIRET n'est pas conforme !", string0);
		assertEquals("", organisme0.getMail());
		assertEquals("Le num\u00E9ro de SIRET n'est pas conforme !", organisme0.getVille());
		assertEquals("", organisme0.getSpecialite());
		assertEquals("=@%bVg", organisme0.getNumSIRET());
		assertEquals("Le num\u00E9ro de SIRET n'est pas conforme !", organisme0.getAdresse());
		assertEquals("0T", organisme0.getNumTel());
	}

	@Test(timeout = 4000)
	public void test16() throws Throwable {
		Organisme organisme0 = new Organisme("76", "47U (F+v-*GK@i", "47U (F+v-*GK@i", "47U (F+v-*GK@i", "76", "76",
				"47U (F+v-*GK@i", "");
		String string0 = organisme0.getAdresse();
		assertEquals("76", organisme0.getNumSIRET());
		assertEquals("47U (F+v-*GK@i", organisme0.getNumTel());
		assertEquals("47U (F+v-*GK@i", organisme0.getVille());
		assertEquals("47U (F+v-*GK@i", organisme0.getNom());
		assertEquals("47U (F+v-*GK@i", string0);
		assertEquals("", organisme0.getSpecialite());
		assertEquals("76", organisme0.getCodePostal());
		assertEquals("76", organisme0.getMail());
	}

	@Test(timeout = 4000)
	public void test17() throws Throwable {
		Organisme organisme0 = new Organisme("", "", "", "", "fi`8b", ")PK]{1|*]La(BXJIx m", "", ">7Y#-G{+0-D=LC0^");
		String string0 = organisme0.getAdresse();
		assertEquals("", organisme0.getNumTel());
		assertEquals(">7Y#-G{+0-D=LC0^", organisme0.getSpecialite());
		assertEquals("", organisme0.getNumSIRET());
		assertEquals("", organisme0.getVille());
		assertEquals("", organisme0.getNom());
		assertEquals("", string0);
		assertEquals(")PK]{1|*]La(BXJIx m", organisme0.getMail());
		assertEquals("fi`8b", organisme0.getCodePostal());
	}

	@Test(timeout = 4000)
	public void test18() throws Throwable {
		Organisme organisme0 = new Organisme("Rw", "Rw", "Rw", "Rw", "Rw", "Rw", "Rw", "Rw");
		// Undeclared exception!
		try {
			organisme0.setNumTel((String) null);
			fail("Expecting exception: NullPointerException");

		} catch (NullPointerException e) {
			//
			// no message in exception (getMessage() returned null)
			//
			verifyException("modele.Organisme", e);
		}
	}

	@Test(timeout = 4000)
	public void test19() throws Throwable {
		Organisme organisme0 = new Organisme("$YF3\"0n<sY9!F+K", "$YF3\"0n<sY9!F+K", "$YF3\"0n<sY9!F+K",
				"$YF3\"0n<sY9!F+K", "$YF3\"0n<sY9!F+K", "$YF3\"0n<sY9!F+K", "$YF3\"0n<sY9!F+K",
				"$YF3\"0n<sY9!F+K");
		// Undeclared exception!
		try {
			organisme0.setNumSIRET((String) null);
			fail("Expecting exception: NullPointerException");

		} catch (NullPointerException e) {
			//
			// no message in exception (getMessage() returned null)
			//
			verifyException("modele.Organisme", e);
		}
	}

	@Test(timeout = 4000)
	public void test20() throws Throwable {
		Organisme organisme0 = new Organisme("4s$YF\"0Vn<9!F+", "4s$YF\"0Vn<9!F+", "4s$YF\"0Vn<9!F+",
				"4s$YF\"0Vn<9!F+", "4s$YF\"0Vn<9!F+", "4s$YF\"0Vn<9!F+", "4s$YF\"0Vn<9!F+", "4s$YF\"0Vn<9!F+");
		// Undeclared exception!
		try {
			organisme0.setMail((String) null);
			fail("Expecting exception: NullPointerException");

		} catch (NullPointerException e) {
			//
			// no message in exception (getMessage() returned null)
			//
			verifyException("modele.Organisme", e);
		}
	}

	@Test(timeout = 4000)
	public void test21() throws Throwable {
		Organisme organisme0 = new Organisme("4YF310n<94o+K", "4YF310n<94o+K", "4YF310n<94o+K", "4YF310n<94o+K",
				"4YF310n<94o+K", "4YF310n<94o+K", "4YF310n<94o+K", "4YF310n<94o+K");
		Organisme organisme1 = new Organisme("4YF310n<94o+K", "4YF310n<94o+K", "4YF310n<94o+K", "4YF310n<94o+K",
				"4YF310n<94o+K", "4YF310n<94o+K", "4YF310n<94o+K", "4YF310n<94o+K");
		boolean boolean0 = organisme0.equals(organisme1);
		assertTrue(boolean0);
	}

	@Test(timeout = 4000)
	public void test22() throws Throwable {
		Organisme organisme0 = new Organisme("", "", "", "", "", "", "", "");
		boolean boolean0 = organisme0.equals((Object) null);
		assertFalse(boolean0);
	}

	@Test(timeout = 4000)
	public void test23() throws Throwable {
		Organisme organisme0 = new Organisme("utoWfX:6", "", "Le num\u00E9ro de SIET n'est pas conforme !",
				"Le num\u00E9ro de SIET n'est pas conforme !", "S", "S", (String) null, ", adresse=");
		boolean boolean0 = organisme0.equals(organisme0);
		assertEquals("S", organisme0.getCodePostal());
		assertEquals(", adresse=", organisme0.getSpecialite());
		assertEquals("utoWfX:6", organisme0.getNumSIRET());
		assertEquals("", organisme0.getNom());
		assertTrue(boolean0);
		assertEquals("Le num\u00E9ro de SIET n'est pas conforme !", organisme0.getAdresse());
		assertEquals("S", organisme0.getMail());
		assertEquals("Le num\u00E9ro de SIET n'est pas conforme !", organisme0.getVille());
	}

	@Test(timeout = 4000)
	public void test24() throws Throwable {
		Organisme organisme0 = new Organisme("gm'+%Yq0J6f)){)M", "gm'+%Yq0J6f)){)M", "gm'+%Yq0J6f)){)M",
				"gm'+%Yq0J6f)){)M", "l7Q)~", "l7Q)~", "0", (String) null);
		Object object0 = new Object();
		boolean boolean0 = organisme0.equals(object0);
		assertEquals("l7Q)~", organisme0.getMail());
		assertEquals("gm'+%Yq0J6f)){)M", organisme0.getAdresse());
		assertEquals("0", organisme0.getNumTel());
		assertEquals("gm'+%Yq0J6f)){)M", organisme0.getNom());
		assertEquals("gm'+%Yq0J6f)){)M", organisme0.getVille());
		assertEquals("l7Q)~", organisme0.getCodePostal());
		assertEquals("gm'+%Yq0J6f)){)M", organisme0.getNumSIRET());
		assertFalse(boolean0);
	}

	@Test(timeout = 4000)
	public void test25() throws Throwable {
		Organisme organisme0 = new Organisme("$\"0<9YF+K", "$\"0<9YF+K", "$\"0<9YF+K", "$\"0<9YF+K", "$\"0<9YF+K",
				"$\"0<9YF+K", "$\"0<9YF+K", "$\"0<9YF+K");
		// Undeclared exception!
		try {
			organisme0.setNumTel("$\"0<9YF+K");
			fail("Expecting exception: IllegalArgumentException");

		} catch (IllegalArgumentException e) {
			//
			// Le num\u00E9ro de t\u00E9l\u00E9phone n'est pas conforme !
			//
			verifyException("modele.Organisme", e);
		}
	}

	@Test(timeout = 4000)
	public void test26() throws Throwable {
		Organisme organisme0 = new Organisme("4310736960", "4310736960", "4310736960", "4310736960", "4310736960",
				"4310736960", "4310736960", "4310736960");
		organisme0.setNumTel("4310736960");
		assertEquals("4310736960", organisme0.getNom());
	}

	@Test(timeout = 4000)
	public void test27() throws Throwable {
		Organisme organisme0 = new Organisme("$\"0n<9!F+K", "$\"0n<9!F+K", "$\"0n<9!F+K", "$\"0n<9!F+K",
				"$\"0n<9!F+K", "$\"0n<9!F+K", "$\"0n<9!F+K", "$\"0n<9!F+K");
		// Undeclared exception!
		try {
			organisme0.setNumTel("$\"0n<9!F+K");
			fail("Expecting exception: IllegalArgumentException");

		} catch (IllegalArgumentException e) {
			//
			// Le num\u00E9ro de t\u00E9l\u00E9phone n'est pas conforme !
			//
			verifyException("modele.Organisme", e);
		}
	}

	@Test(timeout = 4000)
	public void test28() throws Throwable {
		Organisme organisme0 = new Organisme("rz|.844rTLK=E@FbF]", "rz|.844rTLK=E@FbF]", "rz|.844rTLK=E@FbF]",
				"rz|.844rTLK=E@FbF]", "rz|.844rTLK=E@FbF]", "rz|.844rTLK=E@FbF]", "rz|.844rTLK=E@FbF]",
				"rz|.844rTLK=E@FbF]");
		try {
			organisme0.setMail("rz|.844rTLK=E@FbF]");
			fail("Expecting exception: IllegalArgumentException");

		} catch (IllegalArgumentException e) {
			//
			// Le mail n'est donc pas valable
			//
			verifyException("modele.Organisme", e);
		}
	}

	@Test(timeout = 4000)
	public void test29() throws Throwable {
		Organisme organisme0 = new Organisme("gm'+%Yq0J6f)){)M", "gm'+%Yq0J6f)){)M", "gm'+%Yq0J6f)){)M",
				"gm'+%Yq0J6f)){)M", "l7Q)~", "l7Q)~", "0", (String) null);
		try {
			organisme0.setMail("0");
			fail("Expecting exception: IllegalArgumentException");

		} catch (IllegalArgumentException e) {
			//
			// Le mail n'est donc pas valable
			//
			verifyException("modele.Organisme", e);
		}
	}

	@Test(timeout = 4000)
	public void test30() throws Throwable {
		Organisme organisme0 = new Organisme("$YF3\"0n<9!F+K", "$YF3\"0n<9!F+K", "$YF3\"0n<9!F+K", "$YF3\"0n<9!F+K",
				"$YF3\"0n<9!F+K", "$YF3\"0n<9!F+K", "$YF3\"0n<9!F+K", "$YF3\"0n<9!F+K");
		try {
			organisme0.setNumSIRET("$YF3\"0n<9!F+K");
			fail("Expecting exception: IllegalArgumentException");

		} catch (IllegalArgumentException e) {
			//
			// Le num\u00E9ro de SIRET n'est pas conforme !
			//
			verifyException("modele.Organisme", e);
		}
	}

	@Test(timeout = 4000)
	public void test31() throws Throwable {
		Organisme organisme0 = new Organisme("$\"0n<9!F+K", "$\"0n<9!F+K", "$\"0n<9!F+K", "$\"0n<9!F+K",
				"$\"0n<9!F+K", "$\"0n<9!F+K", "$\"0n<9!F+K", "$\"0n<9!F+K");
		try {
			organisme0.setNumSIRET("$\"0n<9!F+K");
			fail("Expecting exception: IllegalArgumentException");

		} catch (IllegalArgumentException e) {
			//
			// Le num\u00E9ro de SIRET n'est pas conforme !
			//
			verifyException("modele.Organisme", e);
		}
	}

	@Test(timeout = 4000)
	public void test32() throws Throwable {
		Organisme organisme0 = new Organisme("4YF310n<94a6K", "4YF310n<94a6K", "4YF310n<94a6K", "4YF310n<94a6K",
				"4YF310n<94a6K", "4YF310n<94a6K", "4YF310n<94a6K", "4YF310n<94a6K");
		organisme0.setSpecialite("4YF310n<94a6K");
		assertEquals("4YF310n<94a6K", organisme0.getSpecialite());
	}

	@Test(timeout = 4000)
	public void test33() throws Throwable {
		Organisme organisme0 = new Organisme(",4", "FW\"0(;00!", "", "ZgDof#`", "", "", "ZgDof#`", (String) null);
		assertEquals("FW\"0(;00!", organisme0.getNom());

		organisme0.setNom("ZgDof#`");
		assertEquals("", organisme0.getCodePostal());
	}

	@Test(timeout = 4000)
	public void test34() throws Throwable {
		Organisme organisme0 = new Organisme("", "2gT'>", "", "2gT'>", "0", "}m%g4F", "k\"~e@wH1~_hBN", "0");
		String string0 = organisme0.getNumSIRET();
		assertEquals("2gT'>", organisme0.getVille());
		assertEquals("k\"~e@wH1~_hBN", organisme0.getNumTel());
		assertEquals("", organisme0.getAdresse());
		assertEquals("}m%g4F", organisme0.getMail());
		assertEquals("", string0);
		assertEquals("0", organisme0.getSpecialite());
		assertEquals("2gT'>", organisme0.getNom());
		assertEquals("0", organisme0.getCodePostal());
	}

	@Test(timeout = 4000)
	public void test35() throws Throwable {
		Organisme organisme0 = new Organisme("gm'+%Yq0J6f)){)M", "gm'+%Yq0J6f)){)M", "gm'+%Yq0J6f)){)M",
				"gm'+%Yq0J6f)){)M", "l7Q)~", "l7Q)~", "0", (String) null);
		organisme0.hashCode();
		assertEquals("l7Q)~", organisme0.getCodePostal());
		assertEquals("gm'+%Yq0J6f)){)M", organisme0.getNumSIRET());
		assertEquals("gm'+%Yq0J6f)){)M", organisme0.getAdresse());
		assertEquals("0", organisme0.getNumTel());
		assertEquals("l7Q)~", organisme0.getMail());
		assertEquals("gm'+%Yq0J6f)){)M", organisme0.getVille());
		assertEquals("gm'+%Yq0J6f)){)M", organisme0.getNom());
	}

	@Test(timeout = 4000)
	public void test36() throws Throwable {
		Organisme organisme0 = new Organisme("$\"0<9YF+K", "$\"0<9YF+K", "$\"0<9YF+K", "$\"0<9YF+K", "$\"0<9YF+K",
				"$\"0<9YF+K", "$\"0<9YF+K", "$\"0<9YF+K");
		organisme0.setCodePostal("$\"0<9YF+K");
		assertEquals("$\"0<9YF+K", organisme0.getNom());
	}

	@Test(timeout = 4000)
	public void test37() throws Throwable {
		Organisme organisme0 = new Organisme(",4", "FW\"0(;00!", "", "ZgDof#`", "", "", "ZgDof#`", (String) null);
		String string0 = organisme0.getSpecialite();
		assertEquals("", organisme0.getAdresse());
		assertEquals(",4", organisme0.getNumSIRET());
		assertEquals("ZgDof#`", organisme0.getNumTel());
		assertEquals("ZgDof#`", organisme0.getVille());
		assertEquals("", organisme0.getCodePostal());
		assertEquals("FW\"0(;00!", organisme0.getNom());
		assertEquals("", organisme0.getMail());
		assertNull(string0);
	}

	@Test(timeout = 4000)
	public void test38() throws Throwable {
		Organisme organisme0 = new Organisme(".K$P'rB", ".K$P'rB", ".K$P'rB", ".K$P'rB", "Organisme [num_SIRET=",
				".K$P'rB", "Organisme [num_SIRET=", "Organisme [num_SIRET=");
		String string0 = organisme0.getMail();
		assertEquals("Organisme [num_SIRET=", organisme0.getNumTel());
		assertEquals(".K$P'rB", string0);
		assertEquals(".K$P'rB", organisme0.getVille());
		assertEquals(".K$P'rB", organisme0.getNumSIRET());
		assertEquals("Organisme [num_SIRET=", organisme0.getCodePostal());
		assertEquals(".K$P'rB", organisme0.getAdresse());
		assertEquals(".K$P'rB", organisme0.getNom());
		assertEquals("Organisme [num_SIRET=", organisme0.getSpecialite());
	}

	@Test(timeout = 4000)
	public void test39() throws Throwable {
		Organisme organisme0 = new Organisme("gm'+%Yq0J6f)){)M", "gm'+%Yq0J6f)){)M", "gm'+%Yq0J6f)){)M",
				"gm'+%Yq0J6f)){)M", "l7Q)~", "l7Q)~", "0", (String) null);
		String string0 = organisme0.getNumTel();
		assertEquals("0", string0);
		assertEquals("gm'+%Yq0J6f)){)M", organisme0.getNom());
		assertEquals("gm'+%Yq0J6f)){)M", organisme0.getNumSIRET());
		assertEquals("l7Q)~", organisme0.getCodePostal());
		assertEquals("gm'+%Yq0J6f)){)M", organisme0.getAdresse());
		assertEquals("gm'+%Yq0J6f)){)M", organisme0.getVille());
		assertNotNull(string0);
		assertEquals("l7Q)~", organisme0.getMail());
	}

	@Test(timeout = 4000)
	public void test40() throws Throwable {
		Organisme organisme0 = new Organisme("", "", "", "", "", "", "", "");
		String string0 = organisme0.getVille();
		assertEquals("", string0);
	}

	@Test(timeout = 4000)
	public void test41() throws Throwable {
		Organisme organisme0 = new Organisme("$\"0n<9!F+K", "$\"0n<9!F+K", "$\"0n<9!F+K", "$\"0n<9!F+K",
				"$\"0n<9!F+K", "$\"0n<9!F+K", "$\"0n<9!F+K", "$\"0n<9!F+K");
		organisme0.setAdresse("$\"0n<9!F+K");
		assertEquals("$\"0n<9!F+K", organisme0.getNumTel());
	}

	@Test(timeout = 4000)
	public void test42() throws Throwable {
		Organisme organisme0 = new Organisme("modele.Organisme", "modele.Organisme", "modele.Organisme",
				"yi&%Es j=ikCio0", (String) null, "yi&%Es j=ikCio0", (String) null, "modele.Organisme");
		String string0 = organisme0.getNom();
		assertEquals("modele.Organisme", organisme0.getSpecialite());
		assertEquals("modele.Organisme", organisme0.getAdresse());
		assertEquals("modele.Organisme", string0);
		assertEquals("modele.Organisme", organisme0.getNumSIRET());
		assertEquals("yi&%Es j=ikCio0", organisme0.getMail());
		assertEquals("yi&%Es j=ikCio0", organisme0.getVille());
		assertNotNull(string0);
	}

	@Test(timeout = 4000)
	public void test43() throws Throwable {
		Organisme organisme0 = new Organisme("gm'+%Yq0J6f)){)M", "gm'+%Yq0J6f)){)M", "gm'+%Yq0J6f)){)M",
				"gm'+%Yq0J6f)){)M", "l7Q)~", "l7Q)~", "0", (String) null);
		assertEquals("gm'+%Yq0J6f)){)M", organisme0.getVille());

		organisme0.setVille("0");
		assertEquals("l7Q)~", organisme0.getMail());
	}

	@Test(timeout = 4000)
	public void test44() throws Throwable {
		Organisme organisme0 = new Organisme((String) null, "NP62", (String) null, (String) null, ", tel=", "NP62", "",
				".com");
		String string0 = organisme0.getAdresse();
		assertEquals("NP62", organisme0.getMail());
		assertNull(string0);
		assertEquals(".com", organisme0.getSpecialite());
		assertEquals("NP62", organisme0.getNom());
		assertEquals("", organisme0.getNumTel());
		assertEquals(", tel=", organisme0.getCodePostal());
	}

	@Test(timeout = 4000)
	public void test45() throws Throwable {
		Organisme organisme0 = new Organisme(",4", "FW\"0(;00!", "", "ZgDof#`", "", "", "ZgDof#`", (String) null);
		String string0 = organisme0.toString();
		assertEquals("ZgDof#`", organisme0.getVille());
		assertEquals(
				"Organisme [num_SIRET=,4, nom=FW\"0(;00!, adresse=, mail=, tel=ZgDof#`, sp\u00E9cialit\u00E9=null]",
				string0);
		assertEquals("", organisme0.getCodePostal());
	}

	@Test(timeout = 4000)
	public void test46() throws Throwable {
		Organisme organisme0 = new Organisme("", "", "", "", "", "", "", "");
		String string0 = organisme0.getCodePostal();
		assertEquals("", string0);
	}
}
