/*
 * This file was automatically generated by EvoSuite
 * Fri Jan 16 14:14:25 GMT 2026
 */

package test.modele;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertNull;
import static org.junit.Assert.assertTrue;

import java.time.Clock;
import java.time.LocalDate;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.time.MockClock;
import org.evosuite.runtime.mock.java.time.MockLocalDate;
import org.junit.Test;
import org.junit.runner.RunWith;

import modele.Paiement;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class Paiement_ESTest extends Paiement_ESTest_scaffolding {

	@Test(timeout = 4000)
	public void test00() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Paiement paiement0 = new Paiement("", (-4242.2F), "6-}H5v0", "6-}H5v0", localDate0, "", "", localDate0);
		assertEquals("6-}H5v0", paiement0.getLibelle());

		paiement0.setLibelle("");
		Paiement paiement1 = new Paiement("", (-2959.8264F), "", "", localDate0, "", "", localDate0);
		boolean boolean0 = paiement0.equals(paiement1);
		assertFalse(boolean0);
	}

	@Test(timeout = 4000)
	public void test01() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Paiement paiement0 = new Paiement((String) null, 0.0F, (String) null, "6-}H5v0", localDate0, (String) null, "",
				localDate0);
		String string0 = paiement0.getSensPaiement();
		assertEquals("", paiement0.getIdIntervention());
		assertNull(string0);
		assertEquals(0.0F, paiement0.getMontant(), 0.01F);
		assertEquals("6-}H5v0", paiement0.getLibelle());
	}

	@Test(timeout = 4000)
	public void test02() throws Throwable {
		LocalDate localDate0 = MockLocalDate.ofEpochDay((-1L));
		Paiement paiement0 = new Paiement("", (-427L), "", "", localDate0, "", (String) null, localDate0);
		String string0 = paiement0.getSensPaiement();
		assertNotNull(string0);
		assertEquals((-427.0F), paiement0.getMontant(), 0.01F);
	}

	@Test(timeout = 4000)
	public void test03() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Paiement paiement0 = new Paiement("OWQCEq:-xoYc[luv Z", 0.0F, (String) null, "", localDate0, (String) null,
				"?=f", localDate0);
		float float0 = paiement0.getMontant();
		assertEquals("?=f", paiement0.getIdIntervention());
		assertEquals("", paiement0.getLibelle());
		assertEquals(0.0F, float0, 0.01F);
		assertEquals("OWQCEq:-xoYc[luv Z", paiement0.getIdPaiement());
	}

	@Test(timeout = 4000)
	public void test04() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Paiement paiement0 = new Paiement("L,[+", (-4242.2F), (String) null, "vvb?HD9~mO8|", localDate0, "L,[+", "L,[+",
				localDate0);
		paiement0.setMontant(623.0F);
		float float0 = paiement0.getMontant();
		assertEquals(623.0F, float0, 0.01F);
	}

	@Test(timeout = 4000)
	public void test05() throws Throwable {
		Paiement paiement0 = new Paiement("tPWOfUe+*Rmx!J+%9", 0.0F, "tPWOfUe+*Rmx!J+%9", "tPWOfUe+*Rmx!J+%9",
				(LocalDate) null, "", "Q", (LocalDate) null);
		paiement0.getMoisConcerne();
		assertEquals(0.0F, paiement0.getMontant(), 0.01F);
		assertEquals("", paiement0.getIdBien());
		assertEquals("tPWOfUe+*Rmx!J+%9", paiement0.getIdPaiement());
		assertEquals("tPWOfUe+*Rmx!J+%9", paiement0.getSensPaiement());
		assertEquals("Q", paiement0.getIdIntervention());
		assertEquals("tPWOfUe+*Rmx!J+%9", paiement0.getLibelle());
	}

	@Test(timeout = 4000)
	public void test06() throws Throwable {
		Clock clock0 = MockClock.systemUTC();
		LocalDate localDate0 = MockLocalDate.now(clock0);
		Paiement paiement0 = new Paiement("", 1318.74F, "", (String) null, localDate0, "", (String) null, localDate0);
		String string0 = paiement0.getLibelle();
		assertNull(string0);
		assertEquals(1318.74F, paiement0.getMontant(), 0.01F);
	}

	@Test(timeout = 4000)
	public void test07() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Paiement paiement0 = new Paiement("", (-1014.13F), "modele.Paiement", "", localDate0, "", "lQN$BlMJrk7RE[(",
				localDate0);
		assertEquals("", paiement0.getLibelle());

		paiement0.setLibelle("uT2`)QP>O:f");
		paiement0.getLibelle();
		assertEquals("", paiement0.getIdBien());
	}

	@Test(timeout = 4000)
	public void test08() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Paiement paiement0 = new Paiement((String) null, 0.0F, (String) null, "6-}H5v0", localDate0, (String) null, "",
				localDate0);
		String string0 = paiement0.getIdPaiement();
		assertEquals("", paiement0.getIdIntervention());
		assertEquals(0.0F, paiement0.getMontant(), 0.01F);
		assertEquals("6-}H5v0", paiement0.getLibelle());
		assertNull(string0);
	}

	@Test(timeout = 4000)
	public void test09() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Paiement paiement0 = new Paiement("o'WPEq;-lT=lE", (-828.7404F), "o'WPEq;-lT=lE", "ZMZI/:", localDate0,
				"ZMZI/:", "", localDate0);
		String string0 = paiement0.getIdPaiement();
		assertEquals((-828.7404F), paiement0.getMontant(), 0.01F);
		assertEquals("ZMZI/:", paiement0.getIdBien());
		assertEquals("ZMZI/:", paiement0.getLibelle());
		assertEquals("o'WPEq;-lT=lE", paiement0.getSensPaiement());
		assertEquals("o'WPEq;-lT=lE", string0);
		assertEquals("", paiement0.getIdIntervention());
	}

	@Test(timeout = 4000)
	public void test10() throws Throwable {
		Clock clock0 = MockClock.systemUTC();
		LocalDate localDate0 = MockLocalDate.now(clock0);
		Paiement paiement0 = new Paiement("", 1318.74F, "", (String) null, localDate0, "", (String) null, localDate0);
		String string0 = paiement0.getIdIntervention();
		assertNull(string0);
		assertEquals(1318.74F, paiement0.getMontant(), 0.01F);
	}

	@Test(timeout = 4000)
	public void test11() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Paiement paiement0 = new Paiement("modele.Paiement", (-4242.2F), "modele.Paiement", "", localDate0,
				"modele.Paiement", "L,[+", localDate0);
		String string0 = paiement0.getIdIntervention();
		assertEquals("modele.Paiement", paiement0.getIdBien());
		assertEquals("modele.Paiement", paiement0.getSensPaiement());
		assertEquals((-4242.2F), paiement0.getMontant(), 0.01F);
		assertEquals("", paiement0.getLibelle());
		assertEquals("modele.Paiement", paiement0.getIdPaiement());
		assertEquals("L,[+", string0);
	}

	@Test(timeout = 4000)
	public void test12() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Paiement paiement0 = new Paiement("OWQCEq:-xoYc[luv Z", 0.0F, (String) null, "", localDate0, (String) null,
				"?=f", localDate0);
		String string0 = paiement0.getIdBien();
		assertNull(string0);
		assertEquals("", paiement0.getLibelle());
		assertEquals("OWQCEq:-xoYc[luv Z", paiement0.getIdPaiement());
		assertEquals("?=f", paiement0.getIdIntervention());
		assertEquals(0.0F, paiement0.getMontant(), 0.01F);
	}

	@Test(timeout = 4000)
	public void test13() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Paiement paiement0 = new Paiement("", (-4242.2F), "6-}H5v0", "6-}H5v0", localDate0, "", "", localDate0);
		assertEquals("", paiement0.getIdBien());

		paiement0.setIdBien("u~rT,#QmCQrpt+");
		paiement0.getIdBien();
		assertEquals("6-}H5v0", paiement0.getLibelle());
	}

	@Test(timeout = 4000)
	public void test14() throws Throwable {
		Paiement paiement0 = new Paiement(";", (-2417.356F), ";", ";", (LocalDate) null, ";", ";", (LocalDate) null);
		paiement0.getDatePaiement();
		assertEquals((-2417.356F), paiement0.getMontant(), 0.01F);
	}

	@Test(timeout = 4000)
	public void test15() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Paiement paiement0 = new Paiement("U/:ry<A\"}K2", (-2959.8264F), "", "", localDate0, "", "", localDate0);
		assertEquals("U/:ry<A\"}K2", paiement0.getIdPaiement());

		paiement0.setIdPaiement("");
		Paiement paiement1 = new Paiement("", (-2959.8264F), "", "", localDate0, "", "", localDate0);
		paiement1.setSensPaiement((String) null);
		boolean boolean0 = paiement1.equals(paiement0);
		assertFalse(boolean0);
	}

	@Test(timeout = 4000)
	public void test16() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Paiement paiement0 = new Paiement("", (-4242.2F), "6-}H5v0", "6-}H5v0", localDate0, "", "", localDate0);
		assertEquals("6-}H5v0", paiement0.getLibelle());

		paiement0.setLibelle("");
		Paiement paiement1 = new Paiement("", (-2959.8264F), "", "", localDate0, "", "", localDate0);
		boolean boolean0 = paiement1.equals(paiement0);
		assertFalse(boolean0);
	}

	@Test(timeout = 4000)
	public void test17() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Paiement paiement0 = new Paiement("U/:ry<A\"}K2", (-2959.8264F), "", "", localDate0, "", "", localDate0);
		assertEquals("U/:ry<A\"}K2", paiement0.getIdPaiement());

		paiement0.setIdPaiement("");
		Paiement paiement1 = new Paiement("", (-2959.8264F), "", "", localDate0, "", "", localDate0);
		boolean boolean0 = paiement1.equals(paiement0);
		assertTrue(boolean0);
	}

	@Test(timeout = 4000)
	public void test18() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Paiement paiement0 = new Paiement("", (-4242.2F), "6-}H5v0", "6-}H5v0", localDate0, "", "", localDate0);
		Paiement paiement1 = new Paiement("U/:ry<A\"}K2", (-2959.8264F), "", "", localDate0, "", "", localDate0);
		assertEquals("U/:ry<A\"}K2", paiement1.getIdPaiement());

		paiement1.setIdPaiement("");
		boolean boolean0 = paiement1.equals(paiement0);
		assertFalse(boolean0);
	}

	@Test(timeout = 4000)
	public void test19() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Paiement paiement0 = new Paiement("", 65.53F, "", "", localDate0, "", "2|3?wXFal9)z", localDate0);
		Paiement paiement1 = new Paiement("modele.Paiement", 65.53F, (String) null, "", localDate0, "", "", localDate0);
		boolean boolean0 = paiement0.equals(paiement1);
		assertEquals("", paiement0.getLibelle());
		assertEquals("modele.Paiement", paiement1.getIdPaiement());
		assertEquals("", paiement0.getIdBien());
		assertEquals(65.53F, paiement1.getMontant(), 0.01F);
		assertEquals("2|3?wXFal9)z", paiement0.getIdIntervention());
		assertEquals("", paiement1.getIdBien());
		assertFalse(boolean0);
		assertEquals("", paiement1.getLibelle());
		assertEquals("", paiement0.getSensPaiement());
	}

	@Test(timeout = 4000)
	public void test20() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Paiement paiement0 = new Paiement("", (-4242.2F), "6-}H5v0", "6-}H5v0", localDate0, "", "", localDate0);
		assertEquals("", paiement0.getIdBien());

		paiement0.setIdBien("u~rT,#QmCQrpt+");
		Paiement paiement1 = new Paiement("U/:ry<A\"}K2", (-2959.8264F), "", "", localDate0, "", "", localDate0);
		boolean boolean0 = paiement1.equals(paiement0);
		assertFalse(boolean0);
	}

	@Test(timeout = 4000)
	public void test21() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Paiement paiement0 = new Paiement(";", 0.0F, "", "uNN\"f|=", (LocalDate) null, "", "?=f", localDate0);
		Paiement paiement1 = new Paiement("", 0.0F, ";", "modele.Paiement", localDate0, "", "", (LocalDate) null);
		boolean boolean0 = paiement0.equals(paiement1);
		assertEquals(";", paiement0.getIdPaiement());
		assertEquals("?=f", paiement0.getIdIntervention());
		assertFalse(boolean0);
		assertEquals("", paiement1.getIdBien());
		assertEquals(";", paiement1.getSensPaiement());
		assertEquals("", paiement0.getIdBien());
		assertEquals("modele.Paiement", paiement1.getLibelle());
		assertEquals(0.0F, paiement1.getMontant(), 0.01F);
	}

	@Test(timeout = 4000)
	public void test22() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Paiement paiement0 = new Paiement("", (-4242.2F), "6-}H5v0", "6-}H5v0", localDate0, "", "", localDate0);
		Paiement paiement1 = new Paiement("U/:ry<A\"}K2", (-2959.8264F), "", "", localDate0, "", "", localDate0);
		boolean boolean0 = paiement1.equals(paiement0);
		assertEquals("6-}H5v0", paiement0.getLibelle());
		assertFalse(boolean0);
		assertEquals("", paiement0.getIdBien());
		assertEquals("U/:ry<A\"}K2", paiement1.getIdPaiement());
		assertEquals("6-}H5v0", paiement0.getSensPaiement());
		assertEquals("", paiement1.getIdIntervention());
		assertEquals((-2959.8264F), paiement1.getMontant(), 0.01F);
		assertEquals("", paiement0.getIdIntervention());
		assertEquals("", paiement1.getIdBien());
	}

	@Test(timeout = 4000)
	public void test23() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Paiement paiement0 = new Paiement("", (-2765.5051F), "", "mh9'gM]*PnN)", localDate0, "", "", localDate0);
		boolean boolean0 = paiement0.equals((Object) null);
		assertEquals("", paiement0.getSensPaiement());
		assertEquals("", paiement0.getIdPaiement());
		assertEquals((-2765.5051F), paiement0.getMontant(), 0.01F);
		assertEquals("", paiement0.getIdIntervention());
		assertEquals("mh9'gM]*PnN)", paiement0.getLibelle());
		assertFalse(boolean0);
		assertEquals("", paiement0.getIdBien());
	}

	@Test(timeout = 4000)
	public void test24() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Paiement paiement0 = new Paiement("", (-4242.2F), "7Iz8+eu['@vV^ |~", "7Iz8+eu['@vV^ |~", localDate0,
				"GhrcON1bC1mV@k_h", "7Iz8+eu['@vV^ |~", localDate0);
		boolean boolean0 = paiement0.equals(paiement0);
		assertTrue(boolean0);
		assertEquals("", paiement0.getIdPaiement());
		assertEquals("7Iz8+eu['@vV^ |~", paiement0.getSensPaiement());
		assertEquals("7Iz8+eu['@vV^ |~", paiement0.getIdIntervention());
		assertEquals("7Iz8+eu['@vV^ |~", paiement0.getLibelle());
		assertEquals((-4242.2F), paiement0.getMontant(), 0.01F);
		assertEquals("GhrcON1bC1mV@k_h", paiement0.getIdBien());
	}

	@Test(timeout = 4000)
	public void test25() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Paiement paiement0 = new Paiement("", (-4242.2F), "6-}H5v0", "6-}H5v0", localDate0, "", "", localDate0);
		boolean boolean0 = paiement0.equals("");
		assertFalse(boolean0);
		assertEquals("", paiement0.getIdPaiement());
		assertEquals("6-}H5v0", paiement0.getSensPaiement());
		assertEquals("", paiement0.getIdBien());
		assertEquals("6-}H5v0", paiement0.getLibelle());
		assertEquals((-4242.2F), paiement0.getMontant(), 0.01F);
		assertEquals("", paiement0.getIdIntervention());
	}

	@Test(timeout = 4000)
	public void test26() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Paiement paiement0 = new Paiement("modele.Paiement", (-4242.2F), "modele.Paiement", "", localDate0,
				"modele.Paiement", "L,[+", localDate0);
		float float0 = paiement0.getMontant();
		assertEquals("L,[+", paiement0.getIdIntervention());
		assertEquals((-4242.2F), float0, 0.01F);
		assertEquals("modele.Paiement", paiement0.getIdBien());
		assertEquals("", paiement0.getLibelle());
		assertEquals("modele.Paiement", paiement0.getSensPaiement());
		assertEquals("modele.Paiement", paiement0.getIdPaiement());
	}

	@Test(timeout = 4000)
	public void test27() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Paiement paiement0 = new Paiement("", (-4242.2F), "6-}H5v0", "6-}H5v0", localDate0, "", "", localDate0);
		paiement0.setDatePaiement(localDate0);
		assertEquals("6-}H5v0", paiement0.getSensPaiement());
		assertEquals("", paiement0.getIdPaiement());
		assertEquals("6-}H5v0", paiement0.getLibelle());
		assertEquals("", paiement0.getIdIntervention());
		assertEquals((-4242.2F), paiement0.getMontant(), 0.01F);
		assertEquals("", paiement0.getIdBien());
	}

	@Test(timeout = 4000)
	public void test28() throws Throwable {
		LocalDate localDate0 = MockLocalDate.ofEpochDay((-427L));
		Paiement paiement0 = new Paiement("", (-1835.72F), "", "", localDate0, "", "", localDate0);
		paiement0.getDatePaiement();
		assertEquals((-1835.72F), paiement0.getMontant(), 0.01F);
	}

	@Test(timeout = 4000)
	public void test29() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Paiement paiement0 = new Paiement("modele.Paiement", (-4242.2F), "modele.Paiement", "", localDate0,
				"modele.Paiement", "L,[+", localDate0);
		paiement0.setMoisConcerne(localDate0);
		assertEquals("", paiement0.getLibelle());
		assertEquals("modele.Paiement", paiement0.getSensPaiement());
		assertEquals("modele.Paiement", paiement0.getIdPaiement());
		assertEquals((-4242.2F), paiement0.getMontant(), 0.01F);
		assertEquals("modele.Paiement", paiement0.getIdBien());
		assertEquals("L,[+", paiement0.getIdIntervention());
	}

	@Test(timeout = 4000)
	public void test30() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Paiement paiement0 = new Paiement("", (-4242.2F), "6-}H5v0", "6-}H5v0", localDate0, "", "", localDate0);
		String string0 = paiement0.getIdPaiement();
		assertEquals("", paiement0.getIdIntervention());
		assertEquals("6-}H5v0", paiement0.getLibelle());
		assertEquals("", paiement0.getIdBien());
		assertEquals((-4242.2F), paiement0.getMontant(), 0.01F);
		assertEquals("6-}H5v0", paiement0.getSensPaiement());
		assertEquals("", string0);
	}

	@Test(timeout = 4000)
	public void test31() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Paiement paiement0 = new Paiement("", (-4242.2F), "6-}H5v0", "6-}H5v0", localDate0, "", "", localDate0);
		String string0 = paiement0.getIdIntervention();
		assertEquals("6-}H5v0", paiement0.getSensPaiement());
		assertEquals("", paiement0.getIdPaiement());
		assertEquals("6-}H5v0", paiement0.getLibelle());
		assertEquals("", string0);
		assertEquals((-4242.2F), paiement0.getMontant(), 0.01F);
		assertEquals("", paiement0.getIdBien());
	}

	@Test(timeout = 4000)
	public void test32() throws Throwable {
		LocalDate localDate0 = MockLocalDate.ofYearDay(133, 133);
		Paiement paiement0 = new Paiement("", 1.0F, "", "", localDate0, "oS(D", "", localDate0);
		String string0 = paiement0.getLibelle();
		assertEquals("oS(D", paiement0.getIdBien());
		assertEquals("", string0);
		assertEquals("", paiement0.getSensPaiement());
		assertEquals("", paiement0.getIdPaiement());
		assertEquals(1.0F, paiement0.getMontant(), 0.01F);
		assertEquals("", paiement0.getIdIntervention());
	}

	@Test(timeout = 4000)
	public void test33() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Paiement paiement0 = new Paiement("", (-2959.8264F), "", "", localDate0, "", "", localDate0);
		paiement0.hashCode();
		assertEquals((-2959.8264F), paiement0.getMontant(), 0.01F);
	}

	@Test(timeout = 4000)
	public void test34() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Paiement paiement0 = new Paiement("", (-4242.2F), "6-}H5v0", "6-}H5v0", localDate0, "", "", localDate0);
		String string0 = paiement0.getIdBien();
		assertEquals("6-}H5v0", paiement0.getSensPaiement());
		assertEquals("", paiement0.getIdPaiement());
		assertEquals("6-}H5v0", paiement0.getLibelle());
		assertEquals("", string0);
		assertEquals((-4242.2F), paiement0.getMontant(), 0.01F);
		assertEquals("", paiement0.getIdIntervention());
	}

	@Test(timeout = 4000)
	public void test35() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Paiement paiement0 = new Paiement("", (-4242.2F), "6-}H5v0", "6-}H5v0", localDate0, "", "", localDate0);
		String string0 = paiement0.getSensPaiement();
		assertEquals("6-}H5v0", paiement0.getLibelle());
		assertEquals("", paiement0.getIdIntervention());
		assertEquals("", paiement0.getIdPaiement());
		assertEquals((-4242.2F), paiement0.getMontant(), 0.01F);
		assertEquals("6-}H5v0", string0);
		assertEquals("", paiement0.getIdBien());
	}

	@Test(timeout = 4000)
	public void test36() throws Throwable {
		LocalDate localDate0 = MockLocalDate.ofEpochDay((-427L));
		Paiement paiement0 = new Paiement("", (-1835.72F), "", "", localDate0, "", "", localDate0);
		paiement0.setIdIntervention("modele.Paiement");
		assertEquals((-1835.72F), paiement0.getMontant(), 0.01F);
	}

	@Test(timeout = 4000)
	public void test37() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Paiement paiement0 = new Paiement("", (-1014.13F), "modele.Paiement", "", localDate0, "", "lQN$BlMJrk7RE[(",
				localDate0);
		paiement0.getMoisConcerne();
		assertEquals("", paiement0.getIdPaiement());
		assertEquals("", paiement0.getLibelle());
		assertEquals("lQN$BlMJrk7RE[(", paiement0.getIdIntervention());
		assertEquals((-1014.13F), paiement0.getMontant(), 0.01F);
		assertEquals("modele.Paiement", paiement0.getSensPaiement());
		assertEquals("", paiement0.getIdBien());
	}
}
