/*
 * This file was automatically generated by EvoSuite
 * Fri Jan 16 14:16:59 GMT 2026
 */

package test.modele;

import static org.evosuite.runtime.EvoAssertions.verifyException;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertTrue;
import static org.junit.Assert.fail;

import java.time.LocalDate;
import java.time.Month;
import java.time.Period;
import java.time.chrono.IsoChronology;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.time.MockLocalDate;
import org.evosuite.runtime.mock.java.time.chrono.MockIsoChronology;
import org.junit.Test;
import org.junit.runner.RunWith;

import modele.ReleveCompteur;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class ReleveCompteur_ESTest extends ReleveCompteur_ESTest_scaffolding {

	@Test(timeout = 4000)
	public void test00() throws Throwable {
		Period period0 = Period.ofMonths(0);
		IsoChronology isoChronology0 = period0.getChronology();
		LocalDate localDate0 = MockIsoChronology.dateNow(isoChronology0);
		ReleveCompteur releveCompteur0 = new ReleveCompteur(localDate0, 0, 0.0, 0.0, "", 0.0);
		double double0 = releveCompteur0.getPrixParUnite();
		assertEquals(0.0, double0, 0.01);
		assertEquals(0.0, releveCompteur0.getPartieFixe(), 0.01);
		assertEquals(0.0, releveCompteur0.getAncienIndex(), 0.01);
		assertEquals(0.0, releveCompteur0.getIndexCompteur(), 0.01);
	}

	@Test(timeout = 4000)
	public void test01() throws Throwable {
		LocalDate localDate0 = MockLocalDate.ofEpochDay((-1L));
		ReleveCompteur releveCompteur0 = new ReleveCompteur(localDate0, (-2456.50251769403), 2184.6308, 1.0,
				"HSgiIEkNQp9", 0.0);
		double double0 = releveCompteur0.getPartieFixe();
		assertEquals(0.0, releveCompteur0.getAncienIndex(), 0.01);
		assertEquals((-2456.50251769403), releveCompteur0.getIndexCompteur(), 0.01);
		assertEquals(1.0, double0, 0.01);
		assertEquals(2184.6308, releveCompteur0.getPrixParUnite(), 0.01);
	}

	@Test(timeout = 4000)
	public void test02() throws Throwable {
		LocalDate localDate0 = MockLocalDate.ofEpochDay(1L);
		ReleveCompteur releveCompteur0 = new ReleveCompteur(localDate0, 1073.0, 1075.358791851, 1811.5885,
				"gt?{s\"1C)--2", 3296.6);
		releveCompteur0.setPartieFixe((-1967.7));
		double double0 = releveCompteur0.getPartieFixe();
		assertEquals((-1967.7), double0, 0.01);
	}

	@Test(timeout = 4000)
	public void test03() throws Throwable {
		Period period0 = Period.ofMonths(0);
		IsoChronology isoChronology0 = period0.getChronology();
		LocalDate localDate0 = MockIsoChronology.dateNow(isoChronology0);
		ReleveCompteur releveCompteur0 = new ReleveCompteur(localDate0, 0, 0.0, 0.0, "", 0.0);
		releveCompteur0.setIndexCompteur((-1.0));
		double double0 = releveCompteur0.getIndexCompteur();
		assertEquals((-1.0), double0, 0.01);
	}

	@Test(timeout = 4000)
	public void test04() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		ReleveCompteur releveCompteur0 = new ReleveCompteur(localDate0, 1, 1, 1, "ETHw01?mbxz6csE}0+", (-1.0));
		releveCompteur0.setIdCompteur((String) null);
		releveCompteur0.getIdCompteur();
		assertEquals(1.0, releveCompteur0.getPartieFixe(), 0.01);
		assertEquals(1.0, releveCompteur0.getIndexCompteur(), 0.01);
		assertEquals((-1.0), releveCompteur0.getAncienIndex(), 0.01);
		assertEquals(1.0, releveCompteur0.getPrixParUnite(), 0.01);
	}

	@Test(timeout = 4000)
	public void test05() throws Throwable {
		Period period0 = Period.ofMonths(0);
		IsoChronology isoChronology0 = period0.getChronology();
		LocalDate localDate0 = MockIsoChronology.dateNow(isoChronology0);
		ReleveCompteur releveCompteur0 = new ReleveCompteur(localDate0, 0, 0.0, 0.0, "", 0.0);
		releveCompteur0.getIdCompteur();
		assertEquals(0.0, releveCompteur0.getPrixParUnite(), 0.01);
		assertEquals(0.0, releveCompteur0.getPartieFixe(), 0.01);
		assertEquals(0.0, releveCompteur0.getIndexCompteur(), 0.01);
		assertEquals(0.0, releveCompteur0.getAncienIndex(), 0.01);
	}

	@Test(timeout = 4000)
	public void test06() throws Throwable {
		LocalDate localDate0 = MockLocalDate.ofEpochDay((-1L));
		ReleveCompteur releveCompteur0 = new ReleveCompteur(localDate0, 1.0, 1.0, 0.0, "C=_b@.K%C)jA7", 1.0);
		releveCompteur0.getDateReleve();
		assertEquals(0.0, releveCompteur0.getPartieFixe(), 0.01);
		assertEquals(1.0, releveCompteur0.getIndexCompteur(), 0.01);
		assertEquals(1.0, releveCompteur0.getAncienIndex(), 0.01);
		assertEquals(1.0, releveCompteur0.getPrixParUnite(), 0.01);
	}

	@Test(timeout = 4000)
	public void test07() throws Throwable {
		Period period0 = Period.ofMonths(0);
		IsoChronology isoChronology0 = period0.getChronology();
		LocalDate localDate0 = MockIsoChronology.dateNow(isoChronology0);
		ReleveCompteur releveCompteur0 = new ReleveCompteur(localDate0, 0, 0.0, 0.0, "", 0.0);
		double double0 = releveCompteur0.getAncienIndex();
		assertEquals(0.0, releveCompteur0.getPartieFixe(), 0.01);
		assertEquals(0.0, double0, 0.01);
		assertEquals(0.0, releveCompteur0.getIndexCompteur(), 0.01);
		assertEquals(0.0, releveCompteur0.getPrixParUnite(), 0.01);
	}

	@Test(timeout = 4000)
	public void test08() throws Throwable {
		Period period0 = Period.ofDays((-123));
		IsoChronology isoChronology0 = period0.getChronology();
		LocalDate localDate0 = MockIsoChronology.dateNow(isoChronology0);
		ReleveCompteur releveCompteur0 = new ReleveCompteur(localDate0, 0.0, 1.0, (-123), "", 1601.4297);
		assertEquals(1601.4297, releveCompteur0.getAncienIndex(), 0.01);

		releveCompteur0.setAncienIndex((-123));
		double double0 = releveCompteur0.getAncienIndex();
		assertEquals((-123.0), double0, 0.01);
	}

	@Test(timeout = 4000)
	public void test09() throws Throwable {
		LocalDate localDate0 = MockLocalDate.ofEpochDay((-20L));
		ReleveCompteur releveCompteur0 = new ReleveCompteur(localDate0, (-20L), (-20L), (-20L), " partieFixe=", (-20L));
		ReleveCompteur releveCompteur1 = new ReleveCompteur(localDate0, 4563.624543086408, (-20L), (-20L),
				" partieFixe=", (-20L));
		boolean boolean0 = releveCompteur0.equals(releveCompteur1);
		assertEquals(4563.624543086408, releveCompteur1.getIndexCompteur(), 0.01);
		assertTrue(boolean0);
		assertEquals((-20.0), releveCompteur1.getAncienIndex(), 0.01);
		assertEquals((-20.0), releveCompteur1.getPartieFixe(), 0.01);
		assertEquals((-20.0), releveCompteur1.getPrixParUnite(), 0.01);
	}

	@Test(timeout = 4000)
	public void test10() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		Month month0 = Month.DECEMBER;
		LocalDate localDate1 = MockLocalDate.of(1, month0, 1);
		ReleveCompteur releveCompteur0 = new ReleveCompteur(localDate0, 520.944085, 4280.53042, (-3270.2589213278), "",
				(-1809.32496493));
		ReleveCompteur releveCompteur1 = new ReleveCompteur(localDate0, (-1809.32496493), 1136.3, 520.944085, "",
				4280.53042);
		releveCompteur1.setDateReleve(localDate1);
		boolean boolean0 = releveCompteur0.equals(releveCompteur1);
		assertFalse(releveCompteur1.equals((Object) releveCompteur0));
		assertFalse(boolean0);
	}

	@Test(timeout = 4000)
	public void test11() throws Throwable {
		LocalDate localDate0 = MockLocalDate.ofEpochDay((-1L));
		ReleveCompteur releveCompteur0 = new ReleveCompteur(localDate0, 1.0, 1.0, 0.0, "C=_b@.K%C)jA7", 1.0);
		ReleveCompteur releveCompteur1 = new ReleveCompteur(localDate0, (-2456.50251769403), 2184.6308, 1.0,
				"HSgiIEkNQp9", 0.0);
		boolean boolean0 = releveCompteur0.equals(releveCompteur1);
		assertEquals((-2456.50251769403), releveCompteur1.getIndexCompteur(), 0.01);
		assertEquals(1.0, releveCompteur1.getPartieFixe(), 0.01);
		assertEquals(2184.6308, releveCompteur1.getPrixParUnite(), 0.01);
		assertFalse(boolean0);
		assertEquals(0.0, releveCompteur1.getAncienIndex(), 0.01);
	}

	@Test(timeout = 4000)
	public void test12() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		ReleveCompteur releveCompteur0 = new ReleveCompteur(localDate0, (-618.412731056728), (-618.412731056728),
				(-618.412731056728), "", (-618.412731056728));
		boolean boolean0 = releveCompteur0.equals((Object) null);
		assertEquals((-618.412731056728), releveCompteur0.getAncienIndex(), 0.01);
		assertFalse(boolean0);
		assertEquals((-618.412731056728), releveCompteur0.getPrixParUnite(), 0.01);
		assertEquals((-618.412731056728), releveCompteur0.getPartieFixe(), 0.01);
		assertEquals((-618.412731056728), releveCompteur0.getIndexCompteur(), 0.01);
	}

	@Test(timeout = 4000)
	public void test13() throws Throwable {
		LocalDate localDate0 = MockLocalDate.ofEpochDay((-1L));
		ReleveCompteur releveCompteur0 = new ReleveCompteur(localDate0, 1.0, 1.0, 0.0, "C=_b@.K%C)jA7", 1.0);
		boolean boolean0 = releveCompteur0.equals(releveCompteur0);
		assertEquals(1.0, releveCompteur0.getPrixParUnite(), 0.01);
		assertTrue(boolean0);
		assertEquals(1.0, releveCompteur0.getIndexCompteur(), 0.01);
		assertEquals(0.0, releveCompteur0.getPartieFixe(), 0.01);
		assertEquals(1.0, releveCompteur0.getAncienIndex(), 0.01);
	}

	@Test(timeout = 4000)
	public void test14() throws Throwable {
		ReleveCompteur releveCompteur0 = new ReleveCompteur((LocalDate) null, 1.0, 2652.9, 2652.9, "gTx", 1.0);
		boolean boolean0 = releveCompteur0.equals("gTx");
		assertFalse(boolean0);
		assertEquals(1.0, releveCompteur0.getAncienIndex(), 0.01);
		assertEquals(1.0, releveCompteur0.getIndexCompteur(), 0.01);
		assertEquals(2652.9, releveCompteur0.getPrixParUnite(), 0.01);
		assertEquals(2652.9, releveCompteur0.getPartieFixe(), 0.01);
	}

	@Test(timeout = 4000)
	public void test15() throws Throwable {
		LocalDate localDate0 = MockLocalDate.now();
		ReleveCompteur releveCompteur0 = null;
		try {
			releveCompteur0 = new ReleveCompteur(localDate0, 31L, 31L, 31L, (String) null, 31L);
			fail("Expecting exception: IllegalArgumentException");

		} catch (IllegalArgumentException e) {
			//
			// Vous devez renseignez le compteur associ\u00E9 !
			//
			verifyException("modele.ReleveCompteur", e);
		}
	}

	@Test(timeout = 4000)
	public void test16() throws Throwable {
		ReleveCompteur releveCompteur0 = new ReleveCompteur((LocalDate) null, 1.0, 2652.9, 2652.9, "gTx", 1.0);
		double double0 = releveCompteur0.getAncienIndex();
		assertEquals(2652.9, releveCompteur0.getPartieFixe(), 0.01);
		assertEquals(2652.9, releveCompteur0.getPrixParUnite(), 0.01);
		assertEquals(1.0, releveCompteur0.getIndexCompteur(), 0.01);
		assertEquals(1.0, double0, 0.01);
	}

	@Test(timeout = 4000)
	public void test17() throws Throwable {
		ReleveCompteur releveCompteur0 = new ReleveCompteur((LocalDate) null, 1.0, 2652.9, 2652.9, "gTx", 1.0);
		releveCompteur0.setPrixParUnite((-1.0));
		double double0 = releveCompteur0.getPrixParUnite();
		assertEquals((-1.0), double0, 0.01);
	}

	@Test(timeout = 4000)
	public void test18() throws Throwable {
		ReleveCompteur releveCompteur0 = new ReleveCompteur((LocalDate) null, 1.0, 2652.9, 2652.9, "gTx", 1.0);
		String string0 = releveCompteur0.toString();
		assertEquals(
				"Relev\u00E9Compteur [dateRelev\u00E9=null, idCompteur=gTx, index=1.0, prixParUnit\u00E9=2652.9, partieFixe=2652.9]",
				string0);
		assertEquals(1.0, releveCompteur0.getAncienIndex(), 0.01);
	}

	@Test(timeout = 4000)
	public void test19() throws Throwable {
		ReleveCompteur releveCompteur0 = new ReleveCompteur((LocalDate) null, 1.0, 2652.9, 2652.9, "gTx", 1.0);
		releveCompteur0.getIdCompteur();
		assertEquals(1.0, releveCompteur0.getIndexCompteur(), 0.01);
		assertEquals(2652.9, releveCompteur0.getPartieFixe(), 0.01);
		assertEquals(1.0, releveCompteur0.getAncienIndex(), 0.01);
		assertEquals(2652.9, releveCompteur0.getPrixParUnite(), 0.01);
	}

	@Test(timeout = 4000)
	public void test20() throws Throwable {
		ReleveCompteur releveCompteur0 = new ReleveCompteur((LocalDate) null, 1.0, 2652.9, 2652.9, "gTx", 1.0);
		releveCompteur0.hashCode();
		assertEquals(1.0, releveCompteur0.getAncienIndex(), 0.01);
		assertEquals(2652.9, releveCompteur0.getPrixParUnite(), 0.01);
		assertEquals(1.0, releveCompteur0.getIndexCompteur(), 0.01);
		assertEquals(2652.9, releveCompteur0.getPartieFixe(), 0.01);
	}

	@Test(timeout = 4000)
	public void test21() throws Throwable {
		ReleveCompteur releveCompteur0 = new ReleveCompteur((LocalDate) null, 1.0, 2652.9, 2652.9, "gTx", 1.0);
		releveCompteur0.getDateReleve();
		assertEquals(1.0, releveCompteur0.getAncienIndex(), 0.01);
		assertEquals(1.0, releveCompteur0.getIndexCompteur(), 0.01);
		assertEquals(2652.9, releveCompteur0.getPartieFixe(), 0.01);
		assertEquals(2652.9, releveCompteur0.getPrixParUnite(), 0.01);
	}

	@Test(timeout = 4000)
	public void test22() throws Throwable {
		ReleveCompteur releveCompteur0 = new ReleveCompteur((LocalDate) null, 1.0, 2652.9, 2652.9, "gTx", 1.0);
		double double0 = releveCompteur0.getPrixParUnite();
		assertEquals(1.0, releveCompteur0.getAncienIndex(), 0.01);
		assertEquals(2652.9, releveCompteur0.getPartieFixe(), 0.01);
		assertEquals(2652.9, double0, 0.01);
		assertEquals(1.0, releveCompteur0.getIndexCompteur(), 0.01);
	}

	@Test(timeout = 4000)
	public void test23() throws Throwable {
		LocalDate localDate0 = MockLocalDate.ofEpochDay((-1L));
		ReleveCompteur releveCompteur0 = new ReleveCompteur(localDate0, 1.0, 1.0, 0.0, "C=_b@.K%C)jA7", 1.0);
		assertEquals(1.0, releveCompteur0.getIndexCompteur(), 0.01);

		releveCompteur0.setIndexCompteur(0.0);
		double double0 = releveCompteur0.getIndexCompteur();
		assertEquals(0.0, double0, 0.01);
	}

	@Test(timeout = 4000)
	public void test24() throws Throwable {
		LocalDate localDate0 = MockLocalDate.ofEpochDay((-1L));
		ReleveCompteur releveCompteur0 = new ReleveCompteur(localDate0, 1.0, 1.0, 0.0, "C=_b@.K%C)jA7", 1.0);
		double double0 = releveCompteur0.getPartieFixe();
		assertEquals(1.0, releveCompteur0.getPrixParUnite(), 0.01);
		assertEquals(1.0, releveCompteur0.getIndexCompteur(), 0.01);
		assertEquals(1.0, releveCompteur0.getAncienIndex(), 0.01);
		assertEquals(0.0, double0, 0.01);
	}

	@Test(timeout = 4000)
	public void test25() throws Throwable {
		ReleveCompteur releveCompteur0 = new ReleveCompteur((LocalDate) null, 1.0, 2652.9, 2652.9, "gTx", 1.0);
		double double0 = releveCompteur0.getIndexCompteur();
		assertEquals(2652.9, releveCompteur0.getPartieFixe(), 0.01);
		assertEquals(2652.9, releveCompteur0.getPrixParUnite(), 0.01);
		assertEquals(1.0, releveCompteur0.getAncienIndex(), 0.01);
		assertEquals(1.0, double0, 0.01);
	}
}
