--met a jour la charge liée à l'intervention
create or replace TRIGGER T_A_U_SAE_INTERVENTION
AFTER UPDATE ON SAE_INTERVENTION
FOR EACH ROW

BEGIN

    UPDATE SAE_CHARGE
    SET DATE_FACTURATION = :NEW.DATE_INTERVENTION, MONTANT = :NEW.MONTANT_FACTURE
    WHERE ID_INTERVENTION = :NEW.ID_INTERVENTION;

END;